Op deployer updates
ethereum-optimism/docs pull request #1020
Opened 2024-10-23 15:04 UTC by sbvegan

**Description**

op-deployer updates, will update the description when the draft is marked ready for review

2024-10-27 16:28 UTC, sbvegan commented on pages/builders/chain-operators/tools/op-deployer.mdx
> +todo: give example of 1s blocktime override
this doc was very helpful, thanks!

2024-10-28 17:06 UTC, tessr commented on pages/builders/chain-operators/tools/op-deployer.mdx
> +description: Learn how op-deployer can simplify deployment of the standard OP Stack.
Rather than introducing the concept of "standard OP Stack," can we say "standard OP Stack _Chain_"?

2024-10-28 17:06 UTC, tessr commented on pages/builders/chain-operators/tools/op-deployer.mdx
> +You can find the latest releases in the monorepo's [release page](https://github.com/ethereum-optimism/optimism/releases). The following guide is how to complie it from source. Assuming you have the
```suggestion
You can find the latest releases in the monorepo's [release page](https://github.com/ethereum-optimism/optimism/releases). The following guide is how to complie it from source. Assuming you have the Go toolchain and `just` installed, you can install `op-deployer` by following these steps:
```

2024-10-28 17:08 UTC, tessr commented on pages/builders/chain-operators/tools/op-deployer.mdx
> +  # test... junk mnemonic. You should replace these with your own addresses for production chains.
Perhaps a question for @mslipper, but can we generate junk roles that are more obviously junk roles? I can imagine someone skimming these files and failing to update the roles because they look like valid addresses.

2024-10-28 17:10 UTC, tessr commented on pages/builders/chain-operators/tools/op-deployer.mdx
Can we add a callout here, to add your chain to the SCR with these genesis files?

2024-10-28 20:11 UTC, mslipper commented on pages/builders/chain-operators/tools/op-deployer.mdx
> +  # test... junk mnemonic. You should replace these with your own addresses for production chains.
Yes I can do this easily. I think the initial intent shouldn't validate unless a dedicated `--dev` flag is passed. I can fix this.

2024-10-28 22:16 UTC, sbvegan commented
fixes: https://github.com/ethereum-optimism/devrel/issues/333

2024-10-28 22:56 UTC, bradleycamacho requested changes
Made a few comments, mostly about style/passive voice. Only thing that needs to be clarified is a mention of the superchain registry. This looks great, feel free to ping me on slack for approval if you need this out ASAP!

2024-10-28 22:56 UTC, bradleycamacho commented on pages/builders/chain-operators/tools/op-deployer.mdx
> +To install from source, follow the steps below. You will need to install the Go toolchain and `just` as prerequisites.
```suggestion
To alternatively install from source, follow the steps below. You will need to install the Go toolchain and `just` as prerequisites.
```

2024-10-28 22:56 UTC, bradleycamacho commented on pages/builders/chain-operators/tools/op-deployer.mdx
> +## Deployment Usage
```suggestion
## Deployment usage
```

2024-10-28 22:56 UTC, bradleycamacho commented on pages/builders/chain-operators/tools/op-deployer.mdx
> +### `init`: configuring your chain
```suggestion
### `init`: configure your chain
```

2024-10-28 22:56 UTC, bradleycamacho commented on pages/builders/chain-operators/tools/op-deployer.mdx
>  To get started with `op-deployer`, you need to create an intent file that outlines your desired chain configuration. You can use the built-in `op-deployer` utility to generate this file. Just run the
```suggestion
To get started with `op-deployer`, create an intent file that defines your desired chain configuration. Use the built-in `op-deployer` utility to generate this file. Run the following command to create an example intent file for a development chain:
```

2024-10-28 22:56 UTC, bradleycamacho commented on pages/builders/chain-operators/tools/op-deployer.mdx
>  To get started with `op-deployer`, you need to create an intent file that outlines your desired chain configuration. You can use the built-in `op-deployer` utility to generate this file. Just run the
There's a lot of (necessary) text in these steps, so I'm just trying to clean it up where possible

2024-10-28 22:56 UTC, bradleycamacho commented on pages/builders/chain-operators/tools/op-deployer.mdx
>  To get started with `op-deployer`, you need to create an intent file that outlines your desired chain configuration. You can use the built-in `op-deployer` utility to generate this file. Just run the
Alternatively:

```suggestion
To get started with `op-deployer`, create an intent file that defines your desired chain configuration. Use the built-in `op-deployer` utility to generate this file:
```

2024-10-28 22:56 UTC, bradleycamacho commented on pages/builders/chain-operators/tools/op-deployer.mdx
> +By default, `op-deployer` will fill in all other configuration variables with those that match the [standard configuration](https://specs.optimism.io/protocol/configurability.html). You can override
```suggestion
By default, `op-deployer` will fill in all other configuration variables with those that match the [standard configuration](https://specs.optimism.io/protocol/configurability.html). You can override these default settings by adding them to your intent file using the table below:
```

2024-10-28 22:56 UTC, bradleycamacho commented on pages/builders/chain-operators/tools/op-deployer.mdx
> +### `inspect`: generating genesis files and chain information
```suggestion
### `inspect`: generate genesis files and chain information
```

2024-10-28 22:56 UTC, bradleycamacho commented on pages/builders/chain-operators/tools/op-deployer.mdx
> +  You will need to write the output of these commands to files to make an addition to the [Superchain Registry](https://github.com/ethereum-optimism/superchain-registry).
>   You will need to write the output of these commands to files to make an addition to the [Superchain Registry](https://github.com/ethereum-optimism/superchain-registry).

This isn't clear to me. I assume it means "to be part of the Superchain Registry", but the "make an addition to" confuses me.

2024-10-28 22:56 UTC, bradleycamacho commented on pages/builders/chain-operators/tools/op-deployer.mdx
> +You'll be inspecting the `state.json` file, so you need to navigate into your working directory to inspect the file. With the contracts deployed, you can generate the genesis and rollup configuration
```suggestion
Inspect the `state.json` file by navigating to your working directory. With the contracts deployed, generate the genesis and rollup configuration files by running the following commands:"
```

2024-10-28 22:56 UTC, bradleycamacho commented on pages/builders/chain-operators/tools/op-deployer.mdx
> +## Bootstrap Usage
```suggestion
## Bootstrap usage
```

2024-10-28 22:56 UTC, bradleycamacho commented on pages/builders/chain-operators/tools/op-deployer.mdx
> +or other custom settlement chains.
```suggestion
You can also use `op-deployer` to deploy the contracts needed to run the `init`... `apply` flow on new chains. This process, called 'bootstrapping,' is useful when you want to use `op-deployer` with L3s, new testnets, or other custom settlement chains.
```

2024-10-28 22:56 UTC, bradleycamacho commented on pages/builders/chain-operators/tools/op-deployer.mdx
> +### OPCM Bootstrap
```suggestion
### OPCM bootstrap
```

2024-10-28 22:56 UTC, bradleycamacho commented on pages/builders/chain-operators/tools/op-deployer.mdx
> +### OPCM Bootstrap
I _assume_ this isn't a proper noun but could be wrong

2024-10-28 23:06 UTC, sbvegan commented on pages/builders/chain-operators/tools/op-deployer.mdx
> +  You will need to write the output of these commands to files to make an addition to the [Superchain Registry](https://github.com/ethereum-optimism/superchain-registry).
Okay I took another shot, lmk what you think

2024-10-28 23:09 UTC, bradleycamacho approved these changes
LGTM!

2024-10-29 14:09 UTC, merged