How to use general message passing
ethereum-optimism/docs pull request #1032
Opened 2024-10-28 17:58 UTC by krofax

**Description**

**Tests**

**Additional context**

**Metadata**

2024-10-30 10:55 UTC, krofax commented
@blmalone @skeletor-spaceman This PR is ready for review.

2024-10-30 12:39 UTC, brokewhale reviewed
looks good

2024-10-30 13:53 UTC, skeletor-spaceman requested changes

2024-10-30 13:53 UTC, skeletor-spaceman commented on pages/stack/interop/message-passing.mdx
> +  ### Prepare message sending
beware of bad formatting here

2024-10-30 13:53 UTC, skeletor-spaceman commented on pages/stack/interop/message-passing.mdx
> +  The [CrossChainMessenger](https://github.com/ethereum-optimism/optimism/blob/92ed64e171c6eb9c6a080c626640e8836f0653cc/packages/contracts-bedrock/src/L2/L2ToL2CrossDomainMessenger.sol) contract serv
```suggestion
  The [CrossDomainMessenger](https://github.com/ethereum-optimism/optimism/blob/92ed64e171c6eb9c6a080c626640e8836f0653cc/packages/contracts-bedrock/src/L2/L2ToL2CrossDomainMessenger.sol) contract serves as the primary interface for cross-chain communication. 
```

2024-10-30 13:53 UTC, skeletor-spaceman commented on pages/stack/interop/message-passing.mdx
> +  It initializes the connection to the L2 messenger contract and provides the base functionality for sending messages across chains.
this is not correct, the CDM does not connect to any L2 messenger, it's a standalone sender that only emits an event.

2024-10-30 13:53 UTC, skeletor-spaceman commented on pages/stack/interop/message-passing.mdx
> +  ```
where was this taken out of? there is no need to set a `_minGasLimit`. I think a confusion was made with the L1<>L2 messengers.

2024-10-30 13:53 UTC, skeletor-spaceman commented on pages/stack/interop/message-passing.mdx
> +  ```
same as above, a confusion was made between L1<>L2 and the interop L2<>L2 messengers

2024-10-30 13:59 UTC, krofax commented on pages/stack/interop/message-passing.mdx
> +  ```
@skeletor-spaceman What would be the correct code here, if we were to take out `_minGasLimit`?

2024-10-30 14:00 UTC, krofax commented on pages/stack/interop/message-passing.mdx
> +  ```
@skeletor-spaceman What will you advice here to improve the code?

2024-10-30 14:01 UTC, skeletor-spaceman commented on pages/stack/interop/message-passing.mdx
> +  ```
hey @krofax ! @zainbacchus will help on this :)

2024-10-31 12:44 UTC, krofax commented
@zainbacchus Please can you review this when you have the time.

2024-10-31 15:10 UTC, zainbacchus approved these changes

2024-10-31 15:25 UTC, krofax commented on pages/stack/interop/message-passing.mdx
> +```
@coderabbitai generate as simplified sequence diagram to match actual implementation.

2024-10-31 16:19 UTC, cpengilly approved these changes

2024-10-31 17:47 UTC, cpengilly commented on pages/stack/interop/_meta.json
> +    "superchain-erc20": "SuperchainERC20 token standard",
just "SuperchainERC" (no token standard)

2024-10-31 17:53 UTC, cpengilly commented on pages/stack/interop/_meta.json
> +    "superchain-erc20": "SuperchainERC20 token standard",
just "SuperchainERC20" (no token standard)
```suggestion
    "superchain-erc20": "SuperchainERC20",
```

2024-10-31 18:41 UTC, cpengilly commented on pages/stack/interop/_meta.json
> +    "superchain-erc20": "SuperchainERC20 token standard",
we're not using 'token standard' per product team

2024-11-01 09:57 UTC, krofax commented
@skeletor-spaceman Could you do a quick final review on your end? Zain has already approved.

2024-11-01 16:44 UTC, skeletor-spaceman approved these changes
matching zains approval

2024-11-01 18:06 UTC, merged