How to transfer a SuperchainERC20
ethereum-optimism/docs pull request #1048
Opened 2024-10-30 15:58 UTC by krofax

**Description**

This PR covers how to transfer a SuperchainERC20  using the `L2ToL2CrossDomainMessenger` contract.

**Tests**

**Additional context**

**Metadata**

- Fixes - https://github.com/ethereum-optimism/devrel/issues/376

2024-10-30 16:01 UTC, krofax commented
@zainbacchus, @blmalone,  @skeletor-spaceman This PR is ready for review.

2024-10-31 13:18 UTC, zainbacchus commented on pages/stack/interop/superchain-erc20.mdx
> +`SuperchainERC20` is an implementation of [ERC-7802](https://ethereum-magicians.org/t/erc-xxxx-crosschain-token-interface/21508) designed to enable asset interoperability in the Superchain.
https://ethereum-magicians.org/t/erc-7802-crosschain-token-interface/21508

2024-10-31 13:24 UTC, krofax commented on pages/stack/interop/superchain-erc20.mdx
> +`SuperchainERC20` is an implementation of [ERC-7802](https://ethereum-magicians.org/t/erc-xxxx-crosschain-token-interface/21508) designed to enable asset interoperability in the Superchain.
Great catch.
Updated!

2024-10-31 13:29 UTC, zainbacchus commented on pages/stack/interop/superchain-erc20.mdx
>  *   **Simplified deployments**: Provides a consistent, unified implementation for tokens across all Superchain-compatible networks and a common crosschain interface for the EVM ecosystem at large.
**Simplified deployments**: 0-infrastructure cost to make your token cross-chain. Provides a consistent, unified implementation for tokens across all Superchain-compatible networks and a common cross-chain interface for the EVM ecosystem at large.

2024-10-31 13:30 UTC, zainbacchus commented on pages/stack/interop/superchain-erc20.mdx
> +*   **Ethereum-aligned**: Implements ERC-7802, a unified interface that can be used across all of Ethereum to enable cross-chain mint/burn functionality.
Thoughts on Ethereum-aligned to Common standard?

2024-10-31 13:32 UTC, zainbacchus requested changes

2024-10-31 13:32 UTC, zainbacchus commented on pages/stack/interop/transfer-superchainERC20.mdx
> +
Since this is just using Supersim, I'd reccomend just keep it high level then direct people to the Supersim doc to detailed information

2024-10-31 13:34 UTC, zainbacchus commented on pages/stack/interop/transfer-superchainERC20.mdx
> +*   L2NativeSuperchainERC20: `0x420beeF000000000000000000000000000000001`
this is not a predeploy, was just an example in supersim

2024-10-31 14:14 UTC, krofax commented
@zainbacchus I've updated the docs, mind taking another look?

2024-10-31 15:07 UTC, zainbacchus commented on pages/stack/interop/transfer-superchainERC20.mdx
> +  *   Mint new tokens using the [L2NativeSuperchainERC20](https://github.com/ethereum-optimism/supersim/blob/main/contracts/src/L2NativeSuperchainERC20.sol) contract if you have minting permissions
should be SuperchainERC20 here :D

2024-10-31 15:08 UTC, zainbacchus commented on pages/stack/interop/transfer-superchainERC20.mdx
> +*   `supersim --interop.autorelay` for development environments
`supersim --interop.autorelay` is for Supersim not for testnet/mainnet so would remove

2024-10-31 15:33 UTC, krofax commented on pages/stack/interop/transfer-superchainERC20.mdx
> +  *   Mint new tokens using the [L2NativeSuperchainERC20](https://github.com/ethereum-optimism/supersim/blob/main/contracts/src/L2NativeSuperchainERC20.sol) contract if you have minting permissions
@zainbacchus Where are you referring to?

2024-10-31 16:20 UTC, cpengilly approved these changes

2024-10-31 16:51 UTC, merged