Deploy assets using Superchain ERC20
ethereum-optimism/docs pull request #1050
Opened 2024-10-30 21:25 UTC by bradleycamacho

Closes https://github.com/ethereum-optimism/devrel/issues/381

This doc explains how to deploy assests using the `SuperchainERC20` standard.

I've left various comments where I think specific review is needed

2024-10-30 21:28 UTC, bradleycamacho commented on pages/stack/interop/deploy-superchain-erc20.mdx
> +```solidity
We need an example here, but I wasn't able to find a good implementation of it. I use AI to create this, but we should absolutely replace this with something better.

2024-10-30 21:28 UTC, bradleycamacho commented on pages/stack/interop/deploy-superchain-erc20.mdx
> +An important thing to note, is that bridging assets through the Superchain using SuperchainERC20 never affects the supply of your asset. Supply is always fixed; bridging and moving your asset across
I added this based on the #docs message earlier today. Please let me know if we should move or rephrase. (Or remove!)

2024-10-30 21:28 UTC, bradleycamacho commented on pages/stack/interop/deploy-superchain-erc20.mdx
> +```solidity
I stole the comments from the specs page. We might want to expand on why the events "MUST" trigger

2024-10-30 21:28 UTC, bradleycamacho commented on pages/stack/interop/deploy-superchain-erc20.mdx
> +## Next steps
Are these the correct places to send folks to?

2024-10-30 21:39 UTC, zainbacchus commented on pages/stack/interop/deploy-superchain-erc20.mdx
> +An important thing to note, is that bridging assets through the Superchain using SuperchainERC20 never affects the supply of your asset. Supply is always fixed; bridging and moving your asset across
@bradleycamacho  wdyt about 

An important thing to note is using `crosschainBurn` and `crosschainMint` on the ` SuperchainERC20`to move your asset across the Superchain only affects which chain it is located on and does not change the overall supply of the token. This keeps the token’s total amount the same across all networks, ensuring its value stays stable during the move and that the `SuperchainERC20` retains a unified, global supply count.

2024-10-30 21:43 UTC, bradleycamacho commented on pages/stack/interop/deploy-superchain-erc20.mdx
> +An important thing to note, is that bridging assets through the Superchain using SuperchainERC20 never affects the supply of your asset. Supply is always fixed; bridging and moving your asset across
Fixed in latest commit

2024-10-31 15:56 UTC, bradleycamacho commented
@zainbacchus this is ready for your review whenever you have a second!

2024-11-07 17:04 UTC, zainbacchus commented on pages/stack/interop/deploy-superchain-erc20.mdx
> +```solidity
Here's ane xample:  https://github.com/ethereum-optimism/superchainerc20-starter/blob/main/packages/contracts/src/L2NativeSuperchainERC20.sol

2024-11-07 17:05 UTC, zainbacchus commented on pages/stack/interop/deploy-superchain-erc20.mdx
> +### Implement the ICrosschainERC20 interface
[IERC7802](https://specs.optimism.io/interop/token-bridging.html#ierc7802)

2024-11-07 17:05 UTC, zainbacchus commented on pages/stack/interop/deploy-superchain-erc20.mdx
> +Ensure that your token contract conforms to the `ICrosschainERC20` interface to support cross-chain minting and burning.
[IERC7802](https://specs.optimism.io/interop/token-bridging.html#ierc7802)

2024-11-07 17:06 UTC, zainbacchus commented on pages/stack/interop/deploy-superchain-erc20.mdx
> +```solidity
I would just point here https://specs.optimism.io/interop/token-bridging.html#implementation 

so we can ensure everythign stays up to date

2024-11-07 17:08 UTC, zainbacchus commented
General feedback, for any code pls point the user to the relevant specs section https://specs.optimism.io/interop/token-bridging.html#implementation

2024-11-07 17:08 UTC, zainbacchus requested changes

2024-11-07 17:08 UTC, zainbacchus commented on pages/stack/interop/deploy-superchain-erc20.mdx
> +This guide explains how to issue new assets with the `SuperchainERC20` standard and bridge them effectively using the `SuperchainERC20Bridge`. If you want more information about the `SuperchainERC20
remove word "standard"

2024-11-07 20:30 UTC, zainbacchus approved these changes
lgtm

2024-11-07 20:40 UTC, cpengilly approved these changes

2024-11-08 00:53 UTC, merged