holocene upgrade notice page and docs updates
ethereum-optimism/docs pull request #1108
Opened 2024-11-13 09:56 UTC by sbvegan

**Description**

Holocene is being shipped to the superchain, this documentation helps chain and node operators prepare for activation.

**Metadata**

- Fixes https://github.com/ethereum-optimism/devrel/issues/430

2024-11-19 13:16 UTC, BlocksOnAChain commented
@sbvegan this looks good to me, has all the details from our notion doc.
I would like us to get reviews from @sebastianst @ajsutton @mds1 before we merge it.

2024-11-19 15:17 UTC, mds1 commented on pages/builders/notices/holocene-changes.mdx
> +For more information on the Holocene implementation details, please review [Holocene specification](https://specs.optimism.io/protocol/holocene/overview.html).
The MIPS contract also changed, is that part of the block derivation change?

2024-11-19 15:19 UTC, mds1 commented on pages/builders/notices/holocene-changes.mdx
> +Besides this, chain operators must upgrade their chain's `SystemConfig` to the latest OP Contracts [v1.8.0-rc.1 release](https://github.com/ethereum-optimism/optimism/releases/tag/op-contracts%2Fv1.8
Only change is this new rc contains the deploy scripts
```suggestion
Besides this, chain operators must upgrade their chain's `SystemConfig` to the latest OP Contracts [v1.8.0-rc.2 release](https://github.com/ethereum-optimism/optimism/releases/tag/op-contracts%2Fv1.8.0-rc.2) to utilize the EIP-1559 configurability. The updated `SystemConfig` implementations are deployed at addresses:
```

2024-11-19 15:20 UTC, mds1 commented on pages/builders/notices/holocene-changes.mdx
> +Chain operators need to update their proxy contracts to point to these new implementations. An upgrade script in the monorepo can be used to facilitate the upgrade, please follow the instructions in
Related to above comment, this should link to the README at the `op-contracts/v1.8.0-rc.2` tag once it's released, instead of linking to develop

2024-11-19 15:21 UTC, mds1 commented on pages/builders/notices/holocene-changes.mdx
> +Chain operators need to update their proxy contracts to point to these new implementations. An upgrade script in the monorepo can be used to facilitate the upgrade, please follow the instructions in
this is because if you upgrade the SystemConfig before holocene, then call the new 1559 methods, it can cause an issue since the node won't know how to handle those calls
```suggestion
Chain operators need to update their proxy contracts to point to these new implementations. An upgrade script in the monorepo can be used to facilitate the upgrade, please follow the instructions in this [README](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/scripts/upgrades/holocene/README.md). Note that it is recommended to upgrade the SystemConfig after the Holocene activation. You need to upgrade if you want to reconfigure your EIP-1559 parameters.
```

2024-11-19 23:11 UTC, sbvegan commented on pages/builders/notices/holocene-changes.mdx
> +For more information on the Holocene implementation details, please review [Holocene specification](https://specs.optimism.io/protocol/holocene/overview.html).
Good call, updated

2024-11-20 00:12 UTC, cpengilly approved these changes

2024-11-20 00:23 UTC, ajsutton approved these changes

2024-11-20 04:14 UTC, sebastianst requested changes

2024-11-20 04:14 UTC, sebastianst commented on pages/builders/notices/holocene-changes.mdx
> +*   Sepolia: TBD
```suggestion
*   Sepolia: `0x29d06Ed7105c7552EFD9f29f3e0d250e5df412CD`
```
We've already deployed the impl for devnet and the impl can be shared between all chains on Sepolia.
[Reference](https://github.com/ethereum-optimism/superchain-ops/blob/811e0f0fa5718b1cf6c6fd8d216669cd673baded/tasks/sep-dev-0/006-holocene-sys-cfg/README.md)

2024-11-20 04:14 UTC, sebastianst commented on pages/builders/notices/holocene-changes.mdx
> +  *   [`op-node`, `op-batcher`, and `op-proposer` at `v1.10.0`](https://github.com/ethereum-optimism/optimism/releases/tag/op-node%2Fv1.10.0)
```suggestion
  *   [`op-node` at `v1.10.0`](https://github.com/ethereum-optimism/optimism/releases/tag/op-node%2Fv1.10.0)
```
We haven't release the batcher yet, still need to fix some bugs.

2024-11-20 04:14 UTC, sebastianst commented on pages/builders/notices/holocene-changes.mdx
> +    For Sepolia that is: `OP Sepolia`, `Base Sepolia`, `Mode Sepolia`, and `Zora Sepolia`.
We've added Metal Sepolia

2024-11-20 04:14 UTC, sebastianst commented on pages/builders/notices/holocene-changes.mdx
> +*   Sepolia: TBD
```suggestion
*   Sepolia: `0x6f86b56d26F60a86Ccd13048993C1cE410565DC1`
```
[Reference](https://github.com/ethereum-optimism/superchain-ops/tree/main/tasks/sep-dev-0/005-holocene-proofs#pre-deployments)

2024-11-20 04:24 UTC, sebastianst approved these changes

2024-11-20 04:24 UTC, merged