Superchain Registry docs
ethereum-optimism/docs pull request #1125
Opened 2024-11-18 22:00 UTC by bradleycamacho

- Adds top level nav category for `The Superchain`
- Adds a `Superchain Registry explainer`

2024-11-18 22:00 UTC, bradleycamacho commented
Closes https://github.com/ethereum-optimism/devrel/issues/419

2024-12-21 01:28 UTC, sbvegan requested changes
I'm very excited for this addition to the docs, great work! I've added suggestions where there is slight nuance, but as a whole, this is so good!

2024-12-21 01:28 UTC, sbvegan commented on pages/superchain/superchain-registry.mdx
> +*   A clear definition of what constitutes a Standard Chain and config
```suggestion
```

We actually don't do this in the registry in a clear way

2024-12-21 01:28 UTC, sbvegan commented on pages/superchain/superchain-registry.mdx
> +*   Validation checks to ensure chains follow the standard config before joining the Superchain Registry
```suggestion
*   Validation checks to ensure standard chains comply with the Standard Rollup Charter and non-standard chains pass baseline validation before joining the Superchain Registry
```

2024-12-21 01:28 UTC, sbvegan commented on pages/superchain/superchain-registry.mdx
> +*   A Superchain Registry repository that shows who's in the registry and what changes they have made to the standard config
```suggestion
*   A Superchain Registry repository that shows who's in the registry and the chain's configuration
```

2024-12-21 01:28 UTC, sbvegan commented on pages/superchain/superchain-registry.mdx
> +All chains must meet this config to meet the inclusion requirements for The Superchain. This config isn't meant to exclude chains, but instead make it easier to understand *how* to configure your cha
```suggestion
All chains must meet this config to meet the inclusion requirements for The Superchain. This configuration targets the Optimism Collective’s highest bar for security, uptime, and decentralization.
```

2024-12-21 01:28 UTC, sbvegan commented on pages/superchain/superchain-registry.mdx
> +## The Standard Config
```suggestion
## The Standard Rollup
```

I know we use "Standard Config" a lot, but I think we should move towards language defined in the Standard Rollup Charter: https://github.com/ethereum-optimism/OPerating-manual/blob/feat/standard-rollup-charter/Standard%20Rollup%20Charter.md#standard-rollup-charter

2024-12-21 01:28 UTC, sbvegan commented on pages/superchain/superchain-registry.mdx
> +The Standard Config is the set of requirements for an OP Stack chain to be considered a Standard Chain within the Superchain. These requirements are currently a draft, pending governance approval.
```suggestion
An OP Stack Standard Rollup meets the set of requirements to be a member of the Superchain. 
```

2024-12-21 01:28 UTC, sbvegan commented on pages/superchain/superchain-registry.mdx
> +You can find the current draft version of The Standard Config in the [specs repo](https://specs.optimism.io/protocol/configurability.html#op-stack-configurability).
```suggestion
You can find more details in the [Standard Rollup Charter documentation](/superchain/blockspace-charter).
```

2024-12-21 01:28 UTC, sbvegan commented on pages/superchain/superchain-registry.mdx
> +  We recommend using the [OP Contract Manager](/stack/opcm) to deploy L1 contracts that meet the Standard Config.
```suggestion
  We recommend using the [op-deployer](/builders/chain-operators/tools/op-deployer) to deploy L1 contracts and generate the L2 genesis file that meet the configuration requirements outlined in the [Standard Rollup Charter](/superchain/blockspace-charter).
```

2024-12-21 01:28 UTC, sbvegan commented on pages/superchain/blockspace-charter.mdx
> +Blockspace Charters and Standard Rollup Charter provide the essential technical and governance framework for the Superchain ecosystem. These frameworks provide a secure and scalable foundation for al
```suggestion
Blockspace Charters provide the essential technical and governance framework for the Superchain ecosystem. These frameworks provide a secure and scalable foundation for all stakeholders. By adhering to these charters, chain operators and users can operate confidently within the Superchain.
```

2024-12-21 01:28 UTC, sbvegan commented on pages/superchain/blockspace-charter.mdx
> +This doc mostly covers the charters, but references the Superchain Registry as they are all deeply connected. Read more about the Superchain Registry [here](./superchain-registry).
```suggestion
This doc mostly covers the charters, but references the Superchain Registry as they are all deeply connected. Read more about the Superchain Registry [here](/superchain/superchain-registry).
```

2024-12-21 01:28 UTC, sbvegan commented on pages/superchain/blockspace-charter.mdx
> +*   **Standard Rollup Charter:** Defines the technical and governance requirements for chains to achieve "Standard" status, ensuring consistency, high security, and operational reliability. Building
```suggestion
*   **Standard Rollup Charter:** Defines the technical and governance requirements for chains to become a Standard Rollup, ensuring consistency, high security, and operational reliability. Building on Blockspace Charters, this document sets specific technical and operational requirements for joining the Superchain. It determines which chains can be added to the Superchain Registry by outlining both on-chain and off-chain validation processes.
```

2024-12-21 01:28 UTC, sbvegan commented on pages/superchain/blockspace-charter.mdx
> +*   **Superchain Registry:** The Superchain Registry is a human-readable index of chains which serves as the source of truth for who's in the Superchain and what modifications they've made. Acting as
```suggestion
*   **Superchain Registry:** The Superchain Registry is a human-readable index of chains which serves as the source of truth for who's in the Superchain ecosystem and the chain's configuration. Acting as the chain validator, the registry checks for compliance with the Standard Rollup Charter. Chains with their `superchain_level = 1` meet all the criteria to be classified as a Standard Rollup.
```

2024-12-21 01:28 UTC, sbvegan commented on pages/superchain/blockspace-charter.mdx
> +By integrating with the Standard Rollup Charter, the registry offers an automated and transparent validation system. This ensures chains can independently demonstrate compliance. For additional detai
```suggestion
By integrating with the Standard Rollup Charter, the registry offers an automated and transparent validation system. This ensures chains can independently demonstrate compliance. For additional details, refer to the [Superchain Registry documentation](/superchain/superchain-registry).
```

2024-12-21 02:09 UTC, bradleycamacho commented on pages/superchain/superchain-registry.mdx
> +## The Standard Config
Gotcha, I'll remove it from these docs and take a pass at other docs like this in the future: https://docs.optimism.io/builders/chain-operators/configuration/rollup

2024-12-22 16:19 UTC, sbvegan commented
This PR fixes: https://github.com/ethereum-optimism/devrel/issues/369

2024-12-23 00:26 UTC, tessr requested changes

2024-12-23 00:26 UTC, tessr commented on pages/superchain/blockspace-charter.mdx
> +*   **Standard Rollup Charter:** Defines the technical and governance requirements for chains to achieve "Standard" status, ensuring consistency, high security, and operational reliability. Building
```suggestion
*   **Standard Rollup Charter:** The Standard Rollup Charter is the first blockspace charter, defining the technical and governance requirements for our highest-security blockspace. By adhering to the Standard Rollup Charter, chains can achieve "Standard" status, ensuring consistency, high security, and operational reliability.
```

Note that non-standard chains can also be added to the Superchain Registry, just not as standard chains (so these non-standard chains will be set with `superchain_level=0`).

2024-12-23 00:26 UTC, tessr commented on pages/superchain/blockspace-charter.mdx
> +*   **Superchain Registry:** The Superchain Registry is a human-readable index of chains which serves as the source of truth for who's in the Superchain and what modifications they've made. Acting as
Good suggestions here from @sbvegan.

Additionally, a few things I'd nix:

* the phrase "human-readable". Many (most) people are not comfortable reading the Superchain Registry which is one reason we also have plans to roll out a different front end. 
* the phrase "acting as the chain validator". The term "validator" is overloaded in crypto, so this phrase may have implications that we don't intend.

2024-12-23 00:26 UTC, tessr commented on pages/superchain/blockspace-charter.mdx
> +### Criteria
We need to add more detail here on which criteria are set by governance and which are more subjective and open to interpretation from the foundation. See this issue for more detail: https://github.com/ethereum-optimism/platforms-team/issues/438 (section on the updates to configurability.md also apply here)

2024-12-23 00:26 UTC, tessr commented on pages/superchain/blockspace-charter.mdx
> +*   **Solvency:** Verification that the chain's history is free from invalid withdrawals or outputs that could undercollateralize the bridge.
```suggestion
*   **Solvency:** Verification that all state transitions in the chain's history are valid, and free from invalid withdrawals or outputs that could undercollateralize the bridge.
```

2024-12-23 00:26 UTC, tessr commented on pages/superchain/blockspace-charter.mdx
> +*   Alignment with the [Law of Chains](https://github.com/ethereum-optimism/OPerating-manual/blob/main/Law%20of%20Chains.md), ensuring protections like censorship resistance and security.
```suggestion
*   Alignment with the [Law of Chains](https://github.com/ethereum-optimism/OPerating-manual/blob/main/Law%20of%20Chains.md), ensuring user protections like censorship resistance and security.
```

2024-12-23 00:26 UTC, tessr commented on pages/superchain/blockspace-charter.mdx
> +The Standard Rollup Charter is a specific blockspace charter, which are a type of framework defining high-level principles, criteria, and governance policies for managing blockspace. The Standard Rol
```suggestion
The Standard Rollup Charter is the blockspace charter that defines the requirements for being a standard chain, our highest-security flagship blockspace. The Standard Rollup Charter ensures that chains adhere to the technical and operational benchmarks necessary to maintain the highest standards of security, compatibility, and compliance in the Superchain.
```

2024-12-23 00:26 UTC, tessr commented on pages/superchain/blockspace-charter.mdx
> +*   **Security and integrity:** Chains must implement robust security measures to protect against attacks and ensure operational stability. Deterministic configurations and rigorous validations are k
IMO we can scrap these bullet points with the summary and jump straight to the specific criteria. We already explain in previous sections that the standard charter aims to maintain high security, uptime and accessibility requirements.

2024-12-23 00:26 UTC, tessr commented on pages/superchain/blockspace-charter.mdx
> +### On-chain criteria
```suggestion
### Onchain criteria
```

2024-12-23 00:26 UTC, tessr commented on pages/superchain/blockspace-charter.mdx
> +Read more about On-Chain checks in the [repo](https://github.com/ethereum-optimism/OPerating-manual/blob/feat/standard-rollup-charter/Standard%20Rollup%20Charter.md#onchain-criteria)
```suggestion
Read more about onchain checks in the [repo](https://github.com/ethereum-optimism/OPerating-manual/blob/feat/standard-rollup-charter/Standard%20Rollup%20Charter.md#onchain-criteria)
```

2024-12-23 00:26 UTC, tessr commented on pages/superchain/blockspace-charter.mdx
> +*   **Version validation:** Chains must deploy a governance-approved OP Stack release. Contracts must match the [standard bytecode](https://github.com/ethereum-optimism/superchain-registry/blob/main/
```suggestion
*   **Version validation:** Chains must deploy a governance-approved, up-to-date OP Stack release. Contracts must match the [standard bytecode](https://github.com/ethereum-optimism/superchain-registry/blob/main/validation/standard/standard-versions-mainnet.toml).
```

2024-12-23 00:26 UTC, tessr commented on pages/superchain/blockspace-charter.mdx
> +The history integrity check identifies discrepancies in chain history. While this process is expected to be phased out, it ensures chains meet the Law of Chains criteria during their transition to "S
```suggestion
The history integrity check identifies discrepancies in chain history, including invalid state transitions. These checks are only required for chains that have not been managed by the Optimism Security Council initially. 
```

2024-12-23 00:26 UTC, tessr commented on pages/superchain/blockspace-charter.mdx
> +*   **Will beta features qualify as Standard?** Not initially. Features require governance approval and testing.
```suggestion
*   **Will beta features qualify as Standard?** No. Beta features have not yet been approved by Optimism Governance. When features graduate from Beta to GA, they may be included in the standard rollup charter. 
```

2024-12-23 00:26 UTC, tessr commented on pages/superchain/blockspace-charter.mdx
> +*   **Is a custom gas token chain Standard?** No, chains must use standard gas configurations.
```suggestion
*   **Is a custom gas token chain Standard?** No, standard chains must use ethereum as their gas token.
```

2024-12-23 00:26 UTC, tessr commented on pages/superchain/blockspace-charter.mdx
> +The Superchain Registry serves as the authoritative compliance tool. It:
We should clarify here that the SRC has two important jobs:

1. It's a source of truth for everyone in the Superchain Ecosystem 
2. It can verify whether chains adhere to the Standard Rollup Charter. 

Because it can do (2), it can display a chain's standard status as part of (1).

2024-12-23 00:26 UTC, tessr commented on pages/superchain/superchain-registry.mdx
> +The Superchain Registry is a human-readable index of chains which serves as the source of truth for who's in the Superchain and what modifications they've made. The Superchain Registry introduces:
```suggestion
The Superchain Registry serves as the source of truth for who's in the Superchain Ecosystem and what modifications they've made. The Superchain Registry introduces:
```

We **must** always use the term Superchain Ecosystem rather than just Superchain here.

2024-12-23 00:26 UTC, tessr commented on pages/superchain/superchain-registry.mdx
> +The Superchain Registry is designed to outline and clarify the process for making your chain Superchain-compatible and joining the registry.
```suggestion

```

Recommend deleting this line

2024-12-23 00:26 UTC, tessr commented on pages/superchain/superchain-registry.mdx
> +If your chain meets the Standard Config requirements, [follow the steps in this guide](https://github.com/ethereum-optimism/superchain-registry/blob/main/docs/add-chain.md) to submit a pull request a
```suggestion
All Superchain Ecosystem members are welcome to join the Superchain Registry, regardless of whether they adhere to the standard rollup charter to not. To join the Registry, [follow the steps in this guide](https://github.com/ethereum-optimism/superchain-registry/blob/main/docs/add-chain.md) to submit a pull request and join the Superchain Ecosystem. This guide will help you set up your chain, create your environment, and run all the validation checks needed to ensure your chain is ready to join the Registry.
```

2024-12-23 15:50 UTC, sbvegan commented
fixes: https://github.com/ethereum-optimism/docs/issues/1187

2024-12-23 21:42 UTC, sbvegan approved these changes

2024-12-23 21:42 UTC, sbvegan commented on pages/superchain/blockspace-charter.mdx
> +Read more about onchain checks in the [repo](https://github.com/ethereum-optimism/OPerating-manual/blob/feat/standard-rollup-charter/Standard%20Rollup%20Charter.md#onchain-criteria) and about configu
```suggestion
Read more about onchain checks in the [repo](https://github.com/ethereum-optimism/OPerating-manual/blob/feat/standard-rollup-charter/Standard%20Rollup%20Charter.md#onchain-criteria).
```

2024-12-23 21:42 UTC, sbvegan commented on pages/superchain/blockspace-charter.mdx
> +Read more about onchain checks in the [repo](https://github.com/ethereum-optimism/OPerating-manual/blob/feat/standard-rollup-charter/Standard%20Rollup%20Charter.md#onchain-criteria) and about configu
I think its okay to remove this because its referenced in the first link on this page

2024-12-23 22:00 UTC, tessr approved these changes
A few more small suggestions but nothing blocking. Thanks y'all!

2024-12-23 22:00 UTC, tessr commented on pages/superchain/_meta.json
> +  "blockspace-charter": "Blockspace and Standard charters"
```suggestion
  "blockspace-charter": "Blockspace Charters and the Standard Rollup Charter"
```

2024-12-23 22:00 UTC, tessr commented on pages/superchain/blockspace-charter.mdx
> +description: Learn about Blockspace charters, the Standard Rollup charter, and the Superchain Registry.
```suggestion
description: Learn about Blockspace Charters, the Standard Rollup Charter, and the Superchain Registry.
```

I suspect we should either keep these concepts fully capitalized or fully lowercase -- either one is fine with me. But we shouldn't mix the casing.

2024-12-23 22:00 UTC, tessr commented on pages/superchain/blockspace-charter.mdx
> +The history integrity check identifies discrepancies in chain history, including invalid state transitions. These checks are only required for chains that have not been managed by the Optimism Securi
```suggestion
The history integrity check identifies discrepancies in chain history, including invalid state transitions. These checks are only required for chains that have not been managed by the Optimism Security Council from launch.
```

The original wording may have been my suggestion, but now that I'm rereading with fresh eyes, I think "from launch" is clearer than "initially".

2024-12-23 22:00 UTC, tessr commented on pages/superchain/superchain-registry.mdx
> +description: Learn about Optimism Superchain components, features, and roadmap.
```suggestion
description: Learn about the members of the Optimism Superchain ecosystem.
```

2024-12-23 22:00 UTC, tessr commented on pages/superchain/superchain-registry.mdx
> +*   A step-by-step process new chains can follow to join the registry
```suggestion
*   A step-by-step process new chains can follow to join the Registry
```

2024-12-23 22:00 UTC, tessr commented on pages/superchain/superchain-registry.mdx
> +*   A Superchain Registry repository that shows who's in the registry and the chain's configuration. Chains with `superchain_level = 1` meet all the criteria to be classified as a Standard Rollup.
```suggestion
*   A Superchain Registry repository that shows who's in the registry and the chain's configuration. Chains with `superchain_level = 1` have proven that they follow the Standard Rollup Charter, and can be classified as a Standard Rollup.
```

2024-12-23 22:00 UTC, tessr commented on pages/superchain/superchain-registry.mdx
> +An OP Stack Standard Rollup meets the set of requirements to be a member of the Superchain.
```suggestion
An OP Stack Standard Rollup follows the Standard Rollup Charter.
```

2024-12-23 22:00 UTC, tessr commented on pages/superchain/superchain-registry.mdx
> +All chains must meet this config to meet the inclusion requirements for The Superchain. This configuration targets the Optimism Collective's highest bar for security, uptime, and decentralization.
```suggestion
This configuration targets the Optimism Collective's highest bar for security, uptime, and decentralization.
```

2024-12-23 22:00 UTC, tessr commented on pages/superchain/superchain-registry.mdx
> +  We recommend using the [op-deployer](/builders/chain-operators/tools/op-deployer) to deploy L1 contracts and generate the L2 genesis file that meet the configuration requirements outlined in the [S
```suggestion
  We **strongly** recommend using the [op-deployer](/builders/chain-operators/tools/op-deployer) to deploy L1 contracts and generate the L2 genesis file that meet the configuration requirements outlined in the [Standard Rollup Charter](/superchain/blockspace-charter).
```

2024-12-23 22:00 UTC, tessr commented on pages/superchain/superchain-registry.mdx
> +## Joining the registry
```suggestion
## Joining the Registry
```

2024-12-24 00:38 UTC, merged