Add public docs for OP Stack network topologies
ethereum-optimism/docs pull request #1167
Opened 2024-12-09 13:54 UTC by krofax

**Description**

This PR introduces public-facing documentation outlining acceptable network topologies for OP Stack network deployments.

Summary:

- Externalized content from [Zach’s internal network design documentation](https://www.notion.so/oplabs/OP-Stack-Network-Design-Example-12ef153ee162807c8991fc4e35cac501) to address confusion noted in support tickets.

- Provides an example configuration with detailed recommendations for various node types, including sequencers, Tx ingress nodes, archive nodes, and public RPC nodes.

- Highlights best practices for redundancy, security, and monitoring.
- Incorporates YAML configuration snippets for easier implementation.

**Tests**

**Additional context**

**Metadata**

Include a link to any github issues that this may close in the following form:
- Fixes https://github.com/ethereum-optimism/devrel/issues/450

2024-12-09 23:13 UTC, sbvegan reviewed
@krofax can you please incorporate this issue as well: https://github.com/ethereum-optimism/docs/issues/918

I'd prefer if these details were added to the architecture page instead of spinning up a new page. I think its best if its under the chain operator section for now because its more practical guidance and not protocol specific information

2024-12-11 16:49 UTC, krofax commented
> @krofax can you please incorporate this issue as well: #918
> 
> I'd prefer if these details were added to the architecture page instead of spinning up a new page. I think its best if its under the chain operator section for now because its more practical guidance and not protocol specific information

@sbvegan I've updated the docs to reflect the changes.

2025-01-10 13:57 UTC, krofax commented
> > @krofax can you please incorporate this issue as well: #918
> > I'd prefer if these details were added to the architecture page instead of spinning up a new page. I think its best if its under the chain operator section for now because its more practical guidance and not protocol specific information
> 
> @sbvegan I've updated the docs to reflect the changes.

@sbvegan Checking here for a review when you have the time.

2025-01-11 00:23 UTC, sbvegan requested changes

2025-01-11 00:23 UTC, sbvegan commented on pages/builders/chain-operators/architecture.mdx
Lets add a short description of `op-challenger` at the top here

2025-01-11 00:23 UTC, sbvegan commented on pages/builders/chain-operators/architecture.mdx
Please remove the example image and the sentence: "Users sending
`eth_sendRawTransaction` requests can have their requests forwarded directly to the
Sequencer. All other RPC requests can be forwarded to replica nodes."

Its out of date

2025-01-14 16:48 UTC, krofax commented
@sbvegan I've resolved your comments here.

2025-01-14 16:50 UTC, sbvegan approved these changes

2025-01-14 16:58 UTC, merged