docs(interop/architecture): first version
ethereum-optimism/docs pull request #1181
Opened 2024-12-15 19:24 UTC by qbzzt

2024-12-18 17:25 UTC, zainbacchus commented on pages/stack/interop/architecture.mdx
> +Interoperability is provided by an [OP Supervisor](./op-supervisor), a new component that we expect every node operator to run in addition to the [rollup node](/builders/node-operators/architecture#r
Interoperability among OP Stack chains is enabled via a new service called [OP Supervisor](./op-supervisor). Every node operator is expected to run this service in addition to the [rollup node](/builders/node-operators/architecture#rollup-node) and [execution client](/builders/node-operators/architecture#execution-client).

2024-12-18 17:25 UTC, zainbacchus commented on pages/stack/interop/architecture.mdx
> +Interoperability is provided by an [OP Supervisor](./op-supervisor), a new component that we expect every node operator to run in addition to the [rollup node](/builders/node-operators/architecture#r
LMK thoughts on this reframe

2024-12-18 17:33 UTC, zainbacchus commented on pages/stack/interop/architecture.mdx
> +Additionally, OP Supervisor reads information from L1's consensus layer to know what L2 blocks are unsafe (not written to L1 yet), which are safe (written to L1, but might suffer from a [reorg](https
simplify: Additionally, OP Supervisor reads information from L1's consensus layer to know what the transaction safety of the L2 blocks.

2024-12-18 17:34 UTC, zainbacchus commented on pages/stack/interop/architecture.mdx
> +OP Supervisor holds a database of all the log events of all the chains in the interoperability cluster.
OP-Supervisor

2024-12-18 18:17 UTC, qbzzt commented on pages/stack/interop/architecture.mdx
> +Interoperability is provided by an [OP Supervisor](./op-supervisor), a new component that we expect every node operator to run in addition to the [rollup node](/builders/node-operators/architecture#r
It's probably better. There is a saying, *the passive voice should not be used*, but it's not applicable to technical writing.

2024-12-18 18:19 UTC, qbzzt commented on pages/stack/interop/architecture.mdx
> +Additionally, OP Supervisor reads information from L1's consensus layer to know what L2 blocks are unsafe (not written to L1 yet), which are safe (written to L1, but might suffer from a [reorg](https
KISS (Keep It Simple and Stupid) is better. We need to explain safely levels somewhere, but they probably would do better below.

2024-12-18 21:10 UTC, zainbacchus commented on pages/stack/interop/architecture.mdx
> +The transaction that receives the message calls a contract called [`CrossL2Inbox`](https://specs.optimism.io/interop/predeploys.html#crossl2inbox), directly or indirectly.
On "The transaction that receives the message calls", can we clarify this is on the destination chain?

2024-12-18 21:10 UTC, zainbacchus commented on pages/stack/interop/architecture.mdx
> +The transaction that receives the message calls a contract called [`CrossL2Inbox`](https://specs.optimism.io/interop/predeploys.html#crossl2inbox), directly or indirectly.
What does "directly or indirectly" mean?

2024-12-18 21:11 UTC, zainbacchus commented on pages/stack/interop/architecture.mdx
> +    participant src as Soucre Chain
Type for "Source chain"

2024-12-18 21:11 UTC, zainbacchus commented on pages/stack/interop/architecture.mdx
> +To understand *why* we need this additional component, it is useful to know how interop messages get from one blockchain to another.
Consider: 

"To understand *why* we need this additional service, it is useful to know how interop messages get from one blockchain to another."

2024-12-18 21:12 UTC, zainbacchus commented on pages/stack/interop/architecture.mdx
> +    participant src as Soucre Chain
typo*

2024-12-18 21:13 UTC, zainbacchus commented on pages/stack/interop/architecture.mdx
> +In addition to being written to L1, a *safe* block is one that only depends on other safe blocks.
I'm not sure what this section is trying to show, how is it relevant to interop architecture?

2024-12-18 21:15 UTC, zainbacchus commented on pages/stack/interop/architecture.mdx
> +  classDef chain fill:#FFC
This visual is hard to grok what its trying to convey.

Consider changing background color, label for OP Stack Chain cant be seen. 

What is Execution layer meant to show?

2024-12-18 21:16 UTC, zainbacchus commented on pages/stack/interop/architecture.mdx
> +Every node operator is expected to run this service in addition to the rollup node]\(/builders/node-operators/architecture#rollup-node) and [execution client](/builders/node-operators/architecture#ex
Broken link for rollup node

2024-12-18 21:17 UTC, zainbacchus commented on pages/stack/interop/architecture.mdx
> +{/*
What is this? Should it be deleted?

2024-12-18 21:17 UTC, zainbacchus commented on pages/stack/interop/architecture.mdx
> +*   For more info about how OP Stack interoperability works under the hood, \[check out the specs]
please fix formatting

2024-12-18 21:17 UTC, zainbacchus commented on pages/stack/interop/architecture.mdx
> +## Next steps
We'll want to review these at a later time, but fine for now

2024-12-18 22:04 UTC, qbzzt commented on pages/stack/interop/architecture.mdx
> +## Next steps
I agree.

2024-12-18 22:09 UTC, qbzzt commented on pages/stack/interop/architecture.mdx
> +*   For more info about how OP Stack interoperability works under the hood, \[check out the specs]
Yes. Shame on me, I ran prettier without verifying it did a good job.

2024-12-18 22:28 UTC, qbzzt commented on pages/stack/interop/architecture.mdx
> +Every node operator is expected to run this service in addition to the [rollup node](/builders/node-operators/architecture#rollup-node) and [execution client](/builders/node-operators/architecture#ex
Except that the links do work.

2024-12-18 22:41 UTC, qbzzt commented on pages/stack/interop/architecture.mdx
> +  classDef chain fill:#FFC
I simplified the visual as much as I can. Can you look at the new version and see if it's OK? If not, let's remove it.

2024-12-18 22:42 UTC, qbzzt commented on pages/stack/interop/architecture.mdx
> +To understand *why* we need this additional component, it is useful to know how interop messages get from one blockchain to another.
OK, changed.

2024-12-18 22:44 UTC, qbzzt commented on pages/stack/interop/architecture.mdx
> +The transaction that receives the message calls a contract called [`CrossL2Inbox`](https://specs.optimism.io/interop/predeploys.html#crossl2inbox), directly or indirectly.
Done.

2024-12-18 23:46 UTC, qbzzt commented on pages/stack/interop/architecture.mdx
> +In addition to being written to L1, a *safe* block is one that only depends on other safe blocks.
I hope I clarified it.

2024-12-19 20:24 UTC, zainbacchus commented on pages/stack/interop/architecture.mdx
> +{/*
bump on this

2024-12-19 20:24 UTC, zainbacchus commented on pages/stack/interop/architecture.mdx
> +{/*
Broken issues

2024-12-19 20:25 UTC, zainbacchus approved these changes

2024-12-19 21:54 UTC, qbzzt commented on pages/stack/interop/architecture.mdx
> +{/*
You mean commented out because I thought I might need it. Deleted now.

2024-12-19 21:56 UTC, qbzzt commented on pages/stack/interop/architecture.mdx
> +To trust that an unsafe block is valid and is going to become safe and then finalized, you need to trust not only the sequencer that produces it, but also all the other sequencer that produce other b
Fixed in latest version.

2024-12-19 21:57 UTC, qbzzt commented on pages/stack/interop/architecture.mdx
> +{/*
The comment? Yes. I thought I'll need that text, so I didn't want to delete it while working on the page. But now we're close to done with the page.

2024-12-20 18:14 UTC, bradleycamacho requested changes
This looks great! Just added a few small request, great job! Feel free to ping me directly once ready for a review

2024-12-20 18:14 UTC, bradleycamacho commented on pages/stack/interop/architecture.mdx
> +An OP Stack node consists of two pieces of software: a consensus client (e.g. op-node) and an execution client, which is responsible for processing user transactions, constructing blocks and serving
> a consensus client (e.g. op-node) and an execution client, which is responsible for processing user transactions, constructing blocks and serving RPC calls.

Weird phrasing here. Should it be `user transactions and constructing blocks`? I'd take another stab at this.

2024-12-20 18:14 UTC, bradleycamacho commented on pages/stack/interop/architecture.mdx
> +An OP Stack node consists of two pieces of software: a consensus client (e.g. op-node) and an execution client, which is responsible for processing user transactions, constructing blocks and serving
```suggestion
An OP Stack node consists of two pieces of software: a consensus client (e.g. op-node) and an execution client, which is responsible for processing user transactions, constructing blocks and serving RPC calls. Interoperability among OP Stack chains is enabled via a new service called [OP Supervisor.](/stack/interop/op-supervisor) Every node operator is expected to run this service in addition to the [rollup node](/builders/node-operators/architecture#rollup-node) and [execution client](/builders/node-operators/architecture#execution-client).
```

2024-12-20 18:14 UTC, bradleycamacho commented on pages/stack/interop/architecture.mdx
> +An OP Stack node consists of two pieces of software: a consensus client (e.g. op-node) and an execution client, which is responsible for processing user transactions, constructing blocks and serving
It seems we refer to the service as "OP Supervisor" in general, and refer to it as `op-supervisor` when we're talking about the service in detail. Using the following doc as my reference right now: https://docs.optimism.io/stack/interop/op-supervisor

2024-12-20 18:14 UTC, bradleycamacho commented on pages/stack/interop/architecture.mdx
> +An OP Stack node consists of two pieces of software: a consensus client (e.g. op-node) and an execution client, which is responsible for processing user transactions, constructing blocks and serving
Maybe we should always refer to it as `op-supervisor`?

2024-12-20 18:14 UTC, bradleycamacho commented on pages/stack/interop/architecture.mdx
> +OP-Supervisor holds a database of all the log events of all the chains in the interoperability cluster.
```suggestion
`op-supervisor` holds a database of all the log events of all the chains in the interoperability cluster.
```

2024-12-20 18:14 UTC, bradleycamacho commented on pages/stack/interop/architecture.mdx
> +Every event can potentially initiate a cross domain message, and it is the job of OP-Supervisor to validate that the log event really happened on the source chain.
```suggestion
Every event can potentially initiate a cross domain message, and it is the job of `op-supervisor` to validate that the log event really happened on the source chain.
```

2024-12-20 18:14 UTC, bradleycamacho commented on pages/stack/interop/architecture.mdx
> +Additionally, OP-Supervisor reads information from L1's consensus layer to determine the transaction safety of L2 blocks.
```suggestion
Additionally, `op-supervisor` reads information from L1's consensus layer to determine the transaction safety of L2 blocks.
```

2024-12-20 18:14 UTC, bradleycamacho commented on pages/stack/interop/architecture.mdx
> +## How messages get from one chain to the other
This seems really well written. Maybe shorten this a bit then move the content over and link to https://deploy-preview-1181--docs-optimism.netlify.app/stack/interop/cross-chain-message?

2024-12-20 18:14 UTC, bradleycamacho commented on pages/stack/interop/architecture.mdx
> +## How messages get from one chain to the other
At a minimum, we should tie the two docs together somehow w/ a link

2024-12-20 18:14 UTC, bradleycamacho commented on pages/stack/interop/architecture.mdx
> +An OP Stack node consists of two pieces of software: a consensus client (e.g. op-node) and an execution client, which is responsible for processing user transactions, constructing blocks and serving
We should link to https://docs.optimism.io/stack/interop/op-supervisor

2024-12-20 18:14 UTC, bradleycamacho commented on pages/stack/interop/architecture.mdx
> +Block `n` in chain A is even finalized, and immune from reorgs.
```suggestion
Block `n` in chain `A` is even finalized, and immune from reorgs.
```

2024-12-21 02:31 UTC, qbzzt commented on pages/stack/interop/architecture.mdx
> +An OP Stack node consists of two pieces of software: a consensus client (e.g. op-node) and an execution client, which is responsible for processing user transactions, constructing blocks and serving
Here's how I see it

| Protocol general term | Optimism implementation |
| - | - |
|  execution client | `op-geth` |
| consensus client | `op-node` |
| OP Supervisor | `op-supervisor` |

2024-12-21 02:42 UTC, qbzzt commented on pages/stack/interop/architecture.mdx
> +## How messages get from one chain to the other
I'd rather not because we need a simple version here for the architecture to make sense. I will add a link to the messages page, which I need to edit at some point anyway.

2024-12-21 03:00 UTC, bradleycamacho commented on pages/stack/interop/architecture.mdx
> +## How messages get from one chain to the other
Sounds good to me!

2024-12-21 03:05 UTC, bradleycamacho commented on pages/stack/interop/architecture.mdx
> +An OP Stack node consists of two pieces of software: a consensus client (e.g. op-node) and an execution client, which is responsible for processing user transactions, constructing blocks and serving
Gotcha, I'm also not familiar enough to make the call - but I think you're going in the right direction. @zainbacchus probably has some ideas here.

We can take some time to chat about this, I don't think it should block this PR. We can edit things later.

2024-12-21 03:06 UTC, bradleycamacho approved these changes

2024-12-21 14:45 UTC, zainbacchus commented on pages/stack/interop/architecture.mdx
> +An OP Stack node consists of two pieces of software: a consensus client (e.g. op-node) and an execution client, which is responsible for processing user transactions, constructing blocks and serving
Fine to keep the general term as OP Supervisor for now! Lets merge it!

2024-12-24 00:30 UTC, merged