Asterisc support guide
ethereum-optimism/docs pull request #1189
Opened 2024-12-20 15:52 UTC by bradleycamacho

2024-12-20 19:35 UTC, cpengilly approved these changes

2024-12-23 22:14 UTC, pauldowman requested changes
There are some specific comments within, but as a more high-level comment I'd suggest some changes:

1. A lot of this just mirrors what's in the Asterisc README, which I think is unnecessary. 

We should have only one source of the same content. If it belongs here then it should move, but we shouldn't have both. Also, the things in the README like how to compile and run tests are probably not what the audience of the OP docs are looking for, I think the repo README is more appropriate for those anyway.

2. It could be more minimal by explicitly referencing the Cannon docs, and saying explicitly that it's equivalent, it's an alternative implementation of a fault proof VM, and also that Kona is a alternative implementation of a fault-proof program. 

So explicitly saying that Asterisc + Kona is equivalent to Cannon + op-program. 

Then we could just mention the differences (that Asterisc is RISC-V instead of MIPS, and that Kona is written in Rust, where as op-program is written in Go). We could provide more detail on additional differences if you want.

3. Just as the Cannon page talks about op-program (since they're two parts of the same system), I think the Asterisc page should mention Kona.

4. I think it should be inside "experimental".

2024-12-23 22:14 UTC, pauldowman commented on pages/stack/fault-proofs/asterisc.mdx
> +Asterisc enables parties to reach consensus on shared execution trace states. In cases of dispute, it identifies the diverging execution step. Commitments are generated for memory, registers, CSR, an
Similar to a comment above, it's not Asterisc alone that "enables parties to reach consensus on shared execution trace states". It's the fault proof program (Kona in this case) running in a fault proof VM (Asterisc in this case) that does this.

2025-01-02 19:36 UTC, bradleycamacho commented
@pauldowman I implemented most of your feedback! Let me chat with the docs team before moving it to the experimental section, since I have complex thoughts about that section as a whole.

A few questions:

- I cut most of the procedural and reference content and just pointed folks towards the repo. The doc is now pretty barebones, which is fine, but I just wanted to ensure there isn't any pertinent missing info. When you compare the doc to the Cannon doc, it seems that Asterisc is much less complex. Is there any info we should add to this doc?
- Cannon and Asterisc are equivalent, but to what degree? Is there content we should pull from the Cannon doc and place into a general FPVM doc all the individual FPVM docs point to?

I'm going to take another pass on this regardless to polish it up, just let me know!

2025-01-03 00:04 UTC, pauldowman requested changes
I added a couple of link fixes. And I'm not sure about the "Benefits over xx" sections. Personally I don''t think it makes sense to compare to Cartesi or Arbitrum here.

2025-01-03 00:04 UTC, pauldowman commented on pages/stack/fault-proofs/asterisc.mdx
> +3.  Compile test binaries using the [`Makefile`](https://github.com/ethereum-optimism/asteriscblob/master/tests/go-tests/Makefile).
```suggestion
3.  Compile test binaries using the [`Makefile`](https://github.com/ethereum-optimism/asterisc/blob/master/tests/go-tests/Makefile).
```

2025-01-03 00:10 UTC, pauldowman commented
As an FYI, I noticed that the docs in the Asterisc repo also need some attention. I think the eng team should take a pass at those first so I opened this: https://github.com/ethereum-optimism/asterisc/issues/112

2025-04-10 13:30 UTC, closed without merging