chain op 4844 updates
ethereum-optimism/docs pull request #481
Opened 2024-02-10 06:16 UTC by cpengilly

- new page added
- linking to new page from chain config page
- update dictionary

2024-02-12 19:15 UTC, smartcontracts commented on pages/builders/chain-operators/ecotone.mdx
> +  As soon as Ecotone is activated, you will have a temporary decrease in L1 fee margin.
What does this mean? Why does it happen and why is it temporary?

2024-02-12 19:15 UTC, smartcontracts commented on pages/builders/chain-operators/ecotone.mdx
> +  At the point of the fork, your current scalar setting will become the `BaseFeeScalar` value, and the `BlobBaseFeeScalar` will be set to `0`.
Is there anything we can link to that explains the fee scalar?

2024-02-12 19:15 UTC, smartcontracts commented on pages/builders/chain-operators/ecotone.mdx
> +  When you enable blobs, if your chain is submitting mostly full blobs, then you'll want to configure `BlobBaseFeeScalar` to be somewhere around the previous `BaseFeeScalar`, and configure `BaseFeeSc
I think these instructions are too vague. Can we replace them with something more exact?

2024-02-12 19:15 UTC, smartcontracts commented on pages/builders/chain-operators/ecotone.mdx
> +    If you are not operating at high throughput (e.g., \~1000 txs per day) and if you only half-fill blobs, you will want to *double* these values to adjust accordingly.
Is 1000 txs per day considered high throughput or low throughput? It's unclear from the way it's being used here.

2024-02-12 19:15 UTC, smartcontracts commented on pages/builders/chain-operators/ecotone.mdx
> +  *   newl1BlobBaseFeeScalar = prevl1BaseFeeScalar \* 1.1
`prevL1BaseFeeScalar` or `prevL1BlobBaseFeeScalar`?

2024-02-12 19:15 UTC, smartcontracts commented on pages/builders/chain-operators/ecotone.mdx
> +  function _getL1FeeEcotone(bytes memory _data) internal view returns (uint256) {
This function is presented without context.

2024-02-12 19:15 UTC, smartcontracts commented on pages/builders/chain-operators/ecotone.mdx
> +  The [ecotone-scalar utility](https://github.com/ethereum-optimism/optimism/tree/develop/op-chain-ops/cmd/ecotone-scalar) converts a desired `BaseFeeScalar` and `BlobBaseFeeScalar` into a single val
> Overhead is ignored and can be set to `0`

Is this new with Ecotone? What does this mean?

2024-02-12 19:15 UTC, smartcontracts commented on pages/builders/chain-operators/ecotone.mdx
> +    You'll have to provide a `gas-price` to geth when making this call.
Below instructions give a gas price of `10000000`, is that the gas price that should be used here or does the user need to determine the gas price themselves?

2024-02-12 19:15 UTC, smartcontracts commented on pages/builders/chain-operators/ecotone.mdx
> +  Finally, run the post-Ecotone GPO functions:
What does this mean?

2024-02-12 19:15 UTC, smartcontracts commented on pages/builders/chain-operators/ecotone.mdx
> +    The batcher will have to be restarted for it to take effect.
> for it to take effect

For what to take effect?

2024-02-12 19:15 UTC, smartcontracts commented on pages/builders/chain-operators/ecotone.mdx
> +    *   You have to submit batches within the 12-hour sequencing window.
I was under the impression that the Sequencing window was 24 hours by default. Can we confirm whether it's 12 or 24 hours? Also, the Sequencing window may be different for custom chains, they will need to check their own Sequencing window to confirm.

2024-02-12 19:15 UTC, smartcontracts commented on pages/builders/chain-operators/ecotone.mdx
> +    Consider the following risks if setting `OP_BATCHER_MAX_CHANNEL_DURATION` to target 5 vs 10 hours:
A bit of a non sequitur, confused where 5 vs 10 hours came from.

2024-02-12 19:15 UTC, smartcontracts commented on pages/builders/chain-operators/ecotone.mdx
> +    *   If your chain is currently processing less than 128KB per 5 hours, then your chain will not be using full blobs, so you will be overpaying.
Is there any tool that someone can use to determine how long their chain takes to generate 128KB?

2024-02-12 19:15 UTC, smartcontracts commented on pages/builders/chain-operators/ecotone.mdx
> +After posting to blob space, chains will follow these steps to switch from blobs back to using calldata.
Chains *can* follow these steps. 

Also, why would someone want to do this? Should be clarified.

2024-02-12 19:15 UTC, smartcontracts commented on pages/builders/chain-operators/ecotone.mdx
> +  To change the batcher configuration, either remove the `OP_BATCHER_DATA_AVAILABILITY_TYPE` parameter, or set its value to "calldata" instead of "blobs".
Let's simplify these instructions and just have them set `OP_BATCHER_DATA_AVAILABILITY_TYPE=calldata`, I prefer giving fewer options when we can. Just keeps things easier for readers.

2024-02-12 19:15 UTC, smartcontracts commented on pages/builders/chain-operators/ecotone.mdx
> +*   If you'd like to set up snap sync for your chain, you'll need to set up a [Boot Node](../node-operators/management/configuration#configuring-peer-to-peer-networking).
Snap sync is a new feature, is that being included with Ecotone? Do we have any other docs about this? It's a pretty major feature.

2024-02-12 19:15 UTC, smartcontracts commented on pages/builders/chain-operators/ecotone.mdx
> +  *   newL1BaseFeeScalar = prevl1BaseFeeScalar \* 1.1
Can we put these inside backticks?

2024-02-14 18:51 UTC, cpengilly commented on pages/builders/chain-operators/ecotone.mdx
> +  At the point of the fork, your current scalar setting will become the `BaseFeeScalar` value, and the `BlobBaseFeeScalar` will be set to `0`.
added this: For more details on fee scalar, see [Transaction Fees, Ecotone section](/stack/transactions/fees#ecotone).

2024-02-14 19:02 UTC, cpengilly commented on pages/builders/chain-operators/ecotone.mdx
> +  *   newL1BaseFeeScalar = prevl1BaseFeeScalar \* 1.1
fixed in recent draft

2024-02-14 19:02 UTC, cpengilly commented on pages/builders/chain-operators/ecotone.mdx
> +  function _getL1FeeEcotone(bytes memory _data) internal view returns (uint256) {
fixed in recent draft

2024-02-14 19:02 UTC, cpengilly commented on pages/builders/chain-operators/ecotone.mdx
> +  *   newl1BlobBaseFeeScalar = prevl1BaseFeeScalar \* 1.1
fixed in recent draft

2024-02-15 20:02 UTC, K-Ho commented on pages/builders/chain-operators/ecotone.mdx
> +*   If you'd like to set up snap sync for your chain, you'll need to set up a [Boot Node](../node-operators/management/configuration#configuring-peer-to-peer-networking).
we're going to add snap sync later

2024-02-15 20:03 UTC, K-Ho commented on pages/builders/chain-operators/ecotone.mdx
> +    *   If your chain is currently processing less than 128KB per 5 hours, then your chain will not be using full blobs, so you will be overpaying.
sadly not yet, I think michael and I can queue this up if folks want, otherwise we can do a rough estimate of X txs per day = roughly Y KB/ day

2024-02-15 20:03 UTC, K-Ho commented on pages/builders/chain-operators/ecotone.mdx
> +  As soon as Ecotone is activated, you will have a temporary decrease in L1 fee margin.
added in latest pr

2024-02-15 23:38 UTC, cpengilly commented on pages/builders/chain-operators/ecotone.mdx
> +  To change the batcher configuration, either remove the `OP_BATCHER_DATA_AVAILABILITY_TYPE` parameter, or set its value to "calldata" instead of "blobs".
updated, some parts kept per kev

2024-02-15 23:38 UTC, cpengilly commented on pages/builders/chain-operators/ecotone.mdx
> +After posting to blob space, chains will follow these steps to switch from blobs back to using calldata.
updated

2024-02-15 23:38 UTC, cpengilly commented on pages/builders/chain-operators/ecotone.mdx
> +For custom chains, the activation dates can be set in the `rollup.json` or in overrides (CLI) by calling `op-node` help or `op-geth` help.
yes, updated

2024-02-15 23:38 UTC, cpengilly commented on pages/builders/chain-operators/ecotone.mdx
> +  The [ecotone-scalar utility](https://github.com/ethereum-optimism/optimism/tree/develop/op-chain-ops/cmd/ecotone-scalar) converts a desired `BaseFeeScalar` and `BlobBaseFeeScalar` into a single val
updated

2024-02-15 23:39 UTC, cpengilly commented on pages/builders/chain-operators/ecotone.mdx
> +  Finally, run the post-Ecotone GPO functions:
deleted

2024-02-15 23:39 UTC, cpengilly commented on pages/builders/chain-operators/ecotone.mdx
> +    The batcher will have to be restarted for it to take effect.
updated

2024-02-15 23:39 UTC, cpengilly commented on pages/builders/chain-operators/ecotone.mdx
> +    *   You have to submit batches within the 12-hour sequencing window.
updated and clarified

2024-02-16 22:24 UTC, sebastianst submitted a review, later dismissed

2024-02-16 22:24 UTC, sebastianst commented on pages/builders/chain-operators/management/configuration.mdx
> +  To minimize costs, we recommend setting your  `OP_BATCHER_MAX_CHANNEL_DURATION` to target 5 hours, with a value of `1500` L1 blocks. When non-zero, this parameter is the max time (in L1 blocks, whi
Note that we can pack 130kB into a blob.

Wondering if we want to recommend 6h or even 9h. It would still be well below the 12h seq window. Why would we feel uncomfortable with 3h to get a batch blob onto L1?

2024-02-16 22:24 UTC, sebastianst commented on pages/builders/node-operators/network-upgrades/ecotone.mdx
> +  The Ecotone testnet network upgrade for OP Goerli activated at **1707238800 Tue Feb 6 17:00:00 UTC 2024**. Ecotone Sepolia releases are published and will activate at Wed Feb 21 17:00:00 UTC 2024.
why mention the unix time stamp for goerli, but not sepolia? I'd do both or none.

2024-02-16 22:24 UTC, sebastianst commented on pages/builders/node-operators/network-upgrades/ecotone.mdx
> +*   [`op-node`](https://github.com/ethereum-optimism/optimism/releases/tag/v1.5.0)
We could already mention
```suggestion
*   [`op-geth`](https://github.com/ethereum-optimism/op-geth/releases/tag/v1.101308.1)
*   [`op-node`](https://github.com/ethereum-optimism/optimism/releases/tag/v1.6.1)
```
here. These already contain the optimistic mainnet activation (see release notes).

2024-02-16 22:24 UTC, sebastianst commented on pages/builders/node-operators/network-upgrades/ecotone.mdx
> +*   For node operators of custom chains not included in the `superchain-registry`, the activation dates can be set in the `rollup.json` (set `ecotone_time`) or set the activation time via overrides (
Note that even if the ecotone activation is configured via the `rollup.json`, it still needs to be configured separately on `op-geth` via cmdline flag.

2024-02-16 22:24 UTC, sebastianst commented on pages/builders/node-operators/network-upgrades/ecotone.mdx
> +*   **Option 1:**  Configure a `beacon-archiver`. There is a configurable `beacon-archiver` that will allow nodes to sync blob data that is older than 18 days - after blobs are 18 days old, normal be
```suggestion
*   **Option 1:**  Configure a `beacon-archiver`. There is a configurable `beacon-archiver` that will allow nodes to sync blob data that is older than 18 days - after blobs are 18 days old, normal beacon nodes will  "prune" or remove them. If your node is already in sync with the head of the chain, you won't need to use a `beacon-archiver`.
```

2024-02-16 22:24 UTC, sebastianst commented on pages/builders/node-operators/network-upgrades/ecotone.mdx
> +*   **Option 1:**  Configure a `beacon-archiver`. There is a configurable `beacon-archiver` that will allow nodes to sync blob data that is older than 18 days - after blobs are 18 days old, normal be
There's a misunderstanding here. The `--l1.beacon-archiver` would be used in conjunction with the `blob-archiver` from Option 3. So it could be instead
* Option 1 (old Option 2): Run beacon node with blobs pruning disabled.
* Option 2 (Option 1 & 3 merged): Run `blob-archiver` and configure op-node to use the `blob-archiver` api service with `--l1.beacon-archiver`.
* Option 3: If you don't want to operate any Beacon infra, use an external Beacon service like quicknode (I think this has been mentioned before)

2024-02-16 22:24 UTC, sebastianst commented on pages/builders/notices/ecotone-fee-changes.mdx
> +  Ecotone Sepolia releases are published and will activate at Wed Feb 21 17:00:00 UTC 2024. The Ecotone upgrade for OP Mainnet is not scheduled yet.
```suggestion
  Ecotone Sepolia releases are published and will activate at Wed Feb 21 17:00:00 UTC 2024. The Ecotone upgrade for OP Mainnet is optimistically scheduled for Mon Mar 18 17:00:01 UTC 2024.
```

2024-02-16 22:24 UTC, sebastianst commented on pages/builders/notices/ecotone-fee-changes.mdx
> +*   [op-node, op-batcher, op-proposer v1.5.1](https://github.com/ethereum-optimism/optimism/releases/tag/v1.5.1)
```suggestion
*   [op-geth v1.101308.1](https://github.com/ethereum-optimism/op-geth/releases/tag/v1.101308.1)
*   [op-node, op-batcher, op-proposer v1.6.1](https://github.com/ethereum-optimism/optimism/releases/tag/v1.6.1)
```

2024-02-16 22:24 UTC, sebastianst commented on pages/builders/notices/ecotone-fee-changes.mdx
> +2.  Configure the Ecotone Activation Date
This section seems quite duplicated, is that on purpose?

2024-02-16 22:24 UTC, sebastianst commented on pages/builders/notices/ecotone-fee-changes.mdx
> +2.  Configure the Ecotone Activation Date
here duplicated 3rd time?

2024-02-16 23:33 UTC, sbvegan commented on pages/builders/chain-operators/management/blobs.mdx
> +*   If you'd like to set up snap sync for your chain, you'll need to set up a [Boot Node](/builders/node-operators/management/configuration#configuring-peer-to-peer-networking).
Let's remove them, @trianglesphere had some comments on it today:

> - Not yet code complete because of a last minute bug that we found, but we know what needs to be fixed
> - Snap sync needs several chain operator changes that must go live first otherwise node operators won’t be able to find other op-geth nodes to sync from

2024-02-16 23:35 UTC, sbvegan commented on pages/builders/node-operators/network-upgrades/ecotone.mdx
> +  The Ecotone testnet network upgrade for OP Goerli activated at **1707238800 Tue Feb 6 17:00:00 UTC 2024**. Ecotone Sepolia releases are published and will activate at Wed Feb 21 17:00:00 UTC 2024.
This has been updated on main, so it'll need to be resolved when main is pulled into this PR branch

2024-02-16 23:37 UTC, sbvegan commented on pages/builders/notices/ecotone-fee-changes.mdx
> +  Ecotone Sepolia releases are published and will activate at Wed Feb 21 17:00:00 UTC 2024. The Ecotone upgrade for OP Mainnet is not scheduled yet.
We want to be careful here about timelines, we might want to check with Cristina on if saying, "optimistically scheduled is fine"

2024-02-19 01:28 UTC, cpengilly commented on pages/builders/chain-operators/management/blobs.mdx
> +    Because you must purchase an entire blob, you will be paying for 120KB of data, but submitting less, and must adjust your scalar accordingly.
updated in doc @K-Ho can you verify if the calculation will change now b/c of this?

2024-02-19 01:31 UTC, cpengilly commented on pages/builders/chain-operators/management/blobs.mdx
> +  ```
added!

2024-02-19 01:33 UTC, cpengilly commented on pages/builders/chain-operators/management/blobs.mdx
> +  <Callout>
going to keep this callout but removing the other duplicate callouts :)

2024-02-19 01:33 UTC, cpengilly commented on pages/builders/chain-operators/management/blobs.mdx
> +*   If you'd like to set up snap sync for your chain, you'll need to set up a [Boot Node](/builders/node-operators/management/configuration#configuring-peer-to-peer-networking).
removing

2024-02-19 01:47 UTC, cpengilly commented on pages/builders/node-operators/network-upgrades/ecotone.mdx
> +*   **Option 1:**  Configure a `beacon-archiver`. There is a configurable `beacon-archiver` that will allow nodes to sync blob data that is older than 18 days - after blobs are 18 days old, normal be
yay! thanks for catching this! 💟

2024-02-19 01:55 UTC, cpengilly commented on pages/builders/chain-operators/management/configuration.mdx
> +| `OP_BATCHER_MAX_CHANNEL_DURATION` | L2 Number of L1 Blocks | The max time (in L1 blocks, which are 12 seconds each) between which batches will be submitted to the L1. | 1500 l1 blocks |
updated

2024-02-19 01:57 UTC, cpengilly commented on pages/builders/chain-operators/management/configuration.mdx
> +  To minimize costs, we recommend setting your  `OP_BATCHER_MAX_CHANNEL_DURATION` to target 5 hours, with a value of `1500` L1 blocks. When non-zero, this parameter is the max time (in L1 blocks, whi
@K-Ho this page likely needs updates based on 130kb

2024-02-19 02:00 UTC, cpengilly commented on pages/builders/node-operators/network-upgrades/ecotone.mdx
> +  The Ecotone testnet network upgrade for OP Goerli activated at **1707238800 Tue Feb 6 17:00:00 UTC 2024**. Ecotone Sepolia releases are published and will activate at Wed Feb 21 17:00:00 UTC 2024.
updated

2024-02-19 02:02 UTC, cpengilly commented on pages/builders/node-operators/network-upgrades/ecotone.mdx
> +*   [`op-node`](https://github.com/ethereum-optimism/optimism/releases/tag/v1.5.0)
ty!

2024-02-19 02:05 UTC, cpengilly commented on pages/builders/node-operators/network-upgrades/ecotone.mdx
> +*   For node operators of custom chains not included in the `superchain-registry`, the activation dates can be set in the `rollup.json` (set `ecotone_time`) or set the activation time via overrides (
callout added

2024-02-19 02:07 UTC, cpengilly commented on pages/builders/node-operators/network-upgrades/ecotone.mdx
> +*   **Option 1:**  Configure a `beacon-archiver`. There is a configurable `beacon-archiver` that will allow nodes to sync blob data that is older than 18 days - after blobs are 18 days old, normal be
fixed

2024-02-19 02:11 UTC, cpengilly commented on pages/builders/notices/ecotone-fee-changes.mdx
> +  Ecotone Sepolia releases are published and will activate at Wed Feb 21 17:00:00 UTC 2024. The Ecotone upgrade for OP Mainnet is not scheduled yet.
agreed @sbvegan going to hold off on this update, as I think we have to wait for the official vote to add comments like that too docs.

2024-02-19 02:13 UTC, cpengilly commented on pages/builders/notices/ecotone-fee-changes.mdx
> +*   [op-node, op-batcher, op-proposer v1.5.1](https://github.com/ethereum-optimism/optimism/releases/tag/v1.5.1)
updated

2024-02-19 02:23 UTC, cpengilly commented on pages/builders/notices/ecotone-fee-changes.mdx
> +2.  Configure the Ecotone Activation Date
yes, intentional but will look for way to clean this up

2024-02-19 02:23 UTC, cpengilly commented on pages/builders/notices/ecotone-fee-changes.mdx
> +2.  Configure the Ecotone Activation Date
looking for way to clean this up

2024-02-20 16:52 UTC, K-Ho approved these changes

2024-02-20 16:52 UTC, K-Ho commented on pages/builders/chain-operators/management/blobs.mdx
> +  If you are posting 60KB per 5 hours of data (assuming roughly 250 byte transactions, this would be \~1250 transactions per day), then you would want to double the above recommended scalar values:
```suggestion
  If you are posting 65KB per 5 hours of data (assuming roughly 250 byte transactions, this would be \~1250 transactions per day), then you would want to double the above recommended scalar values:
```

2024-02-20 18:27 UTC, K-Ho requested changes
https://docs.optimism.io/builders/node-operators/management/configuration#working-base-configuration-1 We will want to update this section as well

To the configuration, add
`--l1.beacon=<ethereum mainnet beacon node RPC url>`
And then add a section below, repeating our note:

> To set your `--l1.beacon` value, either run your own L1 beacon node like [Lighthouse](https://lighthouse-book.sigmaprime.io/run_a_node.html) or use a third-party beacon node RPC service, like [Quicknode](https://www.quicknode.com/docs/ethereum/eth-v1-beacon-genesis).

Below, I'd also duplicate the "Configure a blob archiver" section

2024-02-20 18:27 UTC, K-Ho commented on pages/builders/notices/ecotone-fee-changes.mdx
> +*   For OP Chains that have entries in the `superchain-registry`, the Ecotone activation date is part of the `op-node` and `op-geth` nodes. So, no action is needed for the sequencer after upgrading t
Every time we mention the superchain-registry, should add this link for them to see if their chain is listed: https://github.com/ethereum-optimism/superchain-registry/blob/main/superchain/configs/chainids.json

2024-02-20 18:27 UTC, K-Ho commented on pages/builders/node-operators/network-upgrades/ecotone.mdx
> +Running a `blob-archiver` is lighter weight: [https://github.com/base-org/blob-archiver](https://github.com/base-org/blob-archiver). There is a configurable `beacon-archiver` that will allow nodes to
```suggestion
Running a `blob-archiver` is lighter weight than running a beacon node that does not prune blobs: [https://github.com/base-org/blob-archiver](https://github.com/base-org/blob-archiver). There is a configurable `beacon-archiver` that will allow nodes to sync blob data that is older than 18 days - after blobs are 18 days old, normal beacon nodes will  "prune" or remove them. If your node is already in sync with the head of the chain, you won't need to use a `beacon-archiver`.
```

2024-02-20 18:27 UTC, K-Ho commented on pages/builders/chain-operators/management/blobs.mdx
> +  l1BaseFeeScalar = 7600
```suggestion
  l1BaseFeeScalar = 11000
```

2024-02-20 18:27 UTC, K-Ho commented on pages/builders/chain-operators/management/blobs.mdx
> +  l1BlobBaseFeeScalar = 862000
```suggestion
  l1BlobBaseFeeScalar = 1087000
```

2024-02-20 18:27 UTC, K-Ho commented on pages/builders/chain-operators/management/blobs.mdx
> +  baseFeeScalar = 15200 = 7600 * 2
```suggestion
  baseFeeScalar = 22000 = 11000 * 2
```

2024-02-20 18:27 UTC, K-Ho commented on pages/builders/chain-operators/management/blobs.mdx
> +  blobBaseFeeScalar = 1724000 = 862000 * 2
```suggestion
  blobBaseFeeScalar = 2174000 = 1087000 * 2
```

2024-02-20 18:27 UTC, K-Ho commented on pages/builders/chain-operators/management/blobs.mdx
> +  <Callout type="warning">
I'd pull this out of the callout, its a core part of the info

2024-02-20 18:27 UTC, K-Ho commented on pages/builders/chain-operators/management/blobs.mdx
> +  *   Ensure your `OP_BATCHER_MAX_CHANNEL_DURATION` is properly set to maximize savings. **NOTE:** While setting a high value here will lower costs, it will be less meaningful than for low throughput
There's a TODO here, you should link to the section in chain operator configuration that discusses how to set "OP_BATCHER_MAX_CHANNEL_DURATION"

2024-02-20 21:12 UTC, cpengilly commented on pages/builders/notices/ecotone-fee-changes.mdx
> +*   For OP Chains that have entries in the `superchain-registry`, the Ecotone activation date is part of the `op-node` and `op-geth` nodes. So, no action is needed for the sequencer after upgrading t
Done

2024-02-20 21:13 UTC, cpengilly commented
> https://docs.optimism.io/builders/node-operators/management/configuration#working-base-configuration-1 We will want to update this section as well
> 
> To the configuration, add `--l1.beacon=<ethereum mainnet beacon node RPC url>` And then add a section below, repeating our note:
> 
> > To set your `--l1.beacon` value, either run your own L1 beacon node like [Lighthouse](https://lighthouse-book.sigmaprime.io/run_a_node.html) or use a third-party beacon node RPC service, like [Quicknode](https://www.quicknode.com/docs/ethereum/eth-v1-beacon-genesis).
> 
> Below, I'd also duplicate the "Configure a blob archiver" section

created a new issue here to track this change

2024-02-20 21:24 UTC, cpengilly commented on pages/builders/chain-operators/management/configuration.mdx
> +  To minimize costs, we recommend setting your  `OP_BATCHER_MAX_CHANNEL_DURATION` to target 5 hours, with a value of `1500` L1 blocks. When non-zero, this parameter is the max time (in L1 blocks, whi
addressed!

2024-02-20 21:49 UTC, K-Ho approved these changes

2024-02-20 21:56 UTC, merged