added 2 new snap sync pages
ethereum-optimism/docs pull request #525
Opened 2024-02-29 23:49 UTC by cpengilly

- node op snap sync page
- chain op snap sync page (needs work)

2024-03-01 20:26 UTC, trianglesphere commented on pages/builders/chain-operators/management/snap-sync.mdx
> +Need brief description of what snap sync is + why its important for chain operators.
Snap sync enables users to more quickly sync their nodes & is a mechanism for node operators to sync chains that are using blobs without a blob archiver.

2024-03-01 20:26 UTC, trianglesphere commented on pages/builders/chain-operators/management/snap-sync.mdx
> +This is for the run book for chain operators
Chain operators need to spin up a node which is exposed to the network & has tx gossip disabled.

2024-03-01 20:26 UTC, trianglesphere commented on pages/builders/node-operators/management/snap-sync.mdx
> +*   For OP Mainnet users, this is a significant upgrade because users will be able to sync without having to download the [bedrock datadir](snapshots).
Nit: this copy feels a bit weird. I don't think referencing users makes sense in the docs. Maybe "you". I'm not sure our style guide here though.

2024-03-01 20:26 UTC, trianglesphere commented on pages/builders/node-operators/management/snap-sync.mdx
> +  For snap sync, all `op-geth` nodes should be ran with public IP addresses to easily find other op-geth nodes to sync from.
hmm, instead of public IP here we should say with the discovery port exposed. The public IP part should be moved over to the chain operator section as they are more likely to run a node in the cloud where public IPs are not handed out by default.

2024-03-01 20:26 UTC, trianglesphere commented on pages/builders/node-operators/tutorials/testnet.mdx
> +The genesis file is **not required** for nodes using [snap sync](/builders/node-operators/management/snap-sync), so modified instructions are provided at that step.
hmm, in this case it may be required if it's not a named network

2024-03-01 20:26 UTC, trianglesphere commented on pages/builders/node-operators/tutorials/testnet.mdx
> +*   For all other nodes: download the genesis file from the OP Sepolia networks page
For OP Sepolia, no node ever needs the genesis file, they can just use the `--op-network=op-sepolia` flag

2024-03-02 00:51 UTC, cpengilly commented on pages/builders/node-operators/management/snap-sync.mdx
> +*   For OP Mainnet users, this is a significant upgrade because users will be able to sync without having to download the [bedrock datadir](snapshots).
fixed

2024-03-02 00:52 UTC, cpengilly commented on pages/builders/node-operators/management/snap-sync.mdx
> +  For snap sync, all `op-geth` nodes should be ran with public IP addresses to easily find other op-geth nodes to sync from.
done!

2024-03-02 00:57 UTC, cpengilly commented on pages/builders/node-operators/tutorials/testnet.mdx
> +The genesis file is **not required** for nodes using [snap sync](/builders/node-operators/management/snap-sync), so modified instructions are provided at that step.
tried to address this in the callout and the related step

2024-03-02 00:59 UTC, cpengilly commented on pages/builders/node-operators/tutorials/testnet.mdx
> +*   For all other nodes: download the genesis file from the OP Sepolia networks page
fixed

2024-03-04 18:59 UTC, sbvegan requested changes
https://docs.optimism.io/builders/node-operators/management/configuration#configuration 

these points removed:

> - --syncmode=full: This prevents Geth from attempting to snap sync. Snap sync is currently unsupported, but will be enabled shortly after the mainnet upgrade.
- --maxpeers=0: This prevents Geth from peering with other Geth nodes. Execution-layer peering is currently unsupported, but will be added as part of enabling snap sync.
- --nodiscover: This disables Geth's peer discovery mechanism. Execution-layer discovery is currently unsupported, but will be added as part of enabling snap sync.

https://docs.optimism.io/builders/node-operators/management/configuration#working-base-configuration

remove `--nodiscover` from the working base config

2024-03-04 18:59 UTC, sbvegan commented on pages/builders/chain-operators/management/snap-sync.mdx
> +
I think this page would benefit from the same copy in the node section:

> This guide reviews the optional feature of Snap Sync for node operators, including benefits and how to enable the feature.

> Snap Sync significantly improves the experience of syncing an OP Stack node. Snap Sync is a native feature of go-ethereum that is now optionally enabled on op-node & op-geth. Snap Sync works by downloading a snapshot of the state from other nodes on the network and is then able to start executing blocks from the completed state rather than having to re-execute every single block. This means that performing a Snap Sync is significantly faster than performing a full sync.

2024-03-04 18:59 UTC, sbvegan commented on pages/builders/chain-operators/management/snap-sync.mdx
> +Snap sync enables developers to more quickly sync their nodes and is a mechanism for node operators to sync chains that are using blobs without a blob archiver.
Suggestion, turn this into a bulleted list:
- Snap sync enables node operators on your network to sync faster.
- It removes the need for nodes on your post Ecotone network to run a [blob archiver](/builders/node-operators/management/blobs)

2024-03-04 18:59 UTC, sbvegan commented on pages/builders/chain-operators/management/snap-sync.mdx
> +
I think this section could use the nextra steps component with two steps:
1. Setup snap sync node in your infrastructure
2. Tell your network they can use snap sync

2024-03-04 18:59 UTC, sbvegan commented on pages/builders/chain-operators/management/snap-sync.mdx
> +To enable snap sync, chain operators need to spin up a node which is exposed to the network and has transaction gossip disabled.
This would be step 1: setup a snap sync node
Sub steps:
- Expose `op-geth` discovery port to the internet, need to figure out the default port and if there's any conflict with `geth`
- Disable transaction gossip with: /builders/node-operators/management/configuration#rollupdisabletxpoolgossip

2024-03-04 18:59 UTC, sbvegan commented on pages/builders/chain-operators/management/snap-sync.mdx
> +
Step 2: inform node operators on your network they can utilize snap sync
Sub steps:
- point to the node operator section for snap sync

2024-03-04 18:59 UTC, sbvegan commented on pages/builders/node-operators/management/snap-sync.mdx
> +  For snap sync, all `op-geth` nodes should be ran with the discovery port exposed to easily find other op-geth nodes to sync from.
We should add the default discovery port config here: https://deploy-preview-525--docs-optimism.netlify.app/builders/node-operators/management/configuration#discoveryport

2024-03-04 18:59 UTC, sbvegan commented on pages/builders/chain-operators/management/snap-sync.mdx
> +To enable snap sync, chain operators need to spin up a node which is exposed to the network and has transaction gossip disabled.
/builders/node-operators/management/configuration#discoveryport

2024-03-04 21:46 UTC, cpengilly commented on pages/builders/chain-operators/management/snap-sync.mdx
> +
done

2024-03-04 21:52 UTC, cpengilly commented on pages/builders/chain-operators/management/snap-sync.mdx
> +
thx for this but def need more context here -- i.e., how exactly does a chain operator complete these steps? where/how do they make the configuration changes?

2024-03-04 21:59 UTC, cpengilly commented on pages/builders/chain-operators/management/snap-sync.mdx
> +To enable snap sync, chain operators need to spin up a node which is exposed to the network and has transaction gossip disabled.
got it! thank you! 😄

2024-03-04 22:03 UTC, cpengilly commented on pages/builders/chain-operators/management/snap-sync.mdx
> +
done

2024-03-04 22:05 UTC, cpengilly commented on pages/builders/node-operators/management/snap-sync.mdx
> +  For snap sync, all `op-geth` nodes should be ran with the discovery port exposed to easily find other op-geth nodes to sync from.
done

2024-03-04 22:50 UTC, sbvegan requested changes

2024-03-04 22:50 UTC, sbvegan commented on pages/builders/chain-operators/management/snap-sync.mdx
> +  For snap sync, all `op-geth` nodes should be ran with the [`--discovery.port=30303`](/builders/node-operators/management/configuration#discoveryport) exposed to easily find other op-geth nodes to s
I think we can remove `30303`, @trianglesphere will snap sync work on different ports?

2024-03-04 22:50 UTC, sbvegan commented on pages/builders/chain-operators/management/snap-sync.mdx
> +  *   Expose op-geth [discovery port](/builders/node-operators/management/configuration#discoveryport) to the internet and figure out the default port and if there's any conflict with `op-geth`
Update here to the following:

Expose op-geth [--discovery.port](/builders/node-operators/management/configuration#discoveryport) to the internet.

2024-03-04 22:50 UTC, sbvegan commented on pages/builders/node-operators/management/snap-sync.mdx
> +  For snap sync, all `op-geth` nodes should be ran with the [`--discovery.port=30303`](/builders/node-operators/management/configuration#discoveryport) exposed to easily find other op-geth nodes to s
same question here @trianglesphere, does the port need to be 30303

2024-03-04 22:57 UTC, cpengilly commented on pages/builders/node-operators/management/snap-sync.mdx
> +  For snap sync, all `op-geth` nodes should be ran with the [`--discovery.port=30303`](/builders/node-operators/management/configuration#discoveryport) exposed to easily find other op-geth nodes to s
removed port from all the pages, just easier maintenance in docs too (across these pages)

2024-03-04 23:16 UTC, sbvegan approved these changes
pre-approved, pending Josh's review

2024-03-04 23:46 UTC, trianglesphere submitted a review, later dismissed
There's a couple place where info around flags is incorrect; however, more importantly, I think we should be distributed the snap sync / full node changes throughout the various node operator guides & make them the default.

2024-03-04 23:46 UTC, trianglesphere commented on pages/builders/chain-operators/management/snap-sync.mdx
> +  For snap sync, all `op-geth` nodes should be ran with the [`--discovery.port`](/builders/node-operators/management/configuration#discoveryport) exposed to easily find other op-geth nodes to sync fr
This callout is a little misleading. We should be instructing people to expose port 30303 TCP and 30303 UDP. If they set the port with `--disovery.port` they need to open the port they specified for UDP. If they set `--port`, they need to open up the port that the specified for TCP.

2024-03-04 23:46 UTC, trianglesphere commented on pages/builders/node-operators/management/snap-sync.mdx
> +  For snap sync, all `op-geth` nodes should be ran with the [`--discovery.port`](/builders/node-operators/management/configuration#discoveryport) exposed to easily find other op-geth nodes to sync fr
Ditto this flag isn't right. The default value is perfectly fine for 99% of people.

2024-03-04 23:46 UTC, trianglesphere commented on pages/builders/node-operators/tutorials/testnet.mdx
> +The genesis file **may not be required** for nodes using [snap sync](/builders/node-operators/management/snap-sync) and other specific use cases, so modified instructions are provided at that step.
The genesis file **is not** required for users that set `--op-network=op-sepolia` on op-geth.

See https://github.com/ethereum-optimism/docs/pull/531 for my suggestions on this file. I think it we can cut a lot from this tutorial.

2024-03-04 23:46 UTC, trianglesphere commented on pages/builders/node-operators/tutorials/mainnet.mdx
> +</Callout>
I think we should feature snap sync + the difference between full nodes & archive nodes much more prominently here.

My sample diff: https://github.com/ethereum-optimism/docs/pull/532

2024-03-05 01:12 UTC, cpengilly commented on pages/builders/node-operators/tutorials/testnet.mdx
> +The genesis file **may not be required** for nodes using [snap sync](/builders/node-operators/management/snap-sync) and other specific use cases, so modified instructions are provided at that step.
this page updated per #531

2024-03-05 01:41 UTC, cpengilly commented on pages/builders/node-operators/tutorials/mainnet.mdx
> +</Callout>
page updated per #532

2024-03-05 02:00 UTC, cpengilly commented on pages/builders/chain-operators/management/snap-sync.mdx
> +  For snap sync, all `op-geth` nodes should be ran with the [`--discovery.port`](/builders/node-operators/management/configuration#discoveryport) exposed to easily find other op-geth nodes to sync fr
updated

2024-03-05 19:27 UTC, trianglesphere reviewed
Need to also change the node configuration page to remove the anti-peering flags

2024-03-05 19:27 UTC, trianglesphere commented on pages/builders/chain-operators/management/snap-sync.mdx
> +<Callout type="warning">
```suggestion
<Callout type="info">
```

2024-03-05 19:27 UTC, trianglesphere commented on pages/builders/chain-operators/management/snap-sync.mdx
> +  *   Expose op-geth [`--discovery.port`](/builders/node-operators/management/configuration#discoveryport) to the internet and figure out the default port and if there's any conflict with `op-geth`
```suggestion
  *   Expose port `30303` (`op-geth`'s default discovery port) to the internet on TCP and UDP.
```

2024-03-05 19:27 UTC, trianglesphere commented on pages/builders/node-operators/management/configuration.mdx
>    --op-network=op-mainnet
```suggestion
  --op-network=op-mainnet
```

2024-03-05 19:27 UTC, trianglesphere commented on pages/builders/node-operators/tutorials/mainnet.mdx
> +*   For archive nodes, set `syncmode=full` and `gcmode=archive`.
```suggestion
*   Set `--syncmode=execution-layer` on `op-node` if you don't set `--syncmode=full` here on op-geth.
*   For archive nodes, set `--syncmode=full` and `--gcmode=archive` on `op-geth`
```

2024-03-05 19:27 UTC, trianglesphere commented on pages/builders/node-operators/tutorials/mainnet.mdx
> +{<h3>Initialize op-geth with the datadir </h3>}
TODO @sbvegan did we have these steps somewhere? Maybe we should cut this step as it's basically just extracting datadir into the folder.

2024-03-05 19:27 UTC, trianglesphere commented on pages/builders/node-operators/tutorials/testnet.mdx
> +<Callout type="warning">
```suggestion
<Callout type="info"> 
```

2024-03-05 19:27 UTC, trianglesphere commented on pages/builders/node-operators/tutorials/testnet.mdx
> +*   For archive nodes, set `syncmode=full` and `gcmode=archive`.
```suggestion
*   Set `--syncmode=execution-layer` on `op-node` if you don't set `--syncmode=full` here on op-geth.
*   For archive nodes, set `--syncmode=full` and `--gcmode=archive` on `op-geth`. 
```

2024-03-05 19:27 UTC, trianglesphere commented on pages/builders/node-operators/tutorials/testnet.mdx
> +Sync mode should be set to `syncmode=EL`.
```suggestion
Sync mode should be set to `--syncmode=execution-layer`.
```

2024-03-05 19:27 UTC, trianglesphere commented on pages/builders/node-operators/tutorials/mainnet.mdx
>    --authrpc.jwtsecret=./jwt.txt \
The datadir path comment `export DATADIR_PATH=... # Path to the migrated data directory` should probably read `export DATADIR_PATH=... # Path to the desired data directory for op-geth`

2024-03-05 19:28 UTC, trianglesphere commented on pages/builders/node-operators/tutorials/mainnet.mdx
> +
Let's add a callout here that you only need an archive node if you need historical state & users should default to full nodes.

2024-03-05 20:03 UTC, cpengilly commented on pages/builders/node-operators/tutorials/mainnet.mdx
>    --authrpc.jwtsecret=./jwt.txt \
updated

2024-03-05 20:05 UTC, cpengilly commented on pages/builders/node-operators/tutorials/mainnet.mdx
> +
added!

2024-03-05 22:30 UTC, sbvegan commented on pages/builders/node-operators/tutorials/mainnet.mdx
> +{<h3>Initialize op-geth with the datadir </h3>}
Yeah we can get rid of this step. Its here on the configuration page: https://docs.optimism.io/builders/node-operators/management/configuration#initialization-via-genesis-file

This initialization is just for networks other than op mainnet (non migrated networks)

2024-03-05 22:33 UTC, cpengilly commented on pages/builders/node-operators/tutorials/mainnet.mdx
> +{<h3>Initialize op-geth with the datadir </h3>}
step removed! are we good to publish now?

2024-03-05 22:36 UTC, trianglesphere commented on pages/builders/node-operators/tutorials/mainnet.mdx
> +{<h3>Configure op-geth differently </h3>}
```suggestion
{<h3>Configure op-geth for archive mode</h3>}
```

2024-03-05 22:36 UTC, trianglesphere commented on pages/builders/node-operators/tutorials/testnet.mdx
>    --http \
Need to remove `  --nodiscover \
  --syncmode=full \
  --maxpeers=0 \` from this

2024-03-05 22:43 UTC, cpengilly commented on pages/builders/node-operators/tutorials/testnet.mdx
>    --http \
done

2024-03-05 22:57 UTC, merged