adding fee scalar calculator
ethereum-optimism/docs pull request #529
Opened 2024-03-04 17:58 UTC by sbvegan

**Description**

Adding fee scalar calculator links, so chains can better estimate scalars for the data throughput on their chains.

**Tests**

Please describe any tests you've added. If you've added no tests, or left important behavior untested, please explain why not.

**Additional context**

Add any other context about the problem you're solving.

**Metadata**

- Fixes https://github.com/ethereum-optimism/docs/issues/527

2024-03-04 20:07 UTC, MSilb7 commented
https://github.com/ethereum-optimism/docs/blob/aeb376aed9e56f56ea59e4f75065e60e1e4e204b/pages/builders/chain-operators/management/blobs.mdx#L38

Default scalars weren't updated based on recent analyses. Still could be in flux if we want a default versus only direct people to the calculator (cc @K-Ho ) - This could be temporary, since we can eventually embed the equation(s) in docs.

Configured based on Base running 50k txs / day, rounded for readability.

**Lines 38 - 41:**
l1BaseFeeScalar = 1100
l1BlobBaseFeeScalar = 655000

We could reference these same numbers throughout for consistency:
**Lines 51 - 52:**
baseFeeScalar = 2200 = 1100 * 2
 blobBaseFeeScalar = 1310000 = 655000 * 2

**Lines 75-80**
./bin/ecotone-scalar --scalar=1100 --blob-scalar=655000

2024-03-04 20:08 UTC, MSilb7 commented
@K-Ho comment (paraphrased):
```
we want to completely remove the default recommendations
we just need to make sure its very clear this is just an example
```

Aligned on wording it like an example, but we could assume people may just rip these, so ideally the values are reasonable. We can take:
- l1BaseFeeScalar = 1100
- l1BlobBaseFeeScalar = 655000

As commented above: https://github.com/ethereum-optimism/docs/pull/529#issuecomment-1977367753

2024-03-05 16:29 UTC, K-Ho requested changes
almost there!

2024-03-05 16:29 UTC, K-Ho commented on pages/builders/chain-operators/management/blobs.mdx
> +<Callout type="warning">
Why do we need this callout? Feels like duplicate info

2024-03-05 16:29 UTC, K-Ho commented on pages/builders/chain-operators/management/blobs.mdx
> +  If your chain is submitting full blobs, rough *example* scalar values to set
I think it might be worth just getting rid of this and the values below it altogether. AFAIK no other chain is doing the same throughput as OP Mainnet, so this won't be relevant for anyone

2024-03-05 16:29 UTC, K-Ho commented on pages/builders/chain-operators/management/blobs.mdx
> +back to posting data to calldata. Chains can follow these steps to switch from
```suggestion
back to posting data to calldata. Utilize the [fee parameter calculator](https://docs.google.com/spreadsheets/d/12VIiXHaVECG2RUunDSVJpn67IQp9NHFJqUsma2PndpE/edit) to inform whether your transactions will be cheaper if submitting blobs or if submitting calldata. Chains can follow these steps to switch from 
```

2024-03-05 16:29 UTC, K-Ho commented on pages/builders/chain-operators/management/blobs.mdx
>    To target a 5% margin on your L1 Fees, we would recommend:
Remove recommendation here

2024-03-05 16:29 UTC, K-Ho commented on pages/builders/chain-operators/management/blobs.mdx
>    To target a 5% margin on your L1 Fees, we would recommend:
or phrase it as: "When using the fee parameter calculator, an example set of values you might get for using calldata are:



 "

2024-03-05 16:29 UTC, K-Ho commented on pages/builders/chain-operators/management/blobs.mdx
> +**The values in the following steps have example values.** You should utilize this
remove, this is duplicate info

2024-03-05 16:29 UTC, K-Ho commented on pages/builders/chain-operators/management/blobs.mdx
> +  to get a better estimate for scalar values on your chain. The following
```suggestion
  to get a better estimate for scalar values on your chain. Input the average transaction per day your chain is processing, the types of transactions that occur on your chain, the [`OP_BATCHER_MAX_CHANNEL_DURATION` ](https://docs.optimism.io/builders/chain-operators/management/configuration#setting-your--op_batcher_max_channel_duration) you have parameterized on your `op-batcher`, and the target margin you wish to charge users on top of your L1 costs. The following
```

2024-03-05 16:29 UTC, K-Ho commented on pages/builders/chain-operators/management/blobs.mdx
> +  to get a better estimate for scalar values on your chain. The following
Remove "the following information is tuned to a network like OP Mainnet".

I'd add a note here, which is to tell them how to use the chain calculator: The scalar values we will use in the next step can be seen in this example in the "Chain input" column - 
<img width="1060" alt="Screenshot 2024-03-05 at 10 26 44 AM" src="https://github.com/ethereum-optimism/docs/assets/5341583/b51f0b29-60ce-4164-9c3e-1338af5a46b6">

2024-03-05 17:28 UTC, sbvegan commented on pages/builders/chain-operators/management/blobs.mdx
> +<Callout type="warning">
removed, initial idea was to be repetitive so people didn't use the example

2024-03-05 17:39 UTC, sbvegan commented on pages/builders/chain-operators/management/blobs.mdx
> +**The values in the following steps have example values.** You should utilize this
removed

2024-03-05 20:03 UTC, K-Ho approved these changes

2024-03-05 21:08 UTC, merged