2 new node pages
ethereum-optimism/docs pull request #679
Opened 2024-05-09 16:55 UTC by cpengilly

part 1 of node revision:
- new base config page
- new node architecture page

 part 2 will be rewrite of overview page to follow new funnel @sbvegan for review

2024-05-13 21:11 UTC, trianglesphere commented on pages/builders/node-operators/configuration/base-config.mdx
> +### Initialization via Genesis File (OP Sepolia nodes)
We should probably use a different example and OP Sepolia. Like OP Sepolia can be configured by a genesis file, but it can also be configured via the network flag and most people would be better off using the network flag.

2024-05-14 18:41 UTC, cpengilly commented on pages/builders/node-operators/configuration/base-config.mdx
> +### Initialization via Genesis File (OP Sepolia nodes)
fixed

2024-05-14 21:22 UTC, sbvegan requested changes

2024-05-14 21:22 UTC, sbvegan commented on pages/builders/chain-operators/management/operations.mdx
> +*   See the [Node Configuration](/builders/node-operators/configuration/base-config#configuration) guide for additional explanation or customization.
We can probably remove the header link (#configuration)

2024-05-14 21:22 UTC, sbvegan commented on pages/builders/node-operators/architecture.mdx
> +This page reviews node architecture for all nodes running on the Superchain network. All OP Mainnet nodes are composed of two core software services, the Rollup Node and the Execution Client.
Meta note: I think we refer to the op-node as the rollup node and consensus client interchangeably in the docs. I think thats mostly fine, but might be worth choosing one term.

2024-05-14 21:22 UTC, sbvegan commented on pages/builders/node-operators/configuration/_meta.json
> +    "geth-config": "op-geth Config Options"
Personal preference: 
```
"op-node-config": "Consensus Layer",
"op-geth-config": "Execution Layer"
```

2024-05-14 21:22 UTC, sbvegan commented on pages/builders/node-operators/configuration/base-config.mdx
> +3.  **With network flags:** This initializes the genesis information and chain configuration from the [superchain-registry](https://github.com/ethereum-optimism/superchain-registry).
Lets reorganize this to be number 1, its the most common way

2024-05-14 21:22 UTC, sbvegan commented on pages/builders/node-operators/configuration/base-config.mdx
> +#### Initialization via Network Flags
similarly, lets bump this to appear first

2024-05-14 21:22 UTC, sbvegan commented on pages/builders/node-operators/configuration/base-config.mdx
> +*   See the [op-node configuration](/builders/node-operators/configuration/node-config) guide for additional configuration options for `op-node` and the Consensus-Layer.
If you change the submenu meta.json, these will need to be updated

2024-05-14 21:22 UTC, sbvegan commented on pages/builders/node-operators/configuration/node-config.mdx
> +# Additional Configuration for `op-node` (Consensus-Layer)
Imo this reads better as Consensus Layer Configuration Options (`op-node`)

2024-05-14 21:22 UTC, sbvegan commented on pages/builders/node-operators/configuration/node-config.mdx
> +This page list additional configuration options for `op-node`. `op-node` implements most rollup-specific functionality as Consensus-Layer, similar to a L1 beacon-node.
It lists all options

2024-05-14 21:22 UTC, sbvegan commented on pages/builders/node-operators/configuration/node-config.mdx
> +The following options are from the `--help` in [v1.5.1](https://github.com/ethereum-optimism/optimism/releases/tag/v1.5.1).
Meta note, need to update these options for v1.7.5

2024-05-14 21:22 UTC, sbvegan commented on pages/builders/node-operators/overview.mdx
>  ## Software Releases
Lets remove the twitter callout because software releases don't go through that account. Also adding the discord announcement channel

2024-05-14 21:22 UTC, sbvegan commented on pages/builders/node-operators/configuration/geth-config.mdx
> +title: Additional Configuration for op-geth
Imo this reads better as Execution Layer Configuration Options (op-geth)

2024-05-15 17:07 UTC, cpengilly commented on pages/builders/chain-operators/management/operations.mdx
> +*   See the [Node Configuration](/builders/node-operators/configuration/base-config#configuration) guide for additional explanation or customization.
done

2024-05-15 17:19 UTC, cpengilly commented on pages/builders/node-operators/configuration/node-config.mdx
> +# Additional Configuration for `op-node` (Consensus-Layer)
changed!

2024-05-15 17:20 UTC, cpengilly commented on pages/builders/node-operators/configuration/_meta.json
> +    "geth-config": "op-geth Config Options"
changed to `consensus-config` and `execution-config` to more closely match page titles and help with developer education (they are building on the consensus layer and execution layers, respectively) 💟

2024-05-15 17:21 UTC, cpengilly commented on pages/builders/node-operators/configuration/node-config.mdx
> +This page list additional configuration options for `op-node`. `op-node` implements most rollup-specific functionality as Consensus-Layer, similar to a L1 beacon-node.
fixed

2024-05-15 17:24 UTC, cpengilly commented on pages/builders/node-operators/configuration/node-config.mdx
> +The following options are from the `--help` in [v1.5.1](https://github.com/ethereum-optimism/optimism/releases/tag/v1.5.1).
fixed

2024-05-15 17:37 UTC, cpengilly commented on pages/builders/node-operators/overview.mdx
>  ## Software Releases
going to update in the final version of this doc (other PR)

2024-05-15 17:37 UTC, cpengilly commented on pages/builders/node-operators/configuration/geth-config.mdx
> +title: Additional Configuration for op-geth
fixed

2024-05-15 18:32 UTC, cpengilly commented on pages/builders/node-operators/configuration/base-config.mdx
> +#### Initialization via Network Flags
yep, done!

2024-05-15 18:32 UTC, cpengilly commented on pages/builders/node-operators/configuration/base-config.mdx
> +3.  **With network flags:** This initializes the genesis information and chain configuration from the [superchain-registry](https://github.com/ethereum-optimism/superchain-registry).
done

2024-05-15 19:10 UTC, sbvegan approved these changes

2024-05-15 19:39 UTC, merged