how to run a node on superchain network
ethereum-optimism/docs pull request #690
Opened 2024-05-14 16:58 UTC by cpengilly

draft page

2024-05-14 21:51 UTC, sbvegan requested changes

2024-05-14 21:51 UTC, sbvegan commented on pages/builders/node-operators/_meta.json
> +  "superchain-node": "Run a Node within the Superchain",
Nit: I think this might work fine to stay as, "Overview" and just update the title within the actual page.

2024-05-14 21:51 UTC, sbvegan commented on pages/builders/node-operators/superchain-node.mdx
> +---
similar to my comment above, the file name being `superchain-node` could be confusing

2024-05-14 21:51 UTC, sbvegan commented on pages/builders/node-operators/superchain-node.mdx
> +# How to Run a Node Within the Superchain
Nit: Maybe, "Running a Node in the Superchain"? Idk what it is, but the title here just doesn't flow for me. Acknowledging this was my suggestion 😅

2024-05-14 21:51 UTC, sbvegan commented on pages/builders/node-operators/superchain-node.mdx
> +  *   **Node Architecture**: OP Stack rollup nodes use the rollup node and execution client and can also support legacy geth. For more details, see the [Node Architecture](/builders/node-operators/ar
**Node Architecture**: OP Stack rollup nodes use the rollup node and execution client and can also support legacy geth for pre-bedrock historical execution requests.

2024-05-14 21:51 UTC, sbvegan commented on pages/builders/node-operators/superchain-node.mdx
> +  *   **Network Upgrades**: Network upgrades for OP Stack Rollup nodes are [activated by timestamps](/builders/node-operators/network-upgrades#activations). Failing to upgrade your node before the ti
Network upgrades for OP Stack Rollup nodes are _generally_ activated by timestamps.

while this is how we've done it in the past, its not necessarily the only way it could be done. A bit of nuance that probably doesn't need to be specified, but just calling it out.

2024-05-14 21:51 UTC, sbvegan commented on pages/builders/node-operators/superchain-node.mdx
> +  *   **Option 1:** Follow the [Running a Node with Docker](/builders/node-operators/tutorials/node-from-docker) tutorial, which walks you through the complete process of **building** and **running**
Follow the [Running a Node with Docker](/builders/node-operators/tutorials/node-from-docker) tutorial, which gets your OP Stack rollup node up and running without having to build it from source.

2024-05-14 21:51 UTC, sbvegan commented on pages/builders/node-operators/superchain-node.mdx
> +  *   Configure `op-geth` using the [base configuration](/builders/node-operators/configuration/base-config#working-base-configuration).
dependent on other PR

2024-05-14 21:51 UTC, sbvegan commented on pages/builders/node-operators/superchain-node.mdx
> +  {<h3>Enable Snap Sync</h3>}
Lets mark this as optional

2024-05-14 21:51 UTC, sbvegan commented on pages/builders/node-operators/superchain-node.mdx
> +  The following steps are intended for `op-geth` instead of `op-node`, so it must be tweaked to work for rollup nodes running within the Superchain.
The following steps are intended for `go-ethereum`, so it must be tweaked to work for rollup nodes running within the Superchain.

2024-05-14 21:51 UTC, sbvegan commented on pages/builders/node-operators/superchain-node.mdx
> +  *   Setup [influxdb](https://geth.ethereum.org/docs/monitoring/dashboards#setting-up-influxdb) to monitor geth.
to hold metric data

2024-05-14 21:51 UTC, sbvegan commented on pages/builders/node-operators/superchain-node.mdx
> +  *   Setup [prometheus](https://geth.ethereum.org/docs/monitoring/dashboards#setting-up-prometheus) to read your endpoint.
nit: to scrape your endpoint. Read your endpoint is correct, but I've just heard people say scrape the endpoint more often.

2024-05-14 21:51 UTC, sbvegan commented on pages/builders/node-operators/superchain-node.mdx
> +*   Notifications about important updates are also posted to the [**@Optimism Twitter account**](https://twitter.com/optimism), and to the [**Node & Protocol Announcements Channel on Telegram**](http
remove twitter account and add discord

2024-05-15 22:44 UTC, cpengilly commented on pages/builders/node-operators/_meta.json
> +  "superchain-node": "Run a Node within the Superchain",
already changed the page stub lol, but  from SEO perspective it's better if they closely match

2024-05-15 22:45 UTC, cpengilly commented on pages/builders/node-operators/superchain-node.mdx
> +---
i'll find another page stub name that works 😃

2024-05-15 22:55 UTC, cpengilly commented on pages/builders/node-operators/superchain-node.mdx
> +  *   **Node Architecture**: OP Stack rollup nodes use the rollup node and execution client and can also support legacy geth. For more details, see the [Node Architecture](/builders/node-operators/ar
updated!

2024-05-15 22:55 UTC, cpengilly commented on pages/builders/node-operators/superchain-node.mdx
> +  *   **Network Upgrades**: Network upgrades for OP Stack Rollup nodes are [activated by timestamps](/builders/node-operators/network-upgrades#activations). Failing to upgrade your node before the ti
gotcha. went ahead and updated anyhow 👍🏾

2024-05-15 23:06 UTC, cpengilly commented on pages/builders/node-operators/superchain-node.mdx
> +  *   Setup [prometheus](https://geth.ethereum.org/docs/monitoring/dashboards#setting-up-prometheus) to read your endpoint.
to optimize for a future with language translation, I'll leave it as `read` since it's more clear/universally understood

2024-05-15 23:06 UTC, cpengilly commented on pages/builders/node-operators/superchain-node.mdx
> +*   Notifications about important updates are also posted to the [**@Optimism Twitter account**](https://twitter.com/optimism), and to the [**Node & Protocol Announcements Channel on Telegram**](http
done!

2024-05-16 03:21 UTC, closed without merging