fjord-notice
ethereum-optimism/docs pull request #739
Opened 2024-06-12 21:26 UTC by cpengilly

new fjord notice page with updates to node upgrade page

2024-06-13 12:41 UTC, sebastianst requested changes

2024-06-13 12:41 UTC, sebastianst commented on pages/builders/node-operators/network-upgrades.mdx
> +Fjord upgrade includes RIP-7212, Brotli channel compression, FastLZ, and gas cost changes.
FastLZ _is_ the gas pricing change, so it could be misleading to list it separately. Instead, this sentence should mention that some protocol parameters got increased. Something like
```suggestion
The Fjord upgrade includes the RIP-7212 precompile, FastLZ gas pricing, Brotli channel compression, and several protocol parameter changes.
```

2024-06-13 12:41 UTC, sebastianst commented on pages/builders/node-operators/network-upgrades.mdx
> +*   [L1 gas cost changes](https://specs.optimism.io/fjord/predeploys.html#l1-gas-usage-estimation)
We should group them, currently related changes are separated
```suggestion
*   [RIP-7212: Precompile for secp256r1](https://specs.optimism.io/protocol/precompiles.html#P256VERIFY)
*   [Brotli channel compression](https://specs.optimism.io/fjord/exec-engine.html#fees)
*   FastLZ gas pricing
    *   [FastLZ L1 fee cost calculation](https://specs.optimism.io/fjord/exec-engine.html#fees)
    *   [Upgraded GasPriceOracle to compute FastLZ](https://specs.optimism.io/fjord/derivation.html#gaspriceoracle-deployment)
    *   [L1 gas cost changes](https://specs.optimism.io/fjord/predeploys.html#l1-gas-usage-estimation)
* Protocol parameter changes
    *   [Max sequencer drift becomes constant](https://specs.optimism.io/fjord/derivation.html#constant-maximum-sequencer-drift)
    *   [Channel constant increases](https://specs.optimism.io/fjord/derivation.html#increasing-max_rlp_bytes_per_channel-and-max_channel_bank_size)
*   [Fjord hardfork activation block](https://specs.optimism.io/fjord/derivation.html#network-upgrade-automation-transactions)
```

2024-06-13 12:41 UTC, sebastianst commented on pages/builders/notices/fjord-changes.mdx
> +    *   `L1GasUsed` field of the transaction receipt ([spec](https://specs.optimism.io/fjord/exec-engine.html)) is being deprecated
similarly, FastLZ and "L1 Gas Cost changes" shouldn't be separated, as they are the same overall change

2024-06-13 12:41 UTC, sebastianst commented on pages/builders/notices/fjord-changes.mdx
> +*   `getL1FeeUpperBound` is a new method to estimate fee upper bounds when sending transactions. It is much cheaper, in gas costs, than previous methods. This is what wallets and front-ends should pr
```suggestion
*   `getL1FeeUpperBound` is a new method to estimate fee upper bounds when sending transactions. It is much cheaper, in gas costs, than previous methods. This is what wallets and front-ends should use in practice in most cases.
```

2024-06-13 12:41 UTC, sebastianst commented on pages/builders/notices/fjord-changes.mdx
> +*   Alternatively, you might consider using `getL1FeeUpperBound` if you need to estimate the transaction fee and also need to compute the correct value to set when sending transactions.
```suggestion
*   Alternatively, you should consider using `getL1FeeUpperBound` if you only need to estimate an upper bound of the L1 fee for the purpose of transaction sending.
```

2024-06-13 12:41 UTC, sebastianst commented on pages/builders/notices/fjord-changes.mdx
> +
We could add an item here saying that node operators (both sequencers and normal node operators) should confirm in the startup logs of their op-node and op-geth that the correct Fjord activation timestamps are set.

2024-06-13 12:41 UTC, sebastianst commented on pages/builders/notices/fjord-changes.mdx
> +  Prepare your batcher to be restarted with the updated configuration in advance of the Fjord activation. You will also need to activate Brotli compression for the batcher.
This sounds as if it's two separate things
```suggestion
  Prepare your batcher to activate Brotli compression. This step is optional but recommended to achieve better channel compression.
```

2024-06-13 12:41 UTC, sebastianst commented on pages/builders/notices/fjord-changes.mdx
> +  ```
I would move this as second item, because it's not a real step to take, but more of an information.

2024-06-13 12:41 UTC, sebastianst commented on pages/builders/notices/fjord-changes.mdx
> +  *   Activate Brotli compression for your batcher. `brotli-10` is the default and works fine for most chain configurations, but chain operators can experiment with `brotli-11` if it gives them bette
```suggestion
  *   You can activate Brotli compression for your batcher by setting the `compression-algo` flag. `brotli-10` is the recommended Brotli level and works fine for most chain configurations, but chain operators can experiment with `brotli-11` if it gives them better compression and their batcher can still keep up with the increased compression computation needs. `brotli` defaults to `brotli-10`. If the flag is unset, it still defaults to `zlib`.
```

2024-06-13 12:41 UTC, sebastianst commented on pages/builders/notices/fjord-changes.mdx
> +  *   [`op-node`](https://github.com/ethereum-optimism/optimism/releases/tag/op-node%2Fv1.7.7-rc.1)
I'll finalize releases later today, then we can set
```suggestion
  *   [`op-geth`](https://github.com/ethereum-optimism/op-geth/releases/tag/v1.101315.2)
  *   [`op-node`](https://github.com/ethereum-optimism/optimism/releases/tag/op-node%2Fv1.7.7)
```
which will also contain the mainnet activation times.

2024-06-13 16:33 UTC, cpengilly commented on pages/builders/notices/fjord-changes.mdx
> +    *   `L1GasUsed` field of the transaction receipt ([spec](https://specs.optimism.io/fjord/exec-engine.html)) is being deprecated
updated

2024-06-13 16:42 UTC, cpengilly commented on pages/builders/notices/fjord-changes.mdx
> +
callout added

2024-06-13 16:42 UTC, cpengilly commented on pages/builders/notices/fjord-changes.mdx
> +  ```
done

2024-06-14 20:05 UTC, sbvegan commented on pages/builders/notices/fjord-changes.mdx
> +  *   **Option 1:** In your  `rollup.json`  config file, set `L2GenesisFjordTimeOffset` to the UNIX timestamp of the block you want to activate the Fjord hardfork. You will still need to set the `ove
https://github.com/ethereum-optimism/optimism/blob/3aeb6bdd3efe798713098f890359513eaaa91522/op-chain-ops/genesis/config.go#L138-L140

2024-06-14 20:06 UTC, sbvegan commented on pages/builders/notices/fjord-changes.mdx
> +Node operators will need to upgrade to Fjord before the activation date. For Sepolia, the op-node release [v1.7.7-rc.1](https://github.com/ethereum-optimism/optimism/releases/tag/op-node%2Fv1.7.7-rc.
https://github.com/ethereum-optimism/optimism/releases/tag/v1.7.7

2024-06-14 20:06 UTC, sbvegan commented on pages/builders/notices/fjord-changes.mdx
> +Node operators will need to upgrade to Fjord before the activation date. For Sepolia, the op-node release [v1.7.7-rc.1](https://github.com/ethereum-optimism/optimism/releases/tag/op-node%2Fv1.7.7-rc.
https://github.com/ethereum-optimism/op-geth/releases/tag/v1.101315.2

2024-06-14 20:07 UTC, sbvegan commented on pages/builders/notices/fjord-changes.mdx
> +Node operators will need to upgrade to Fjord before the activation date. For Sepolia, the op-node release [v1.7.7-rc.1](https://github.com/ethereum-optimism/optimism/releases/tag/op-node%2Fv1.7.7-rc.
These release numbers in the description need to be updated. We need to remove the release candidate version and do the actual release too

2024-06-14 20:09 UTC, sbvegan commented on pages/builders/notices/fjord-changes.mdx
> +  *   **Option 1:** Set the time in the `rollup.json` (set `fjord_time`) for `op-node`. You will still need to set the `override.fjord` flag in `op-geth` if you use this option.
What is `fjord_time`? That is not a field in the rollup.json

2024-06-14 20:10 UTC, sbvegan commented on pages/stack/protocol/fault-proofs/mips.mdx
> -*   [MIPS Reference Sheet](https://inst.eecs.berkeley.edu/~cs61c/resources/MIPS_Green_Sheet.pdf)
Is this an intentional removal? Seems unrelated to fjord?

2024-06-14 20:58 UTC, cpengilly commented on pages/stack/protocol/fault-proofs/mips.mdx
> -*   [MIPS Reference Sheet](https://inst.eecs.berkeley.edu/~cs61c/resources/MIPS_Green_Sheet.pdf)
yes, it is a broken link (and not owned by us). I think we are good on ref materials since we're linking to the specs

2024-06-14 21:06 UTC, cpengilly commented on pages/builders/notices/fjord-changes.mdx
> +Node operators will need to upgrade to Fjord before the activation date. For Sepolia, the op-node release [v1.7.7-rc.1](https://github.com/ethereum-optimism/optimism/releases/tag/op-node%2Fv1.7.7-rc.
updated

2024-06-14 21:11 UTC, cpengilly commented on lychee.toml
> +accept = ["100..=103", "200..=299", "401..=401", "403..=403", "502..=502"]
fixed

2024-06-14 21:15 UTC, cpengilly commented on pages/builders/notices/fjord-changes.mdx
> +  *   **Option 1:** In your  `rollup.json`  config file, set `L2GenesisFjordTimeOffset` to the UNIX timestamp of the block you want to activate the Fjord hardfork. You will still need to set the `ove
oooh, I'm not sure @sebastianst @ZakAyesh for help

2024-06-14 21:15 UTC, cpengilly commented on pages/builders/notices/fjord-changes.mdx
> +  *   **Option 1:** Set the time in the `rollup.json` (set `fjord_time`) for `op-node`. You will still need to set the `override.fjord` flag in `op-geth` if you use this option.
@sebastianst @ZakAyesh for clarification

2024-06-14 21:36 UTC, cpengilly commented on pages/builders/notices/fjord-changes.mdx
> +  *   **Option 1:** Set the time in the `rollup.json` (set `fjord_time`) for `op-node`. You will still need to set the `override.fjord` flag in `op-geth` if you use this option.
fixed

2024-06-17 16:01 UTC, sebastianst commented on pages/builders/notices/fjord-changes.mdx
> +  *   **Option 1:** In your  `rollup.json`  config file, set `L2GenesisFjordTimeOffset` to the UNIX timestamp of the block you want to activate the Fjord hardfork. You will still need to set the `ove
there seems to be a mix up of deploy config (using relative offsets) and rollup configs (using absolute timestamps)

2024-06-17 16:12 UTC, cpengilly commented on pages/builders/notices/fjord-changes.mdx
> +  *   **Option 1:** In your  `rollup.json`  config file, set `L2GenesisFjordTimeOffset` to the UNIX timestamp of the block you want to activate the Fjord hardfork. You will still need to set the `ove
fixed

2024-06-17 16:39 UTC, sbvegan approved these changes

2024-06-17 16:40 UTC, merged