Address aliasing for l2 proxy admin owner
ethereum-optimism/docs pull request #751
Opened 2024-06-17 14:37 UTC by blmalone

**Description**

See: https://github.com/ethereum-optimism/specs/pull/240

2024-06-17 15:00 UTC, blmalone commented on pages/chain/security/privileged-roles.mdx
> +*   **Op Sepolia**: Aliased Sepolia L1 Proxy Admin owner address [`0x2FC3ffc903729a0f03966b917003800B145F67F3`](https://sepolia-optimism.etherscan.io/address/0x2FC3ffc903729a0f03966b917003800B145F67F
Yea I can see how it is confusing. I kept "Ethereum" and "Sepolia" as a way to show how it's aliased but maybe that's overkill.

2024-06-17 15:27 UTC, mds1 commented on pages/chain/security/privileged-roles.mdx
> +*   **Op Sepolia**: Aliased Sepolia L1 Proxy Admin owner address [`0x2FC3ffc903729a0f03966b917003800B145F67F3`](https://sepolia-optimism.etherscan.io/address/0x2FC3ffc903729a0f03966b917003800B145F67F
I'd be ok keeping them if we also qualify it with the role name, e.g. "Ethereum L1PAO is addressX, corresponding L2PAO is the aliased addressX which is addressX"

2024-06-18 22:17 UTC, blmalone commented on pages/chain/security/privileged-roles.mdx
> +*   **Op Sepolia**: Aliased Sepolia L1 Proxy Admin owner address [`0x2FC3ffc903729a0f03966b917003800B145F67F3`](https://sepolia-optimism.etherscan.io/address/0x2FC3ffc903729a0f03966b917003800B145F67F
Added your suggestion.

2024-06-21 15:18 UTC, sbvegan requested changes

2024-06-21 15:29 UTC, sbvegan approved these changes

2024-06-21 15:59 UTC, merged