superchainconfig guardian address change
ethereum-optimism/docs pull request #753
Opened 2024-06-17 20:13 UTC by cpengilly

Update privileged-roles.mdx

2024-06-17 22:40 UTC, ZakAyesh requested changes
Just need to double check the address change for the L2ProxyAdmin

2024-06-17 22:40 UTC, ZakAyesh commented on pages/chain/security/privileged-roles.mdx
> +*   **Ethereum**: [`0x6B1BAE59D09fCcbdDB6C6cceb07B7279367C4E3b`](https://optimistic.etherscan.io/address/0x6B1BAE59D09fCcbdDB6C6cceb07B7279367C4E3b)
Are we sure this is the correct address? I double checked the link in etherscan and the address appears to be empy

2024-06-18 08:47 UTC, geoknee commented on pages/chain/security/privileged-roles.mdx
> +The L2 Proxy Admin is an address that can be used to upgrade most OP Mainnet system contracts on L2. L2 Proxy Admin is the aliased address of the L1ProxyAdmin owner, which means the L2 ProxyAdmin Own
Two comments on this: 

1. This isn't scanning right to me, is this more accurate?
```suggestion
The L2 Proxy Admin is an address that can be used to upgrade most OP Mainnet system contracts on L2. The L2 Proxy Admin owner is the aliased address of the L1ProxyAdmin owner, which means the L2 ProxyAdmin Owner is equal to the L1 ProxyAdmin Owner, but due to aliasing it's a different address.
```

2. Do we have a link for "aliasing"? Does it mean the same address on a different chain? Suboptimal to just have this terminology without explanation IMO.

2024-06-18 09:47 UTC, geoknee commented on pages/chain/security/privileged-roles.mdx
> +The L2 Proxy Admin is an address that can be used to upgrade most OP Mainnet system contracts on L2. L2 Proxy Admin is the aliased address of the L1ProxyAdmin owner, which means the L2 ProxyAdmin Own
Maybe this link is appropriate? https://docs.optimism.io/chain/differences#address-aliasing 

I'm still pretty confused about 

> the L2 ProxyAdmin Owner is equal to the L1 ProxyAdmin Owner, but due to aliasing it's a different address.

The context is that I am writing validation checks in the superchain registry which will reference both the L1 ans L2 ProxyAdmin addresses, as well as their owners.

2024-06-18 17:58 UTC, cpengilly commented on pages/chain/security/privileged-roles.mdx
> +The L2 Proxy Admin is an address that can be used to upgrade most OP Mainnet system contracts on L2. L2 Proxy Admin is the aliased address of the L1ProxyAdmin owner, which means the L2 ProxyAdmin Own
@geoknee yep,thanks for the rewrite. I may not have captured the note correctly from @mds1 so pinging him here to weigh in

2024-06-18 17:59 UTC, cpengilly commented on pages/chain/security/privileged-roles.mdx
> +*   **Ethereum**: [`0x6B1BAE59D09fCcbdDB6C6cceb07B7279367C4E3b`](https://optimistic.etherscan.io/address/0x6B1BAE59D09fCcbdDB6C6cceb07B7279367C4E3b)
also double-checking that I have the correct address

2024-06-18 18:40 UTC, mds1 commented on pages/chain/security/privileged-roles.mdx
> +The L2 Proxy Admin is an address that can be used to upgrade most OP Mainnet system contracts on L2. L2 Proxy Admin is the aliased address of the L1ProxyAdmin owner, which means the L2 ProxyAdmin Own
1. The suggestion @geoknee gave LGTM, I'd say we apply it.
2. To expand on how this works:
    - The link from @geoknee is the best description in our docs that I've seen, so it would be good to link to that here.
    - As mentioned in that link, given an L1 contract address, the aliased L2 address is equal to `L1_contract_address + 0x1111000000000000000000000000000000001111`
    - We'll use `0x6B1BAE59D09fCcbdDB6C6cceb07B7279367C4E3b` as the example (ref https://github.com/ethereum-optimism/docs/pull/753/files#r1643500731).
    - That 0x6B address is the L2 address that's been aliased, so to figure out the original L1 address we do `0x6B1BAE59D09fCcbdDB6C6cceb07B7279367C4E3b - 0x1111000000000000000000000000000000001111`
    - That result gives an L1 contract address of 0x5a0Aae59D09fccBdDb6C6CcEB07B7279367C3d2A, which is the L1 ProxyAdmin Owner. 
    - No one has the private key for 0x6B1BAE59D09fCcbdDB6C6cceb07B7279367C4E3b on OP Mainnet, which means the only way for the L2 ProxyAdmin owner to send transactions is via deposit transactions from the L1 0x5a0Aae59D09fccBdDb6C6CcEB07B7279367C3d2A address 

We have a [`AddressAliasHelper`](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/src/vendor/AddressAliasHelper.sol) library to help with those calculations

2024-06-18 18:40 UTC, mds1 commented on pages/chain/security/privileged-roles.mdx
> +*   **Ethereum**: [`0x6B1BAE59D09fCcbdDB6C6cceb07B7279367C4E3b`](https://optimistic.etherscan.io/address/0x6B1BAE59D09fCcbdDB6C6cceb07B7279367C4E3b)
Ref https://github.com/ethereum-optimism/docs/pull/753/files#r1644899273

2024-06-20 19:40 UTC, ZakAyesh approved these changes
lgtm

2024-06-20 20:52 UTC, cpengilly commented on pages/chain/security/privileged-roles.mdx
> +The L2 Proxy Admin is an address that can be used to upgrade most OP Mainnet system contracts on L2. L2 Proxy Admin is the aliased address of the L1ProxyAdmin owner, which means the L2 ProxyAdmin Own
updating now!

2024-06-20 20:57 UTC, merged