docs: Improve search ability for docker images
ethereum-optimism/docs pull request #809
Opened 2024-07-29 06:49 UTC by richardgreg

**Description**
1. **Comprehensive Software Releases:**
   - Expanding the scope to include all software components, not just node components.
   - Adding `op-challenger` to the list of software components with links to releases.

2. **Docker Image Searchability:**
   - Clear instructions and links to find Docker images for `op-node` and `op-geth`.
   - Consistent tagging conventions for Docker images to aid in searchability.

3. **Example Docker Image Tags:**
   - Examples of tagging the Docker images for better understanding and easier access.

**Tests**

Please describe any tests you've added. If you've added no tests, or left important behavior untested, please explain why not.

**Additional context**

Add any other context about the problem you're solving.

**Metadata**

- Fixes #785

2024-07-31 22:46 UTC, cpengilly approved these changes

2024-07-31 23:25 UTC, sbvegan requested changes

2024-07-31 23:25 UTC, sbvegan commented on pages/builders/node-operators/releases.mdx
> +description: Information on all software releases and how to stay up to date.
This change does not include all of the software releases.

2024-07-31 23:25 UTC, sbvegan commented on pages/builders/node-operators/releases.mdx
> -title: Node Software Releases
This should remain as node software releases

2024-08-03 03:19 UTC, cpengilly approved these changes

2024-08-03 20:22 UTC, sbvegan approved these changes

2024-08-03 20:22 UTC, merged