Create page in dev docs on individual identity.mdx
ethereum-optimism/docs pull request #821
Opened 2024-08-06 11:24 UTC by C-Emily-Furlong

**Description**

Adding a new page to the developer docs that covers how individual identity is represented in the Collective

**Tests**

Please describe any tests you've added. If you've added no tests, or left important behavior untested, please explain why not.

**Additional context**

Add any other context about the problem you're solving.

**Metadata**

- Fixes #[Link to Issue]

2024-08-06 13:35 UTC, krofax requested changes

2024-08-06 13:35 UTC, krofax commented on pages/chain/identity/individuals.mdx
> +Attestations can be made about individuals by leaving the recipient address blank and entering the user’s id into the attestation metadata.
```suggestion
The Optimism Collective represents individuals using unique identifiers generated through the **[Farcaster protocol id registry](https://docs.farcaster.xyz/reference/contracts/reference/id-registry)**. This system ensures a secure and standardized approach to identity management within the collective.

### Registering a User ID

To obtain a unique identifier:

1. Use the **[Farcaster Id Gateway](https://docs.farcaster.xyz/reference/contracts/reference/id-gateway)**
2. Use the Warpcast app, which:

* Creates a new custody address
* Acts as a wallet

### Making Attestations

When you make attestations about individuals:

* Leave the recipient address blank
* Enter the users id into the attestation metadata

```

2024-08-06 13:35 UTC, krofax commented on pages/chain/identity/individuals.mdx
> +You can read more about individual identity in **[the governance docs](https://community.optimism.io/docs/identity/project-and-individual-identity-in-the-collective/#building-a-digital-identity)**.
```suggestion

### Further Reading

For more details on individual identity in the Optimism Collective, refer to the **[the governance docs](https://community.optimism.io/docs/identity/project-and-individual-identity-in-the-collective/#building-a-digital-identity)** on building a digital identity.
```

2024-08-08 09:02 UTC, C-Emily-Furlong reviewed
👍

2024-08-12 14:50 UTC, merged