interop explaienrs
ethereum-optimism/docs pull request #825
Opened 2024-08-11 00:35 UTC by cpengilly

2 interop explainers

2024-08-12 19:53 UTC, sbvegan reviewed
This looks great!

2024-08-13 16:36 UTC, zainbacchus requested changes

2024-08-13 16:36 UTC, zainbacchus commented on pages/stack/protocol/interop/cross-chain-message.mdx
> +A cross-chain message applies to any asset using the [SuperchainERC20](https://specs.optimism.io/interop/token-bridging.html) token standard. Two transactions are required to complete a cross chain m
A cross-chain message applies to any message sent across chain. This applies to asset transfers using the SuperchainERC20 token standard.

2024-08-13 16:36 UTC, zainbacchus commented on pages/stack/protocol/interop/cross-chain-message.mdx
> +*   **Second transaction:** is submitted to a destination chain, where the block builder SHOULD only include it if certain that the first transaction was included in the source chain. NOTE: There is
Anyone can submit the second transaction. The block builder can use OP-Supervisor to determine the integrity of the initating message. 

cc @tynes

2024-08-13 16:36 UTC, zainbacchus commented on pages/stack/protocol/interop/cross-chain-message.mdx
> +## How It Works
(nit) Shouldnt this section be first?

2024-08-13 16:36 UTC, zainbacchus commented on pages/stack/protocol/interop/explainer.mdx
> +Interoperability is the ability for a blockchain to easily read the state of another blockchain.
easily => securely

2024-08-13 16:36 UTC, zainbacchus commented on pages/stack/protocol/interop/explainer.mdx
> +It is permissionless to define a dependency on a chain, so chain operators will be able to choose which chains their chains depend on, and it is not a requirement that chains are in each other's depe
The dependency set for OP Mainnet will be managed by Optimism Governance. 

cc @tynes

2024-08-13 16:36 UTC, zainbacchus commented on pages/stack/protocol/interop/explainer.mdx
> +*   The Superchain-backend `microservice` will be a requirement for running an OP Stack chain that has interop enabled.
isn't microservice OP-Supervisor? cc @tynes

2024-08-13 16:36 UTC, zainbacchus commented on pages/stack/protocol/interop/explainer.mdx
> +*   In the future, this service will rely on the P2P network and cryptographic schemes for validating cross chain messages, instead of RPCs.
In the future, to reduce the infrastructure cost, this service will...

cc @tynes

2024-08-13 16:36 UTC, zainbacchus commented on pages/stack/protocol/interop/explainer.mdx
> +If a sequencer does not want to trust another sequencer at all, they can choose to only accept executing messages where the initiating message has been finalized with L1 levels of security. This demo
should we add the safe/unsafe diagram here? cc @sbvegan

2024-08-13 18:07 UTC, sbvegan commented on pages/stack/protocol/interop/explainer.mdx
> +If a sequencer does not want to trust another sequencer at all, they can choose to only accept executing messages where the initiating message has been finalized with L1 levels of security. This demo
yeah I think its a good place for it, @cpengilly here's the image we can use to illustrate this point

![unsafe-safe-finalize](https://github.com/user-attachments/assets/9c83d6a1-08a4-4a4a-b109-11104df9af4c)

2024-08-21 17:47 UTC, cpengilly commented on pages/stack/protocol/interop/explainer.mdx
> +*   The Superchain-backend `microservice` will be a requirement for running an OP Stack chain that has interop enabled.
confirmed with @tynes that it is op-supervisor, so updating docs now 😅

2024-08-21 18:25 UTC, bradleycamacho commented on pages/stack/protocol/interop/cross-chain-message.mdx
> +    *   **Second/finalizing transaction:** is submitted to a destination chain, where the block builder SHOULD only include it if certain that the first transaction was included in the source chain.
```suggestion
    *   **Second/finalizing transaction:** is submitted to a destination chain, where the block builder should only include it if certain that the first transaction was included in the source chain. The block builder can use OP-Supervisor to determine the integrity of the initiating message. Anyone can submit the second transaction.
```

2024-08-21 18:26 UTC, bradleycamacho commented on pages/stack/protocol/interop/cross-chain-message.mdx
> +    *   **Second/finalizing transaction:** is submitted to a destination chain, where the block builder SHOULD only include it if certain that the first transaction was included in the source chain.
Capitalizing `SHOULD` seemed weird. Doesn't seem to need emphasis, and if the implication is "it might or might not", we should probably be a bit more clear

2024-08-21 18:39 UTC, bradleycamacho commented on pages/stack/protocol/interop/explainer.mdx
> +This means ETH and ERC-20s can seamlessly and securely move across L2s, and intent-based protocols, such as bridges, can build better experiences on top of the message passing protocol.
This sentence was pretty hard to parse. Not a blocker, just wanted to highlight.

2024-08-21 18:41 UTC, bradleycamacho commented on pages/stack/protocol/interop/explainer.mdx
> +Interoperability allows for horizontally scalable blockchains, a key feature of the Superchain. With native interop, latency can be low (~2 seconds) by optimistically accepting cross chain messages.
Should all instances of `cross chain` be `cross-chain`?

2024-08-21 18:42 UTC, bradleycamacho commented on pages/stack/protocol/interop/explainer.mdx
> +Chain operators can add or remove chains from the dependency set through the `SystemConfig`. For example, the dependency set for OP Mainnet is managed by Optimism Governance.
Do we need an example of this?

2024-08-21 18:45 UTC, bradleycamacho commented on pages/stack/protocol/interop/explainer.mdx
> +### What is the trust/verification model? Do Sequencers that opt into this interop system have to trust each other fully?
```suggestion
### What is the trust/verification model? Do sequencers that opt into this interop system have to trust each other fully?
```

2024-08-21 20:25 UTC, cpengilly commented on pages/stack/protocol/interop/explainer.mdx
> +Chain operators can add or remove chains from the dependency set through the `SystemConfig`. For example, the dependency set for OP Mainnet is managed by Optimism Governance.
yep, it's in the specs :)

2024-08-21 20:29 UTC, cpengilly commented on pages/stack/protocol/interop/explainer.mdx
> +Interoperability allows for horizontally scalable blockchains, a key feature of the Superchain. With native interop, latency can be low (~2 seconds) by optimistically accepting cross chain messages.
updated, we should prob add this to linter too, which I'll do in a separate PR

2024-08-21 20:42 UTC, zainbacchus approved these changes
lgtm

2024-08-21 20:43 UTC, merged