Migrate pnpm to just
ethereum-optimism/docs pull request #850
Opened 2024-08-23 18:21 UTC by krofax

**Description**

A clear and concise description of the features you're adding in this pull request.

**Tests**

Please describe any tests you've added. If you've added no tests, or left important behavior untested, please explain why not.

**Additional context**

Add any other context about the problem you're solving.

**Metadata**

- Fixes #[Link to Issue]

2024-09-12 23:57 UTC, sbvegan requested changes
Overall this migration away from pnpm to just in the monorepo is a little more nuanced and will require a deeper dive into the changes that were made. I also am not convinced we need to add just to the docs repo.

2024-09-12 23:57 UTC, sbvegan commented on CONTRIBUTING.md
> +3. Then, run `just dev` to start the development server and
Lets revert these changes. The documentation repository still uses `pnpm`. The monorepo migrated to `just`

2024-09-12 23:57 UTC, sbvegan commented on CONTRIBUTING.md
> +- Try another `just dev` and repeat until no issues are reported ("client" and "server compiled successfully").
Same comment as above

2024-09-12 23:57 UTC, sbvegan commented on README.md
> +Then, run `just dev` to start the development server and visit localhost:3000.
revert

2024-09-12 23:57 UTC, sbvegan commented on justfile
> +# List available recipes
oooohhhhh you added just to the docs project, I'm on the fence about adding it in the docs repo tbh. I'd be interested to hear what the other folks on the docs team think. Its my opinion that because this repository uses javascript as a dependency, it makes sense to keep `pnpm` as the package manager. It seems like the addition of `just` is extra overhead. Whereas in the monorepo, the javascript has been removed.

2024-09-12 23:57 UTC, sbvegan commented on pages/builders/chain-operators/tutorials/create-l2-rollup.mdx
> +just install
This doesn't map directly to the new justfile: https://github.com/ethereum-optimism/optimism/blob/develop/justfile

2024-09-12 23:57 UTC, sbvegan commented on pages/builders/chain-operators/tutorials/create-l2-rollup.mdx
> +just build
same comment as above

2024-09-12 23:57 UTC, sbvegan commented on pages/builders/node-operators/tutorials/node-from-source.mdx
>  Install the Node.js dependencies for the Optimism Monorepo.
There is no longer javascript/nodejs in the monorepo

2024-09-12 23:57 UTC, sbvegan commented on pages/builders/node-operators/tutorials/node-from-source.mdx
> +just install
this doesn't map to the justfile https://github.com/ethereum-optimism/optimism/blob/develop/justfile

2024-09-12 23:57 UTC, sbvegan commented on pages/builders/node-operators/tutorials/node-from-source.mdx
> +just build
same comment

2024-09-25 16:20 UTC, krofax commented
@sbvegan 

> oooohhhhh you added just to the docs project, I'm on the fence about adding it in the docs repo tbh. I'd be interested to hear what the other folks on the docs team think. Its my opinion that because this repository uses javascript as a dependency, it makes sense to keep pnpm as the package manager. It seems like the addition of just is extra overhead. Whereas in the monorepo, the javascript has been removed.

This is completely valid, closing the PR.

2024-09-25 16:20 UTC, closed without merging