adding audit template
ethereum-optimism/docs pull request #891
Opened 2024-09-10 16:37 UTC by sbvegan

**Description**

I'm going to use this issue template for running through the technical documentation audit.

2024-09-10 17:18 UTC, bradleycamacho requested changes

2024-09-10 17:18 UTC, bradleycamacho commented on pages/builders/chain-operators/configuration/rollup.mdx
> +A 1/1 Safe owned by the Security Council Safe, with the [Deputy Guardian Module](https://specs.optimism.io/protocol/safe-extensions.html#deputy-guardian-module)
This works, but should it be its own PR so it's not tied to the audit template going live?

2024-09-10 17:18 UTC, bradleycamacho commented on .github/ISSUE_TEMPLATE/docs_audit_results.md
> +## Description of the updates required
Love to see sentence case

2024-09-10 17:18 UTC, bradleycamacho commented on .github/ISSUE_TEMPLATE/docs_audit_results.md
> +> Write a description of the current state of the page.
Are you going to be writing all the audit results? An example of how in-depth the description should be would be helpful if not (bullet points, intended users, relation to other docs, etc.)

2024-09-10 17:18 UTC, bradleycamacho commented on .github/ISSUE_TEMPLATE/docs_audit_results.md
> +<summary>T-shirt size</summary>
The relationship between size and content evaluation (`a-critical` for example) is a bit unclear to me. Is there value in both?

2024-09-10 17:18 UTC, bradleycamacho commented on .github/ISSUE_TEMPLATE/docs_audit_results.md
> +- `s-XL`: (> 1 month) Very large and complex projects that involve extensive planning, execution, and testing.
Absolutely not essential, but defining these in context of our upcoming sprints could be useful - "Complex tasks that require significant time investment and multiple sprints"

2024-09-10 17:18 UTC, bradleycamacho commented on .github/ISSUE_TEMPLATE/docs_audit_results.md
> +- `s-XL`: (> 1 month) Very large and complex projects that involve extensive planning, execution, and testing.
If any single doc is `s-XL`, it should likely be split up into multiple docs OR at a minimum multiple subtasks.

When we start working in sprints, an XL won't be complete in a single sprint and we should avoid bringing the same issue into multiple sprints. We should chunk it out into MMFs tied to the XL.

2024-09-10 17:18 UTC, bradleycamacho commented on .github/ISSUE_TEMPLATE/docs_audit_results.md
> +## MDX Metadata format
We should take a look at the metadescription in the frontmatter of each doc (some could use some love/optimization for SEO)

2024-09-10 17:21 UTC, sbvegan commented on .github/ISSUE_TEMPLATE/docs_audit_results.md
> +## Description of the updates required
I'm doing my best to integrate the style guide :D

2024-09-10 17:23 UTC, sbvegan commented on pages/builders/chain-operators/configuration/rollup.mdx
> +A 1/1 Safe owned by the Security Council Safe, with the [Deputy Guardian Module](https://specs.optimism.io/protocol/safe-extensions.html#deputy-guardian-module)
I just threw them in to fix the low hanging fruit. If you'd rather have them split out, just lmk :)

2024-09-10 17:28 UTC, sbvegan commented on .github/ISSUE_TEMPLATE/docs_audit_results.md
> +<summary>T-shirt size</summary>
Good idea, I'd be down just to remove content evaluation. T-shirt size and description should be sufficient.

2024-09-10 17:29 UTC, bradleycamacho commented on pages/builders/chain-operators/configuration/rollup.mdx
> +A 1/1 Safe owned by the Security Council Safe, with the [Deputy Guardian Module](https://specs.optimism.io/protocol/safe-extensions.html#deputy-guardian-module)
Keeping them works!

2024-09-10 17:29 UTC, sbvegan commented on .github/ISSUE_TEMPLATE/docs_audit_results.md
> +- `s-XL`: (> 1 month) Very large and complex projects that involve extensive planning, execution, and testing.
Great feedback, I have these descriptions in our project board, but I'm down to tailor them to the sprint process

2024-09-10 17:30 UTC, sbvegan commented on .github/ISSUE_TEMPLATE/docs_audit_results.md
> +## MDX Metadata format
This one definitely falls out of my domain. Do you have any resources/guidance on how I can evaluate this during the audit?

2024-09-10 17:32 UTC, bradleycamacho commented on .github/ISSUE_TEMPLATE/docs_audit_results.md
> +## MDX Metadata format
SEO also falls out of my domain, but maybe @cpengilly has some ideas?

I think it could be as simple as:

> If I was actively searching for this page on google and this description was the search result, would I know it's the correct page?

2024-09-11 14:50 UTC, bradleycamacho approved these changes

2024-09-11 16:40 UTC, merged