Bridging ETH to OP Mainnet With Viem
ethereum-optimism/docs pull request #906
Opened 2024-09-18 00:53 UTC by krofax

**Description**

This tutorial explains how you can use the Viem to bridge ETH from L1 (Ethereum or Sepolia) to L2 (OP Mainnet or OP Sepolia), it deprecates the Optimism SDK.

**Tests**

Please describe any tests you've added. If you've added no tests, or left important behavior untested, please explain why not.

**Additional context**

Add any other context about the problem you're solving.

**Metadata**

- Fixes #[Link to Issue]

2024-09-23 09:05 UTC, brokewhale reviewed
Honestly, I think there might be a bit of a flow break in this tutorial  when viewed from an absolute beginner's perspective. It'd be really helpful if we could make the steps as straightforward and easy to follow as possible.

The full code snippet approach is awesome. If we can have something like the CLI approach, along with a full code snippet, that would be fantastic.

2024-09-24 11:06 UTC, krofax commented on pages/builders/app-developers/tutorials/cross-dom-bridge-eth.mdx
> +<Tabs items={['Create an account', 'Create RPC providers', 'Wallet Clients']}>
@brokewhale i thought about this, but then, inside some tabs are some steps, and we cannot have nested steps.

2024-09-24 12:00 UTC, krofax commented on pages/builders/app-developers/tutorials/cross-dom-bridge-eth.mdx
> +// Import required modules
Added a step for clarity

2024-09-24 15:38 UTC, krofax commented
> Honestly, I think there might be a bit of a flow break in this tutorial when viewed from an absolute beginner's perspective. It'd be really helpful if we could make the steps as straightforward and easy to follow as possible.
> 
> The full code snippet approach is awesome. If we can have something like the CLI approach, along with a full code snippet, that would be fantastic.

What do you mean by a CLI approach?

2024-10-02 15:04 UTC, krofax commented
@brokewhale You can check out this tutorial now.

2024-10-07 10:09 UTC, brokewhale commented
> @brokewhale You can check out this tutorial now.

on it

2024-10-07 15:47 UTC, brokewhale reviewed
some reviews for now. Deposit reviewed 
some things you should note

- some codeblocks are broken
- some are empty
- on the withdrawal part you might want to rename some of the const to be different from deposit to allow continuity 


example
on the deposit side
```js
const args = await publicClientL2.buildDepositTransaction({
    mint: parseEther("0.0001"),
    to: account.address,
});
```

you can't use `args` anymore on the withdrawal side unless you want to restart the node

this will error

```js
//Add the same imports used in DepositETH function
const args = await publicClientL2.buildWithdrawalTransaction({
withdrawalAmount: parseEther("0.0001"),
});
```

instead you can do
```js
const depositArgs = await publicClientL2.buildDepositTransaction({
    mint: parseEther("0.0001"),
    to: account.address,
});
```

and 

```js
//Add the same imports used in DepositETH function
const withdrawalArgs  = await publicClientL2.buildWithdrawalTransaction({
withdrawalAmount: parseEther("0.0001"),
});

and for others too

if the intent is to close the current session and start `node` again while importing all over again then it's fine, but i feel just continuing is better

2024-10-09 09:29 UTC, brokewhale commented on pages/builders/app-developers/tutorials/cross-dom-bridge-eth.mdx
> +      ```js file=<rootDir>/public/tutorials/cross-dom-bridge-eth.js#L58-L63 hash=357eede3fe4b79bbd160892cfee5d8ec
you want to stop at L62,

there is a trailing `}`

2024-10-09 09:29 UTC, brokewhale commented on public/tutorials/cross-dom-bridge-eth.js
> +const hash = await walletClientL2.initiateWithdrawal(withdrawalArgs);
```js
const withdrawalHash = await walletClientL2.initiateWithdrawal(withdrawalArgs);
```

2024-10-09 09:29 UTC, brokewhale commented on public/tutorials/cross-dom-bridge-eth.js
> +console.log(`Withdrawal transaction hash on L2: ${hash}`);
`console.log(`Withdrawal transaction hash on L2: ${withdrawalHash}`);
`

2024-10-09 09:29 UTC, brokewhale commented on public/tutorials/cross-dom-bridge-eth.js
> +const receipt = await publicClientL2.waitForTransactionReceipt({ hash });
`const withdrawalReceipt = await publicClientL2.waitForTransactionReceipt({ withdrawalHash });
`

2024-10-09 09:29 UTC, brokewhale commented on public/tutorials/cross-dom-bridge-eth.js
> +receipt,
`withdrawalReceipt `

2024-10-09 09:29 UTC, brokewhale commented on public/tutorials/cross-dom-bridge-eth.js
> +receipt,
`withdrawalReceipt `

2024-10-09 09:29 UTC, brokewhale commented on pages/builders/app-developers/tutorials/cross-dom-bridge-eth.mdx
> +      ```js file=<rootDir>/public/tutorials/cross-dom-bridge-eth.js#L108-L113 hash=d23afa6efca5573a71a1fe8e1205f997
should end at L112

2024-10-09 12:05 UTC, brokewhale commented on public/tutorials/cross-dom-bridge-eth.js
> +const Deposithash = await walletClientL1.depositTransaction(depositArgs);
depositHash

2024-10-09 12:23 UTC, brokewhale approved these changes

2024-10-21 11:35 UTC, brokewhale requested changes
all good except this

2024-10-21 11:35 UTC, brokewhale commented on public/tutorials/cross-dom-bridge-eth.js
> +});
```js

// Build parameters to initiate the withdrawal transaction on the L1.
const withdrawalArgs = await publicClientL1.buildInitiateWithdrawal({
  to: account.address,
  value: parseEther('0.0001')
})
 ```

2024-10-21 16:30 UTC, krofax commented
> all good except this

Done, please approve.

2024-10-21 16:33 UTC, brokewhale approved these changes

2024-10-21 22:55 UTC, bradleycamacho requested changes
Just a few changes! Nothing large, good job on this!

2024-10-21 22:55 UTC, bradleycamacho commented on pages/builders/app-developers/tutorials/cross-dom-bridge-eth.mdx
> +title: Bridging ETH with Viem
```suggestion
title: Bridging ETH with viem
```

2024-10-21 22:55 UTC, bradleycamacho commented on pages/builders/app-developers/tutorials/cross-dom-bridge-eth.mdx
> +# Bridging ETH to OP Mainnet With Viem
```suggestion
# Bridging ETH to OP Mainnet with viem
```

2024-10-21 22:55 UTC, bradleycamacho commented on pages/builders/app-developers/tutorials/cross-dom-bridge-eth.mdx
> +title: Bridging ETH with Viem
Their docs are really sketchy in regards to accurate use, but it seems that `viem` should always be lowercase. I'll only mark one or two instances, but you should take a pass over the entire PR and lowercase it

https://viem.sh/docs/introduction

2024-10-21 22:55 UTC, bradleycamacho commented on pages/builders/app-developers/tutorials/cross-dom-bridge-eth.mdx
> +  *   Challenge Period: The 7-day withdrawal challenge Period is crucial for security.
```suggestion
  *   Challenge period: The 7-day withdrawal challenge Period is crucial for security.
```

2024-10-21 22:55 UTC, bradleycamacho commented on pages/builders/app-developers/tutorials/cross-dom-bridge-eth.mdx
> +  *   Gas Costs: Withdrawals involve transactions on both L2 and L1, each incurring gas fees.
```suggestion
  *   Gas costs: Withdrawals involve transactions on both L2 and L1, each incurring gas fees.
```

2024-10-21 22:55 UTC, bradleycamacho commented on pages/builders/app-developers/tutorials/cross-dom-bridge-eth.mdx
> +  *   Private Key Handling: Use secure key management practices in real applications.
```suggestion
  *   Private Key handling: Use secure key management practices in real applications.
```

2024-10-21 22:55 UTC, bradleycamacho commented on pages/builders/app-developers/tutorials/cross-dom-bridge-eth.mdx
> +  *   Private Key Handling: Use secure key management practices in real applications.
Not sure if Key is capitalized

2024-10-21 22:55 UTC, bradleycamacho commented on pages/builders/app-developers/tutorials/cross-dom-bridge-eth.mdx
> +  *   RPC Endpoint Security: Keep your API key (or any RPC endpoint) secure.
```suggestion
  *   RPC endpoint security: Keep your API key (or any RPC endpoint) secure.
```

2024-10-21 22:55 UTC, bradleycamacho commented on pages/builders/app-developers/tutorials/cross-dom-bridge-eth.mdx
> +*   Develop a user interface for easier interaction with these bridging functions.
Do we have any resources we can share here? These are two really large "steps" and it'd be nice to give users a breadcrumb to follow at the least

2024-10-25 16:11 UTC, bradleycamacho approved these changes

2024-10-27 22:16 UTC, fujianggara10 commented
Good job fellow

2024-10-30 11:00 UTC, merged