feat: added close callout btn
ethereum-optimism/docs pull request #933
Opened 2024-09-26 19:44 UTC by brokewhale

added callout close btn

https://github.com/user-attachments/assets/8cd8a0e8-b101-4e1e-a5c4-ce627c24571e

2024-09-26 19:51 UTC, krofax approved these changes

2024-09-26 19:54 UTC, bradleycamacho requested changes
Looks great! As long as the button is actually clickable on mobile and you check out my small comment, this looks great to me! Thanks!!

2024-09-26 19:54 UTC, bradleycamacho commented on components/WipCallout.tsx
> +            The Alt-DA Mode feature is currently in <strong>Beta</strong> within
Can we get these into a single line again? Or did they get split up for a reason?

2024-09-26 19:59 UTC, brokewhale commented on components/WipCallout.tsx
> +            The Alt-DA Mode feature is currently in <strong>Beta</strong> within
ohh just seeing this, i think this might be the result of the linting

2024-09-26 19:59 UTC, bradleycamacho commented
> Looks great! As long as the button is actually clickable on mobile and you check out my small comment, this looks great to me! Thanks!!

Can confirm the button works on mobile btw

2024-09-26 20:03 UTC, brokewhale commented on components/WipCallout.tsx
> +            The Alt-DA Mode feature is currently in <strong>Beta</strong> within
but it should still render the same way regardless

2024-09-26 20:15 UTC, brokewhale commented on components/WipCallout.tsx
> +            The Alt-DA Mode feature is currently in <strong>Beta</strong> within
mobile confirmed

https://github.com/user-attachments/assets/cefdc8a1-08e9-4e38-8751-84f8942398cb

2024-09-26 20:23 UTC, brokewhale reviewed
✅

2024-09-27 14:30 UTC, krofax commented
@bradleycamacho please approval and merge.

2024-10-03 15:43 UTC, merged