Tracing Deposits and Withdrawals
ethereum-optimism/docs pull request #966
Opened 2024-10-08 14:30 UTC by krofax

**Description**

This tutorial explains how you can use the Viem race a deposit or withdrawal transaction between L1 and L2. It deprecates the Optimism SDK.

**Tests**

**Additional context**

**Metadata**

- Fixes https://github.com/ethereum-optimism/devrel/issues/257

2024-10-10 22:07 UTC, bradleycamacho approved these changes
This still needs a tech review so I'm happy to review again later, but this look great to me! Just make sure to update the headers to comply with the new style

2024-10-15 19:03 UTC, ZakAyesh commented
For all of these tutorials usually there is a step for running the command `mkdir op-sample-project` if we assume that developers go through a couple of these they may have trouble creating the directories since they will have to overwrite their old one. Can we name the directories something based on the content of the tutorial. Like for this one:

`mkdir op-tracing-tutorial`

2024-10-18 14:56 UTC, krofax commented
> For all of these tutorials usually there is a step for running the command `mkdir op-sample-project` if we assume that developers go through a couple of these they may have trouble creating the directories since they will have to overwrite their old one. Can we name the directories something based on the content of the tutorial. Like for this one:
> 
> `mkdir op-tracing-tutorial`

@ZakAyesh Updated the tut, can you take a second review?

2024-10-18 15:33 UTC, brokewhale commented on public/tutorials/sdk-trace-txns.js
> +  chain: optimism,
chain should be mainnet or sepolia

2024-10-18 15:33 UTC, brokewhale commented on public/tutorials/sdk-trace-txns.js
> +  chain: optimism,
you should also import 
 const { mainnet, optimism } = await import("viem/chains");

2024-10-18 19:57 UTC, brokewhale approved these changes
the chains are not imported, they should

2024-10-21 22:49 UTC, bradleycamacho approved these changes

2024-10-21 22:49 UTC, bradleycamacho commented on pages/builders/app-developers/tutorials/sdk-trace-txns.mdx
> +*   Check out the tutorial on [Bridging ERC-20 Tokens With the Optimism SDK](./cross-dom-bridge-erc20) to learn how to create deposits and withdrawals.
```suggestion
*   Check out the tutorial on [bridging ERC-20 tokens with the Optimism SDK](./cross-dom-bridge-erc20) to learn how to create deposits and withdrawals.
```

2024-10-21 22:49 UTC, bradleycamacho commented on pages/builders/app-developers/tutorials/sdk-trace-txns.mdx
> +*   You can also check out the tutorial on [Viewing Deposits and Withdrawals by Address](./sdk-view-txns) to find deposits and withdrawals to trace.
```suggestion
*   You can also check out the tutorial on [viewing deposits and withdrawals by address](./sdk-view-txns) to find deposits and withdrawals to trace.
```

2024-10-21 22:49 UTC, bradleycamacho commented on pages/builders/app-developers/tutorials/sdk-trace-txns.mdx
> +*   Check out the tutorial on [Bridging ERC-20 Tokens With the Optimism SDK](./cross-dom-bridge-erc20) to learn how to create deposits and withdrawals.
We should def sentence case the link, but I have less strong opinion on if `bridging` should be lower case or caps. I lean towards lowercasing since we're not saying "look at our Bridging ERC-20... doc", but use the title as the action. 

Let me know if that doesn't make sense

2024-10-22 15:29 UTC, ZakAyesh requested changes

2024-10-22 15:29 UTC, ZakAyesh commented on pages/builders/app-developers/tutorials/sdk-trace-txns.mdx
> +export L1_RPC_URL="https://rpc.ankr.com/eth_sepolia"
Change to `export L1_RPC_URL="https://YOUR_L1_ SEPOLIA_RPC_URL_HERE` 

This way it minimizes users blindly copying and pasting code when going through the tutorial.

2024-10-22 15:29 UTC, ZakAyesh commented on pages/builders/app-developers/tutorials/sdk-trace-txns.mdx
> +export L2_RPC_URL="https://sepolia.optimism.io"
Change to `export L2_RPC_URL="https://YOUR_L2_OP_SEPOLIA_RPC_URL_HERE`

This way it minimizes users blindly copying and pasting code when going through the tutorial.

2024-10-22 15:29 UTC, ZakAyesh commented on pages/builders/app-developers/tutorials/sdk-trace-txns.mdx
> +  ```js file=<rootDir>/public/tutorials/sdk-trace-txns.js#L16-L25 hash=b44b43868a421156320884045294f7ca
At this point I got this error and was unable to continue the tutorial:

`Uncaught ReferenceError: optimismSepolia is not defined`

2024-10-22 16:28 UTC, krofax commented on pages/builders/app-developers/tutorials/sdk-trace-txns.mdx
> +export L1_RPC_URL="https://rpc.ankr.com/eth_sepolia"
The idea is for users to copy and paste it, into their terminal.

2024-10-22 19:30 UTC, ZakAyesh requested changes

2024-10-22 19:30 UTC, ZakAyesh commented on pages/builders/app-developers/tutorials/sdk-trace-txns.mdx
> +  ```js file=<rootDir>/public/tutorials/sdk-trace-txns.js#L9-L10 hash=014f5d17eddb45fc081c7db9f33361b4
Earlier in the tutorial we exported the RPC URL as an environment variable, should we just use that rather than declaring a new variable?

2024-10-22 19:30 UTC, ZakAyesh commented on pages/builders/app-developers/tutorials/sdk-trace-txns.mdx
> +  ```js file=<rootDir>/public/tutorials/sdk-trace-txns.js#L9-L10 hash=014f5d17eddb45fc081c7db9f33361b4
Also, it seems the L2 RPC is missing a variable here which is necessary for the code below

2024-10-28 14:46 UTC, krofax commented
@ZakAyesh Can you please check this one more time?

2024-10-30 18:05 UTC, ZakAyesh requested changes

2024-10-30 18:05 UTC, ZakAyesh commented on pages/builders/app-developers/tutorials/sdk-trace-txns.mdx
> +  ```js file=<rootDir>/public/tutorials/sdk-trace-txns.js#L13-L14 hash=6be30f5429fdd050fc32c21de4627d2e
The code isn't importing the environment variables correctly. Code suggested below:

```
const l1RpcUrl = process.env.L1_RPC_URL;
const l2RpcUrl = process.env.L2_RPC_URL;

2024-10-31 15:49 UTC, krofax commented on pages/builders/app-developers/tutorials/sdk-trace-txns.mdx
> +  ```js file=<rootDir>/public/tutorials/sdk-trace-txns.js#L13-L14 hash=6be30f5429fdd050fc32c21de4627d2e
Thanks for that catch i've updated it.

2025-01-21 06:35 UTC, Nifitsas4 approved these changes

2025-01-21 18:19 UTC, ZakAyesh approved these changes

2025-01-22 14:55 UTC, merged