supersim explainer
ethereum-optimism/docs pull request #978
Opened 2024-10-11 19:32 UTC by cpengilly

- page is under interop
- symbolic link added under app devs > tools
- meta.json files updated in both directories

2024-10-11 23:13 UTC, fainashalts reviewed
Had some comments/revisions, but looking great! Thanks for putting this together and let me know when you're ready for a re-review!

2024-10-11 23:13 UTC, fainashalts commented on pages/builders/app-developers/tools/_meta.json
> +    "supersim": "SuperSim IDE",
I don't think we're capitalizing the second S

2024-10-11 23:13 UTC, fainashalts commented on pages/builders/app-developers/tools/_meta.json
> +    "supersim": "SuperSim IDE",
```suggestion
    "supersim": "Supersim Multichain Development Environment",
```

2024-10-11 23:13 UTC, fainashalts commented on pages/stack/protocol/interop/_meta.json
> +    "supersim": "SuperSim Explainer"
```suggestion
    "supersim": "Supersim Explainer"
```

2024-10-11 23:13 UTC, fainashalts commented on pages/stack/protocol/interop/supersim.mdx
> +title: SuperSim Explainer
```suggestion
title: Supersim Explainer
```

2024-10-11 23:13 UTC, fainashalts commented on pages/stack/protocol/interop/supersim.mdx
> +description: Learn how to use the SuperSim local dev environment tool designed to simulate the Optimism Superchain.
```suggestion
description: Learn how to use the Supersim local dev environment tool designed to simulate the Optimism Superchain.
```

2024-10-11 23:47 UTC, cpengilly commented on pages/stack/protocol/interop/supersim.mdx
> +*   Integration with common Ethereum development tools (e.g., Hardhat, Foundry)
updating now!

2024-10-12 00:20 UTC, cpengilly commented
@fainashalts ready for re-review!

2024-10-12 00:34 UTC, fainashalts requested changes
Just a couple more changes requested!

2024-10-12 00:34 UTC, fainashalts commented on pages/builders/app-developers/tools/supersim.mdx
> +import SuperSim from '@/pages/stack/protocol/interop/supersim.mdx'
Should rename to remove the second capitalized S.

2024-10-12 00:34 UTC, fainashalts commented on pages/builders/app-developers/tools/supersim.mdx
> +<SuperSim />
```suggestion
<Supersim />
```

2024-10-12 00:34 UTC, fainashalts commented on pages/stack/protocol/interop/supersim.mdx
> +graph TD
This isn't quite right. The predeployed contracts are part of supersim, not a separate thing. GH comments are a bit annoying for editing mermaid charts but I would just remove the pred-deployed contracts part and the arrows coming out of it.

2024-10-12 00:51 UTC, cpengilly commented
final check @fainashalts

2024-10-12 03:06 UTC, fainashalts approved these changes
LGTM!

2024-10-12 03:47 UTC, fainashalts commented
@cpengilly I see an error in CI, looks like some file paths might be wrong!

2024-10-13 16:10 UTC, sbvegan approved these changes
looks good to me, I know we need this one out, but can we add sentence case to the headers?

2024-10-13 16:10 UTC, sbvegan commented on pages/stack/protocol/interop/supersim.mdx
> +## Supersim Workflow
```suggestion
## Supersim workflow
```

2024-10-13 16:10 UTC, sbvegan commented on pages/stack/protocol/interop/supersim.mdx
> +## Features and Benefits
```suggestion
## Features and benefits
```

2024-10-13 16:10 UTC, sbvegan commented on pages/stack/protocol/interop/supersim.mdx
> +## Next Steps
```suggestion
## Next steps
```

2024-10-13 16:10 UTC, sbvegan commented on pages/stack/protocol/interop/supersim.mdx
> +# Supersim Multichain Development Environment
```suggestion
# Supersim multichain development environment
```

2024-10-13 16:10 UTC, sbvegan commented on pages/stack/protocol/interop/explainer.mdx
>  ## Next Steps
```suggestion
## Next steps
```

2024-10-14 01:39 UTC, merged