superchainERC20
ethereum-optimism/docs pull request #986
Opened 2024-10-14 04:16 UTC by cpengilly

- explainer added to op stack > protocol > interop
- symbolic link added to builders > app devs > contracts

2024-10-15 13:59 UTC, pharger commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +`SuperchainERC20` is a token standard specifically designed for the Superchain ecosystem. It serves as the foundation for interoperable tokens within the Superchain, including `GovToken`, `WETH` (Wra
> `SuperchainERC20` is a token standard specifically designed for the Superchain ecosystem.
This should probably lean more in the Ethereum crosschain standardization. Maybe something like:

"`SuperchainERC20` is a token standard designed to enable asset interoperability in the Superchain ecosystem. It serves as the foundational token deployment pattern within the Superchain, including `GovToken`, `WETH` (Wrapped Ether), migrated `OptimismMintableERC20Tokens`, and newly minted native `SuperchainERC20`. This standard is crucial for enabling a more interconnected and efficient token ecosystem within the Superchain, balancing the needs for interoperability, security, and simplified developer experience."

2024-10-15 14:00 UTC, pharger commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +*   **Built-in bridging**: The bridging interface exists on the token itself, eliminating the need for a central bridge predeploy (e.g., `bridgeERC20`, `bridgeERC20To`).
Not sure I follow this one?

2024-10-17 18:54 UTC, cpengilly commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +`SuperchainERC20` is a token standard specifically designed for the Superchain ecosystem. It serves as the foundation for interoperable tokens within the Superchain, including `GovToken`, `WETH` (Wra
love it! updated!

2024-10-17 18:55 UTC, cpengilly commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +*   **Built-in bridging**: The bridging interface exists on the token itself, eliminating the need for a central bridge predeploy (e.g., `bridgeERC20`, `bridgeERC20To`).
no prob, removing it 😆

2024-10-17 18:57 UTC, cpengilly commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +*   **Consistency**: Provides a unified standard for tokens across all Superchain-compatible networks.
updated the lang. can you send the link over pls?

2024-10-17 18:58 UTC, cpengilly commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +*   **Governance minimized**: Designed to keep tokens within the Superchain ecosystem with minimal governance intervention.
yep, removed! in both places!

2024-10-17 18:59 UTC, cpengilly commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +*   **Bridging Functions**: using methods like `bridgeERC20` and `bridgeERC20To` for cross-chain transfers.
great catch! thanks!

2024-10-17 19:03 UTC, cpengilly commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +`SuperchainERC20` differs from other token standards in its focus and implementation:
yay! thank you!

2024-10-17 19:08 UTC, cpengilly commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +2.  Permission `crosschainMint` and `crosschainBurn` to the Superchain bridge address
agreed, updated!

2024-10-17 22:12 UTC, sbvegan approved these changes
lgtm! although, I think it would be very nice is we can pull the whole `Interoperability` section up a level and drop it under `Experimental`. Then setup redirect links. I can address this in a different PR, but I think this will help with visibility and help illustrate that this is a developing feature.

2024-10-17 22:24 UTC, zainbacchus requested changes
Lgtm but two general changes needed before approval:

- Make intro concise, we're also glossing over how amazing interop is. it allows for tokens to make across chains without asset wrapping, middlechains, or liquidity pools for maximal capital efficiency - unifying liquidity and simplifying user experience.
- Clean up some fragments in following sections

2024-10-17 22:24 UTC, zainbacchus commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +For now, application developers should view `SuperchainERC20`as standard ERC20 tokens with additional built-in functions that will be enabled once Interop goes live.
built-in functions that allow cross-chain asset movement that will be enabled once Interop goes live.

2024-10-17 22:24 UTC, zainbacchus commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +  `SuperchainERC20` token must give access to the address where the future Interop bridge will live.
In order to enable asset interoperability, `SuperchainERC20` token must give access to the address where the future`SuperchainERC20Bridge` will live.

2024-10-17 22:24 UTC, zainbacchus commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +`SuperchainERC20` is a token standard designed to enable asset interoperability in the Superchain ecosystem.
tbh you could get away with just saying 

`SuperchainERC20` is a token standard designed to enable asset interoperability in the Superchain.

Not sure what we're adding with (It serves as...) and (This standard is crucial for...)

2024-10-17 22:24 UTC, zainbacchus commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +*   **Ethereum-aligned**: Intentionally designed to be supported across the EVM ecosystem (RIP coming soon).
Prob a better way to say this. 

**Ethereum-aligned**: Intentionally designed to be generic and supported as an Ethereum-wide standard (RIP coming soon).

2024-10-17 22:24 UTC, zainbacchus commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +*   `SuperchainERC20` shares trust assumptions across all chains in the superchain, such that custom assumptions around security and latency are not required to account for when executing transfers.
S in Superchain should be uppercase

2024-10-17 22:24 UTC, zainbacchus commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +Application developers must complete two tasks to enable `SuperchainERC20`. This advance setup ensures that `SuperchainERC20` goes live when the Interop upgrade happens and tokens becomes interoperab
This is a weird paragraph. 

We should be trying to say:
-App devs must do two things to make their tokens SuperchainERC20 compatible
-Doing this setup today will ensure that their tokens can benefit from Interop once the Interop upgrade happens

2024-10-17 22:30 UTC, zainbacchus commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +`SuperchainERC20` is a token standard designed to enable asset interoperability in the Superchain ecosystem.
Consider exapnding on what asset interoperability means.....it allows for tokens to securely move across chains without asset wrapping or liquidity pools for maximal capital efficiency - unifying liquidity and simplifying user experience.
 
 Should we talk about how it works?
 
This standard work facilitates secure token transfers between chains in the Superchain networks via native burning and minting.
 
 Initating message where Token is burned on the source chain: a user initiates a transfer of token from one blockchain to another, and specifies the recipient wallet address on the destination chain. A specified amount of token is burned on the source chain.
 
 Executing message where token is minted on the destination chain. The specified amount of token is minted on the destination chain and sent to the recipient wallet address.

2024-10-18 05:28 UTC, cpengilly commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +*   **Ethereum-aligned**: Intentionally designed to be supported across the EVM ecosystem (RIP coming soon).
updated

2024-10-18 05:42 UTC, cpengilly commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +It serves as the foundational token deployment pattern within the Superchain, including `GovToken`, `WETH` (Wrapped Ether), migrated `OptimismMintableERC20Tokens`, and newly minted native `Superchain
removed and replaced with lang above

2024-10-18 05:59 UTC, cpengilly commented
@zainbacchus addressed your comments, thank you for the awesome review!
@sbvegan I totally agree! ❤️

2024-10-18 06:04 UTC, cpengilly commented
@coderabbit can you generate a mermaid diagram for the 'how it works' section, explaining the minting and burning flow?

2024-10-18 12:15 UTC, zainbacchus approved these changes

2024-10-18 12:15 UTC, zainbacchus commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +*   **Minting Role**: modifies the definition to be minting role-based rather than interface-based.
should be removed

2024-10-18 17:36 UTC, skeletor-spaceman requested changes

2024-10-18 17:36 UTC, skeletor-spaceman commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +*   **Permissionless propagation**: Easily clone an existing token contract to a new OP Stack chain using `create2` without requiring the original owner, which enables movement of assets to the new c
```suggestion
*   **Permissionless propagation**: Easily clone an existing token contract to a new OP Stack chain using `create2` without requiring the original deployer, which enables movement of assets to the new chain once Interop goes live. Importantly, permissionless propagation retains the integrity of the original owner on the contract and preserves security but proliferates the contract's availability to new chains.
```

2024-10-18 17:36 UTC, skeletor-spaceman commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +*   Executing message where token is **minted** on the destination chain. The specified amount of token is minted on the destination chain and sent to the recipient wallet address.
```suggestion
*   Executing message where token is **minted** on the destination chain. The specified amount of token is minted on the destination chain directly to the recipient wallet address.
```

2024-10-18 17:36 UTC, skeletor-spaceman commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +*   **Minting Role**: modifies the definition to be minting role-based rather than interface-based.
```suggestion
```

2024-10-18 17:36 UTC, skeletor-spaceman commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +For now, application developers should view `SuperchainERC20`as standard ERC20 tokens with additional built-in functions that allow cross-chain asset movement that will be enabled once Interop goes l
```suggestion
For now, application developers should view `SuperchainERC20` as standard ERC20 tokens with additional built-in functions that allow cross-chain asset movement that will be enabled once Interop goes live.
```

2024-10-18 17:36 UTC, skeletor-spaceman commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +*   Join the discussion! `SuperchainERC20` implementation is being developed in partnership with Wonderland, with discussions taking place in the [#interop-evm](https://discord.gg/3zvcEFj6Nu) Discord
should this invite link be public?

2024-10-18 17:44 UTC, cpengilly commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +*   Join the discussion! `SuperchainERC20` implementation is being developed in partnership with Wonderland, with discussions taking place in the [#interop-evm](https://discord.gg/3zvcEFj6Nu) Discord
@skeletor-spaceman ooh i'm not sure, would you like me to remove it for now? [just the link]

2024-10-18 17:44 UTC, cpengilly commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +*   Join the discussion! `SuperchainERC20` implementation is being developed in partnership with Wonderland, with discussions taking place in the [#interop-evm](https://discord.gg/3zvcEFj6Nu) Discord
cc @zainbacchus @pharger

2024-10-18 17:44 UTC, skeletor-spaceman commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +```
https://specs.optimism.io/interop/token-bridging.html?highlight=token-bridg#diagram
you can use this on the example, since it's a bit more precise on the flow

2024-10-18 17:46 UTC, skeletor-spaceman commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +*   Join the discussion! `SuperchainERC20` implementation is being developed in partnership with Wonderland, with discussions taking place in the [#interop-evm](https://discord.gg/3zvcEFj6Nu) Discord
if we remove please also let's disable it from discord too, since it will remain on GH history :)

2024-10-18 17:47 UTC, cpengilly commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +```
@skeletor-spaceman @pharger -- we were thinking the simplified flow maybe worked better in docs since this is a high-level explainer (used by broader audience). Does that check out?

2024-10-18 17:50 UTC, skeletor-spaceman commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +```
it does, but the current `mermaid` flow will, imho, confuse more than a slightly more complex one.

2024-10-18 18:10 UTC, cpengilly commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +*   Join the discussion! `SuperchainERC20` implementation is being developed in partnership with Wonderland, with discussions taking place in the [#interop-evm](https://discord.gg/3zvcEFj6Nu) Discord
removing based on convos

2024-10-18 18:46 UTC, skeletor-spaceman approved these changes

2024-10-18 19:24 UTC, merged

2024-10-23 19:37 UTC, 0xParticle reviewed
Hey! I'm reviewing this on behalf of Wonderland and @skeletor-spaceman . I wrote most of the specs on this topic. 

Very good document. Some notes:
- I think a very good TLDR for the standard is: same address across chains + ICrosschainERC20 interface + only allow `SuperchainTokenBridge` to call `crosschainMint` and `crosschainBurn`. 
- There is no official method to deploy `SuperchainERC20` tokens, this is left to each token issuer. There is an official factory for `OptimismSuperchainERC20` tokens, which are ment to be converted back and forth with `OptimismMintableERC20`.
- The RIP is probably going to be an ERC. I can share the draft with you if you think it could be useful for more context regarding EVM compatibility.

2024-10-23 19:37 UTC, 0xParticle commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +*   **Permissionless propagation**: Easily clone an existing token contract to a new OP Stack chain using `create2` without requiring the original owner, which enables movement of assets to the new c
The standard itself does not enforce any deployment method. A token can be deployed using CREATE or an EOA as deployer, so posterior deployments might result in a different address.

2024-10-23 19:37 UTC, 0xParticle commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +*   **Ethereum-aligned**: Intentionally designed to be generic and supported as an Ethereum-wide standard (RIP coming soon).
nit: RIP is probably gonna be an ERC

2024-10-23 19:37 UTC, 0xParticle commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +*   **Factory Predeploy**: uses a `create2`-based factory for deploying `SuperchainERC20` tokens consistently across chains.
This is not enforced in the token standard. The `OptimismSuperchainERC20` (specific implementation of `SuperchainERC20` that can be converted back and forth with `OptimismMintableERC20`) will use an official factory (the `OptimismSuperchainERC20Factory` predeploy), but its not a requisite for every token. 
Every token does need same address across different chains to be processed by the bridge. We recommend deployments happen with a standarized method, such as the `Create2Deployer`, but again, the standard is as neutral as possible on this point.

2024-10-23 19:37 UTC, 0xParticle commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +*   **Bridging Functions**: using methods like `sendERC20` and `relayERC20` for cross-chain transfers.
you can mention these live in the Bridge contract, and not in the token itself

2024-10-23 19:37 UTC, 0xParticle commented on pages/stack/protocol/interop/superchain-erc20.mdx
> +2.  Deployment at same address on every chain in the Superchain using `create2` function.
nit: did you mean the `Create2Deployer` preinstall here? or the `CREATE2` opcode?