Transaction Finality Explainer
ethereum-optimism/docs pull request #987
Opened 2024-10-14 10:28 UTC by krofax

**Description**

Created a section on the docs to cover the nuances of transaction finality, sequencer policy and challenge periods to debunk the belief that OP Stack chains take 7 days for transaction finalization.

**Tests**

**Additional context**

**Metadata**

2024-10-23 21:54 UTC, sbvegan requested changes
Overall this is good, you've got the core concepts down. Most of my suggestions are to remove additional context to hone in on the key points we're trying to convey on this page.

2024-10-23 21:54 UTC, sbvegan commented on pages/stack/transactions/_meta.json
>      "transaction-flow": "Transaction Flow",
```suggestion
    "transaction-flow": "Transaction flow",
```

2024-10-23 21:54 UTC, sbvegan commented on pages/stack/transactions/_meta.json
>      "deposit-flow": "Deposit Flow",
```suggestion
    "deposit-flow": "Deposit flow",
```

2024-10-23 21:54 UTC, sbvegan commented on pages/stack/transactions/_meta.json
>      "withdrawal-flow": "Withdrawal Flow",
```suggestion
    "withdrawal-flow": "Withdrawal flow",
```

2024-10-23 21:54 UTC, sbvegan commented on pages/stack/transactions/_meta.json
>      "forced-transaction": "Forced Transaction"
```suggestion
    "forced-transaction": "Forced transaction"
```

2024-10-23 21:54 UTC, sbvegan commented on pages/stack/transactions/_meta.json
>      "transaction-flow": "Transaction Flow",
Let's just apply sentence case uniformely

2024-10-23 21:54 UTC, sbvegan commented on pages/stack/transactions/transaction-finality.mdx
> +This guide explains how transaction finality works in OP Stack, covering the fundamental concepts of Fault Proofs and Challenges.
```suggestion
This guide explains how transaction finality works in the OP Stack and addresses common misconceptions around transaction finality and the Fault Proof System.
```

2024-10-23 21:54 UTC, sbvegan commented on pages/stack/transactions/transaction-finality.mdx
> +OP Stack is an extension of Ethereum's consensus mechanism. Instead of running an entirely separate consensus protocol, the OP Stack leverages Ethereum's consensus.
```suggestion
The OP Stack derives its security from Ethereum by utilizing Ethereum's consensus mechanism. Instead of running an entirely separate consensus protocol, the OP Stack derives a layer 2 blockchain by reading the finalized state on Ethereum.
```

2024-10-23 21:54 UTC, sbvegan commented on pages/stack/transactions/transaction-finality.mdx
> +# Overview
```suggestion
# Transaction finality
```

2024-10-23 21:54 UTC, sbvegan commented on pages/stack/transactions/transaction-finality.mdx
> +
```suggestion
```

2024-10-23 21:54 UTC, sbvegan commented on pages/stack/transactions/transaction-finality.mdx
> +*   Attack vectors, such as double-spends, are mitigated by Ethereum's security mechanisms.
```suggestion
```

2024-10-23 21:54 UTC, sbvegan commented on pages/stack/transactions/transaction-finality.mdx
> +*   Attack vectors, such as double-spends, are mitigated by Ethereum's security mechanisms.
I recommend removing this section because I think it distracts from the key concept we're trying to illustrate in this document: Transaction finality

2024-10-23 21:54 UTC, sbvegan commented on pages/stack/transactions/transaction-finality.mdx
> +
```suggestion
```

Similar to my comment above, I think this is good context, but it detracts from the concept that we're trying to describe. I think the h2 below covers these details succinctly.

2024-10-23 21:54 UTC, sbvegan commented on pages/stack/transactions/transaction-finality.mdx
> +1.  **Unsafe:** The L2 sequencer creates a block containing the transaction, but the transaction data has not yet been posted to Ethereum (L1). The block is circulated within the L2 network for speed
```suggestion
1.  **Unsafe:** The sequencer creates a block containing the transaction, but the transaction data has not yet been posted to Ethereum (L1). The block is circulated within the L2 network for speed.
```

2024-10-23 21:54 UTC, sbvegan commented on pages/stack/transactions/transaction-finality.mdx
> +2.  **Safe:** The sequencer's batcher posts the transaction data to L1. At this point, any L2 node can derive the transaction.
```suggestion
2.  **Safe:** The batcher posts the transaction data to L1. At this point, any L2 node can derive the transaction.
```

2024-10-23 21:54 UTC, sbvegan commented on pages/stack/transactions/transaction-finality.mdx
> +3.  **Finalized:** Transactions are finalized once more than 65 Ethereum blocks (approximately 20 minutes) have passed, ensuring that the L1 data is secure and cannot be reorganized.
```suggestion
3.  **Finalized:** Transactions are finalized once more than 65 Ethereum blocks (approximately 10-15 minutes) have passed, ensuring that the L1 data is secure and cannot be reorganized.
```

65 blocks * 12s blocks / 60s = 13 min

2024-10-23 21:54 UTC, sbvegan commented on pages/stack/transactions/transaction-finality.mdx
> +## The Role of the Proof System
```suggestion
## Common misconceptions
```

2024-10-23 21:54 UTC, sbvegan commented on pages/stack/transactions/transaction-finality.mdx
> +When a block is submitted to Ethereum, it is either valid or invalid. If the block is valid, the state is updated accordingly. If it is invalid, the block is discarded. Nodes execute valid blocks and
```suggestion
### Transaction validity

When a transaction is submitted to the network, it is either valid or invalid. If the transaction is valid, the sequencer puts it in a block. If it is invalid, the transaction is discarded. There is no way the sequencer can write an invalid transaction to a new block.
```

Lets move this under the "Common misconceptions" header

2024-10-23 21:54 UTC, sbvegan commented on pages/stack/transactions/transaction-finality.mdx
> +
```suggestion
### Reorgs and finality

Once a transaction is included in a finalized Ethereum block, it cannot be reorganized. 
```

Lets move this under the "Common misconceptions" header

2024-10-23 21:54 UTC, sbvegan commented on pages/stack/transactions/transaction-finality.mdx
> +### Handling Reorgs
```suggestion
```

Lets put this content under "Reorgs and finality"

2024-10-23 21:54 UTC, sbvegan commented on pages/stack/transactions/transaction-finality.mdx
> +The proof system is entirely separate from the core OP Stack protocol. It is an application-level validation system designed to ensure the accuracy of certain claims about the transaction state.
```suggestion
The biggest misconception about transaction finality is that a transaction needs to wait for the entire challenge window to become finalized. The reality is the OP Stack transaction finality takes minutes, not over a week. This section detangles the concept of transaction finality and the Fault Proof System's challenger mechanism.
```

2024-10-23 21:54 UTC, sbvegan commented on pages/stack/transactions/transaction-finality.mdx
> +The 7-day challenge period is a reasonable time frame that allows participants to organize a response, potentially even initiating a L1 hard fork to address critical issues. In the OP Stack, this cha
```suggestion
### The role of proof system

The following is a quick refresher on the Fault Proof System. It is a system designed to ensure the accuracy of certain claims about the transaction state on the L2.

A claim in the context of OP Stack is a statement asserting the state of the system at a specific block height. For instance, a claim might assert that at block 1,000,000, the state hash is `XYZ`. If other participants believe this claim to be incorrect, they can challenge it.

Challenges focus on proving whether a given claim is valid. The outcome of a challenge does not impact the underlying chain. For example, if a claim about the transaction state at a specific block is proven wrong, it only affects the application level functionality and does not alter the OP Stack protocol.

The challenge period provides time for challenges to be raised and resolved.
Although OP Stack finalizes transactions quickly (within 20 minutes), the 7-day challenge window serves two critical purposes:

1.  It allows time to dispute the correctness of output state roots posted to Ethereum by the proposer.
2.  It provides a security period for withdrawal processing, ensuring the integrity of cross-chain operations.
```

2024-10-23 21:54 UTC, sbvegan commented on pages/stack/transactions/transaction-finality.mdx
> +### Bridge Independence
```suggestion
### Bridge independence
```

2024-10-23 21:54 UTC, sbvegan commented on pages/stack/transactions/transaction-finality.mdx
> +A custom bridge might be developed by a user to allow ERC-20 tokens to move between layers. However, this bridge is application-level and not native to the OP Stack. If there is an issue with the bri
```suggestion
For example, a custom bridge might be developed to allow ERC-20 tokens to move between layers. However, this bridge is application-level and not native to the OP Stack. If there is an issue with the bridge, such as incorrect proof validation, it does not impact the protocol itself but affects the subjective value of the bridged assets.
```

2024-10-23 21:54 UTC, sbvegan commented on pages/stack/transactions/transaction-finality.mdx
> +### Withdrawal Delays vs. Finality
```suggestion
### Withdrawal delays vs. finality
```

2024-10-23 21:54 UTC, sbvegan commented on pages/stack/transactions/transaction-finality.mdx
> +One common misconception is confusing withdrawal delays with transaction finality:
This is a big misconception, lets bump it towards the top of this section

2024-10-24 11:52 UTC, sbvegan requested changes

2024-10-24 11:52 UTC, sbvegan commented on pages/stack/transactions/transaction-finality.mdx
> +*   The sequencer cannot affect finalized transactions.
Lets drop this section underneath the, "Transaction finality states" so that topic is first

2024-10-24 11:52 UTC, sbvegan commented on pages/stack/transactions/transaction-finality.mdx
> +2.  Affected L2 blocks revert to an "unsafe" status.
```suggestion
2.  Affected `safe` L2 blocks revert to an `unsafe` status.
```

2024-10-24 11:52 UTC, sbvegan commented on pages/stack/transactions/transaction-finality.mdx
> +The Fault Proof System is designed to ensure the accuracy of certain claims about the transaction state on the L2.
```suggestion
The Fault Proof System is designed to ensure the accuracy of certain claims about the transaction state on the L2. It provides a way to prove messages from L2 to L1 are correct. It does not have to do with transaction finality.
```

2024-10-24 11:52 UTC, sbvegan commented on pages/stack/transactions/transaction-finality.mdx
> +A claim in the context of OP Stack is a statement asserting the state of the system at a specific block height. For instance, a claim might assert that at block 1,000,000, the state hash is `XYZ`. If
```suggestion
A claim in the context of OP Stack is a statement asserting the state of the system at a specific block height. For instance, a claim might assert that at block 1,000,000 a certain address has all of the ether on the entire L2. If other participants believe this claim to be incorrect, they can challenge it.
```

2024-10-24 11:52 UTC, sbvegan commented on pages/stack/transactions/transaction-finality.mdx
> +Challenges focus on proving whether a given claim is valid. The outcome of a challenge does not impact the underlying chain. For example, if a claim about the transaction state at a specific block is
```suggestion
Challenges focus on proving whether a given claim is valid. The outcome of a challenge does not impact the underlying chain. For example, if a claim about a certain address owning all the ether on the L2 is proven wrong, that address would not be able to move the ether from L2 to their address on L1.
```

2024-10-24 12:42 UTC, sbvegan approved these changes
lgtm

2024-10-25 14:30 UTC, krofax commented
@zainbacchus @smartcontracts Can i get your reviews here too?

2024-10-25 16:19 UTC, zainbacchus commented on pages/stack/transactions/transaction-finality.mdx
> +*   The sequencer cannot affect finalized transactions.
the 4th bullet point is the same as the 3rd right?

2024-10-25 16:21 UTC, zainbacchus commented on pages/stack/transactions/transaction-finality.mdx
> +### Reorgs and finality
Reorgs shouldnt be in the FP section right?, should be above the common misconceptions unless im misunderstanding

2024-10-25 16:23 UTC, zainbacchus commented on pages/stack/transactions/transaction-finality.mdx
> +2.  It provides a security period for withdrawal processing, ensuring the integrity of cross-chain operations.
think we should explain what happens if there's a successful challenge

2024-10-25 16:23 UTC, zainbacchus commented on pages/stack/transactions/transaction-finality.mdx
> +*   Withdrawal delays are application-level security features.
what does this mean?

2024-10-25 16:24 UTC, zainbacchus commented on pages/stack/transactions/transaction-finality.mdx
> +### Bridge independence
i think we can remove this section

2024-10-25 16:24 UTC, zainbacchus requested changes
added some feedback!

2024-10-28 05:06 UTC, smartcontracts commented on pages/stack/transactions/transaction-finality.mdx
> +2.  **Safe:** The batcher posts the transaction data to L1. At this point, any L2 node can derive the transaction.
Only thing worth considering here is that *technically* the sequencer and the batcher are two different things but it can often be easier to just refer to them as the same thing for the sake of clarity. So instead of `The batcher posts to the transaction data to L1` you might want to say `The Sequencer posts the transaction data to L1`.

2024-10-28 05:06 UTC, smartcontracts commented on pages/stack/transactions/transaction-finality.mdx
> +1.  **Unsafe:** The sequencer creates a block containing the transaction, but the transaction data has not yet been posted to Ethereum (L1). The block is circulated within the L2 network for speed.
I prefer to capitalize the names of actors within the system, so `sequencer => Sequencer`.

2024-10-28 05:10 UTC, smartcontracts commented on pages/stack/transactions/transaction-finality.mdx
> +3.  **Finalized:** Transactions are finalized once more than 65 Ethereum blocks (approximately 10-15 minutes) have passed, ensuring that the L1 data is secure and cannot be reorganized.
This isn't correct, an Ethereum transaction is not finalize after exactly 65 blocks, it depends on 2/3rds of validator signing off 2 back to back checkpoints. In *general* this takes about 2 epochs or 65 blocks / 12.8 minutes but it can take much longer in bad network conditions.

2024-10-28 05:11 UTC, smartcontracts commented on pages/stack/transactions/transaction-finality.mdx
> +When a transaction is submitted to the network, it is either valid or invalid. If the transaction is valid, the sequencer puts it in a block. If it is invalid, the transaction is discarded. There is
The Sequencer *can* attempt to publish a block that contains an invalid transaction but this will be rejected by the rest of the network

2024-10-28 05:11 UTC, smartcontracts commented on pages/stack/transactions/transaction-finality.mdx
> +*   Once transactions are published on L1, the sequencer cannot modify or censor them.
Not true, in theory the Sequencer can still modify things until finality is reached because you can have reorgs

2024-10-28 05:12 UTC, smartcontracts commented on pages/stack/transactions/transaction-finality.mdx
> +If an Ethereum reorganization (reorg) occurs:
```suggestion
If an Ethereum reorganization (reorg) were to occur *before* finality:
```

2024-10-28 05:13 UTC, smartcontracts commented on pages/stack/transactions/transaction-finality.mdx
> +The Fault Proof System is designed to ensure the accuracy of certain claims about the transaction state on the L2. It provides a way to prove messages from L2 to L1 are correct. It does not have to d
The Fault Proof System is used by *bridge* contracts on L1 to verify claims that users make about the state of L2 for the purpose of facilitating user withdrawals of certain bridged assets from L2 to L1.

2024-10-28 05:14 UTC, smartcontracts commented on pages/stack/transactions/transaction-finality.mdx
> +2.  It provides a security period for withdrawal processing, ensuring the integrity of cross-chain operations.
Yes, illustrate both examples clearly

2024-10-28 05:15 UTC, smartcontracts commented on pages/stack/transactions/transaction-finality.mdx
> +### The role of proof system
Much of this is confusing because it still doesn't present the Optimism bridge as an application rather than a core part of the rollup. It's important to start by demonstrating that the bridge is an application and that it's the bridge that uses the proof system, not the rollup.

2024-10-28 05:16 UTC, smartcontracts commented on pages/stack/transactions/transaction-finality.mdx
> +### Bridge independence
I think the core concepts of this section are important but it needs to be made more specific to the Optimism bridge and needs to be included higher up. Withdrawals are NOT a part of the core protocol. They are an app-level construct.

2024-11-06 11:35 UTC, krofax commented on pages/stack/transactions/transaction-finality.mdx
> +TODO: It'd be really fun to have a button that (for the bond cost of 0.08 ETH) creates a bad withdrawal claim for all of the ETH in the bridge. Users would be able to see first hand how their claim g
@smartcontracts How do we want to approach this?

2024-11-06 16:34 UTC, cpengilly approved these changes

2024-11-07 08:25 UTC, smartcontracts commented on pages/stack/transactions/transaction-finality.mdx
> +2.  The Sequencer includes the transaction in a block and distributes it over a public peer-to-peer network. At this point, the transaction is considered **"unsafe"**. A technical term indicating tha
```suggestion
2.  The Sequencer includes the transaction in a block and distributes it over a public peer-to-peer network. At this point, the transaction is considered **"unsafe"**, a technical term indicating that the transaction is in a block but its data has not yet been posted to Ethereum. This process typically takes only a few seconds.
```

2024-11-07 08:25 UTC, smartcontracts commented on pages/stack/transactions/transaction-finality.mdx
> +3.  The Sequencer publishes this block's data to Ethereum, either as [blob data](https://www.eip4844.com/) or as calldata attached to a standard Ethereum transaction. Once included in an Ethereum blo
```suggestion
3.  The Sequencer publishes this block's data to Ethereum, either as [blob data](https://www.eip4844.com/) or as calldata attached to a standard Ethereum transaction. Once included in an Ethereum block, the transaction is considered **"safe"**. This step usually takes 5–10 minutes.
```

2024-11-07 08:25 UTC, smartcontracts commented on pages/stack/transactions/transaction-finality.mdx
> +TODO: Fix this so it has the right numbers
Can get rid of this TODO, looks right

2024-11-07 08:25 UTC, smartcontracts commented on pages/stack/transactions/transaction-finality.mdx
> +This misconception often arises due to the OP Stack's Standard Bridge, which includes a 7-day delay on *withdrawals* of ETH and ERC-20 tokens. Withdrawing tokens from an OP Stack chain to Ethereum us
```suggestion
This misconception often arises due to the OP Stack's Standard Bridge, which includes a 7-day delay on *withdrawals* of ETH and ERC-20 tokens. Withdrawing tokens from an OP Stack chain to Ethereum using the Standard Bridge requires a minimum 7-day wait. This delay affects only withdrawals through the Standard Bridge and does not impact transaction finality on the OP Stack chain.
```

2024-11-07 08:25 UTC, smartcontracts commented on pages/stack/transactions/transaction-finality.mdx
> +TODO: It'd be really fun to have a button that (for the bond cost of 0.08 ETH) creates a bad withdrawal claim for all of the ETH in the bridge. Users would be able to see first hand how their claim g
Can skip it for now but it would be a cool addition down the line

2024-11-07 08:25 UTC, smartcontracts commented on pages/stack/transactions/transaction-finality.mdx
> +Another misconception related to the belief that [finalization takes 7 days](#misconception-transactions-take-7-days-to-finalize) is that **Fault Proof challenges** created in response to withdrawals
```suggestion
Another misconception related to the belief that [finalization takes 7 days](#misconception-transactions-take-7-days-to-finalize) is that **Fault Proof challenges** created in response to withdrawals in the Standard Bridge can reorganize the OP Stack chain. **This is incorrect.** OP Stack transactions are not reorganized in response to Fault Proof challenges.
```

2024-11-07 08:25 UTC, smartcontracts commented on pages/stack/transactions/transaction-finality.mdx
> +A common misconception is that the Sequencer can trigger reorganizations of the OP Stack chain at any time. However, while the Sequencer can reorganize **"unsafe"** blocks (not yet published to Ether
```suggestion
A common misconception is that the Sequencer can trigger reorganizations of the OP Stack chain at any time. However, while the Sequencer can reorganize **"unsafe"** blocks (not yet published to Ethereum), reorganizations become more challenging once blocks are **"safe"** and become effectively impossible once blocks are **"finalized."**
```

2024-11-07 14:50 UTC, zainbacchus commented on pages/stack/transactions/transaction-finality.mdx
> +TODO: Fix this so it has the right numbers
You still have the TODO in here

2024-11-07 14:51 UTC, zainbacchus approved these changes
Still todos

2024-11-07 14:55 UTC, krofax commented
> Still todos

Removed.

2024-11-08 13:08 UTC, merged